### ISSUE TITLE
Mock PE level 6

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2030/2021-s1#100]
I'm confused by what I have to implement for level 6? If I understand it correctly, I need to implement a way to check whether a person is under SHN, but regarding DormWithShn class, am I suppose to extend dorm? And what methods should be implemented in DormWithShn, like what methods is it suppose to have? Thanks for your help

**Comment by JedrekLoo** [comment]
Hi, you are supposed to implement DormsWithShn extending Dorms
The only method required in DormsWithShn is `void handleSickPerson` and maybe another method to help you log the shn served

**Comment by ramapriyan912001** [comment]
Yep ^
The Dorms class clearly mentions which classes are important to the implementation of DormsWithShn.
