### ISSUE TITLE
Mock PE Submission to CodeCrunch

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#106]
# Description 
Hi, I was trying to submit my files to CodeCrunch but I got the following error:
![photo_2020-09-27_22-14-21](https://user-images.githubusercontent.com/70755428/94367298-59a4a900-0110-11eb-8e44-4e295ff8bec5.jpg)
which doesn't really make sense to me cause I'm not controlling the jshell inputs?
Is there something wrong on my end that I need to fix?

**Comment by yonggqiii** [comment]
@shhiiiqqqqiiiii there was a bug with the test files, hold on for a few minutes for me to resolve it. Thanks!

**Comment by yonggqiii** [comment]
@shhiiiqqqqiiiii resolved, thanks!
