### ISSUE TITLE
Project 1 level 3

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#107]
# Description 
Hi guys I was attempting level 3 of the project and was unsure if i should declare Event as an interface or as a class since every subsequent event will all have the attributes of Customer and the List of servers. If i implement even as an interface, then my Done Event technically wont have to implement the event interface even though it is still an Event. Would appreciate any ideas thank you!

## Topic: 
Interface/Class

**Comment by tlylt** [comment]
If there are some methods that have the same implementation across all events, then choosing the interface approach may prevent you from filling in the implementation details in the Event interface itself (unless impure I suppose).

**Comment by Paulynlhx** [comment]
You could also consider using an abstract class such that you don't have to implement the method too. Using abstract class could also allow you make other events without initialising the instance variable !!

**Comment by Jiwei99** [comment]
It depends if you want to declare more functions inside Event that can be inherited / used by all subclass of event. If so, using abstract class will be more appropriate. if not, I think interface will work too.

**Comment by SkyBlaise99** [comment]
Usually you will use an `abstract class` since you want

> every subsequent event will all have the attributes of Customer and the List of servers

and

> If i implement even as an interface, then my Done Event technically wont have to implement the event interface even though it is still an Event

**Comment by kohkenneth** [comment]
@tlylt @Paulynlhx @SkyBlaise99 @Jiwei99 thanks for all the input! really appreciate it!
