### ISSUE TITLE
Lab #4 ImmutableList.equals()

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#115]
# Description 
Greetings fellow 2030ers, abit late to be asking this but I'm a bit stuck on this one seemingly simple problem. When an ImmutableList is typecasted into (Object) and passed into ImmutableList.equals(ImmutableList<T> list), the Object.equals(Object o) is called instead, and it's understood because the list has been typecasted into Object.

My approach so far is to catch it in the overloaded ImmutableList.equals(Object o) (using instanceof) and calling the list.equals() method, basically overloading my .equals() with different method signatures. I can add a screenshot of my code if its allowed, but I think you get the point.

Anyway, any suggested alternative ideas? I can't seem to get around this without typecasting the object back, but I have to use SuppressWarnings("unchecked"), which is banned in codeCrunch :( Any feedback would be greatly appreciated!

## Topic: 
Lab #4 ImmutableList

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/61898858/94580259-49293580-02ac-11eb-92bb-f07f396ada4e.png)

**Comment by lkldev** [comment]
Hi, as mention by the lab, we have to override the method instead of overloading it. As to how to overcome the uncheck warnings, you might want to refer to lecture 4 on generics and look at how wildcards can help you in this scenario. Hope this helps :)

**Comment by ghost** [comment]
It worked!! Some things I just learnt today:

In general, do not change the method signature of equals(Object). Override, not overload (credits to my TA)
Typecasting is done using <?> instead of <T>, guess I somehow missed that part of the lecture
Do not resort to suppressWarnings

Also major thanks to @lkldev appreciate it brother/sister.
