### ISSUE TITLE
Project1 Level 3 Issue : Cannot find symbol - symbol: method execute()

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#117]
I'm having some issues with chaining .execute() method in my project. Basically I can call .execute() once on my ArriveEvent and it correctly returns my output for ServeEvent, but when I call it again (i.e. .execute().execute()), I get a message saying the method execute() can't be found now. However I've already written the execute() method into all the relevant classes including ServeEvent.java. I've checked for any errors within the classes but I can't seem to find the cause of the issue. 

All my event states extend from Event.java. I don't have an abstract execute method in my Event.java class since DoneEvent.java and LeaveEvent.java doesnt have/need to use an execute method.

<img width="611" alt="2020-09-30 (5)" src="https://user-images.githubusercontent.com/72072042/94618418-b7d2b700-02dd-11eb-8d9b-d8c59d0b1f6a.png">

**Comment by yuanxin1997** [comment]
If you are calling helper method from other java class. you will need to open them as well.
E.g SimulationParameters.java    ,SafeEntry.java , LocationDatabase.java  , and ect.

**Comment by yuanxin1997** [comment]
you need to open all relevant the java files.  E.g WaitEvent.java.. ArriveEvent, LeaveEvent, Event...

**Comment by yuanxintaxon** [comment]
you need to open all the relevant java files. E.g WaitEvent.java.. ArriveEvent, LeaveEvent, Event...

**Comment by marcuspeh** [comment]
Is your other event class open?

**Comment by yuanxin1997** [comment]
If your class contains method/class from other classes, you need to open them as well. 

I think you’ve forgotten to open some files. You can try to open them and see if it works

**Comment by kohkenneth** [comment]
I think you must open the other files in bottom up dependency before you'll be able to run this

**Comment by b-leong** [comment]
you could try fixing the execute method for serve and writing the execute method for Done & Leave that returns itself

**Comment by Clem-cpu** [comment]
Do u have an abstract method in ur events class for execute(). And also does your execute event return the corresponding event and not just the string output

**Comment by Jcheez** [comment]
It seems like you have a problem with your ServeEvent's execute. It should be returning a DoneEvent. Also, u should have an abstract method for execute in your Events.java. For Done and Leave, you can return the same event since the process ends when an event reaches done and leave.

**Comment by dljw98** [comment]
Thank you all! The issue was because I didn't have an abstract execute() method in my Event class.
