### ISSUE TITLE
Lab4 Level4 equals(ImmutableList<T> t) method

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#118]
I keep failing this particular test in codecrunch:

![photo_2020-09-30_00-31-38](https://user-images.githubusercontent.com/72072042/94619129-e9984d80-02de-11eb-9b72-e7b7e177f3c5.jpg)

I've tried type-casting t into (ImmutableList<T>) t, in my .equals method but it doesn't seem to work either. 
Essentially what I'm doing in my equals method is I check if they are of the same .size() first, then I proceed to run a for loop where I compare each element to see if they are .equals to each other. 

For reference, here is my  relevant ImmutableList constructor

![photo_2020-09-30_01-05-13](https://user-images.githubusercontent.com/72072042/94619636-cf12a400-02df-11eb-8ae2-f7f63fad81fd.jpg)

May I know how to get past this particular test?

**Comment by enqiilim** [comment]
hi, i ran into this same problem, may i know how you solved it?

**Comment by marcuspeh** [comment]
> hi, i ran into this same problem, may i know how you solved it?

It's because your equal method did not override but instead overload (it takes in ImmutableList instead of object)
