### ISSUE TITLE
Double/Float Precision issues

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#120]
Hi, Prof Terence has commented on one of the issues with regards to the title above. How did you guys implement it? I actually didn't as mine was fine.. I'm not too sure how to use [prof's method](https://github.com/nus-cs2030/2021-s1/issues/82#issuecomment-698186493), if anyone can please show?

```java
boolean closeEnough(double a, double b) {
   double tolerance = 1E-4;
   return Math.abs(a-b) < tolerance;
}
```

Thanks!

**Comment by zzkzzzz** [comment]
So basically, if the difference between `a` and `b` is small enough, less than the tolerance `0.0001` given. Then we treat these two numbers are equal.  
`closeEnough(1.00009,1)` will return true `0.00009<0.0001`which means `1.00009`and `1` are equal.
`closeEnough(1.1,1)` will return false `0.1>0.0001` which means `1.1` and `1` are not equal.
We can change the tolerance base on different situations. In the project, `tolerance = 1E-4;` is good enough.

Hope this helps.

**Comment by Octanis0** [comment]
Use ```closeEnough(a, b)``` as a 'looser' version of ```(a == b)``` where ```a``` and ```b``` can be different from each other by ```tolerance = 1E-4``` and still be counted as equal to each other.

**Comment by domlimm** [comment]
Thanks yboth! @zzkzzzz @Octanis0
