### ISSUE TITLE
Project 1: Is modifying the toString() method of classes to execute operations good practice?

### ISSUE THREAD

**Issue by Josephaedan** [nus-cs2030/2021-s1#121]
## Description
For Project 1 Level 4, we are instructed to use PriorityQueue to simulate and print the events in order as output. Level 3 also prepares us to pass in a list of servers as a parameter into the event classes and to implement .execute() methods to them. Hence, I'd assume most people pass in a consistent referenced list of servers into each event that updates the state of the servers as the simulation goes using the execute() method.

**However, I'd like to ask if it is good coding practice to update this list of servers in the toString() method instead of the execute() method**, as that is what I have done. My rationale was that my simulation would have to run the toString() method of the event to print the event sequence, hence I could use the toString() method to update my list of servers instead of the execute() method which would run only later on. A sample of my Event's .toString() method is included below.

`    
@Override

    public String toString() {

        getServers().set(index, server.serve(getEventTime()));

        return String.format("%.3f %s served by %s", getEventTime(), getCustomer().getID(), server.getID());

    }
`

Given that the name of the method itself is toString(), would implementing other operations inside the method be considered good practice?

## Topic: 
Project 1

## Screenshots (if any): 
Insert Images here if necessary

**Comment by rohit0718** [comment]
by the Single Responsibility Principle, i dont think doing such a thing is advised

**Comment by tlylt** [comment]
Agree with @rohit0718 

Maybe a slight improvement to the code can be the following. 
```java
public void updateServers() {
    getServers().set(index, server.serve(getEventTime()));
}

public String toString() {
    updateServers();
    return String.format("%.3f %s served by %s", getEventTime(), getCustomer().getID(), server.getID());
}
```
Then again if we can extract out the updateServers() method, then I guess we can simply invoke this updateServers() method directly before or after the printing of the event. 
```java
//...
event.updateServers();
System.out.println(event);
//...
```

Just my 2 cents.

**Comment by Josephaedan** [comment]
> Then again if we can extract out the updateServers() method, then I guess we can simply invoke this updateServers() method directly before or after the printing of the event.
> 
> ```java
> //...
> event.updateServers();
> System.out.println(event);
> //...
> ```
> 
> Just my 2 cents.

Ah, understood and agreed, I think that's much better. Thank you for the suggestions!
