### ISSUE TITLE
Lab4 Level5 ArrayStoreException

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#122]
I'm a bit stumped on how to check for ArrayStoreException in lab4 level5. 
The method I'm referring to is the one that goes <U> U[] toArray(U[] u). I've tried to try-catch-throw new ArrayStoreException("...") but my "..." error message wasn't printed out when the error was encountered. So I've been trying to do if(some condition) then throw new ArrayStoreException("..."). However I can't seem to figure out how to make my condition serviceable. 

Also, why doesn't if (!(U instanceof T)) work?

**Comment by tlylt** [comment]
Hate to be the guy but try searching it under issues...
![image](https://user-images.githubusercontent.com/41845017/94671796-e8027000-0346-11eb-96ce-76c7071499b4.png)

**Comment by dljw98** [comment]
Ah sorry about that - should have searched beforehand
