### ISSUE TITLE
Mock Practical Level 6

### ISSUE THREAD

**Issue by CWei88** [nus-cs2030/2021-s1#124]
# Description 
When I run the Mock Practical java Main -v using a barebone DormsWithShn.java to see how it looks like, it only outputs the test and the people that had entered during time 0.000. I checked Main.java and found that those events without a SHN use the Dorms.java implementation, which I have not made any changes to.

Why is my output different from the one on CodeCrunch despite the fact that I have not made changes to Dorms.java? The output is attached below.

## Screenshots (if any): 
![Capture](https://user-images.githubusercontent.com/64974354/94691202-99af9a00-0363-11eb-9e64-959187d7aaf7.PNG)

**Comment by tanruiquan** [comment]
Perhaps check your onSHN method in Person class? I had the opposite problem (everyone except those that entered during 0.000 appeared) and making some changes in the onSHN method solved it.

**Comment by CWei88** [comment]
Thanks that was the problem it worked!
