### ISSUE TITLE
Project 1 JavaDocs / Documentation

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#125]
I’ve already completed all levels of the project and passed all test cases. Just wanted to ask if I’m supposed to submit a JavaDocs documentation? 

It’s stated in this prev announcement that documentation is included in the grading:
<img width="890" alt="Screenshot 2020-09-30 at 10 54 23 PM" src="https://user-images.githubusercontent.com/39799639/94703547-873c5d00-0371-11eb-9910-c9f0c3f4580a.png">

But Javadocs files are in html and I can’t submit html files onto Codecrunch, in this case, will relevant comments in the individual java files be sufficient?

**Comment by marcuspeh** [comment]
Nope i think its just the javadoc comment in your java file

**Comment by SkyBlaise99** [comment]
I think it means to pass the checkstyle can alr.
