### ISSUE TITLE
Project 1 help: Immutability of Event class and level 4

### ISSUE THREAD

**Issue by SeanEng** [nus-cs2030/2021-s1#138]
Hi guys, I would like to clarify what exactly is immutability. For the my serverList in Event class, I assumed that for it to be immutable, all execute methods will not modify this list in anyway, and instead create a deep copy of the list to pass onto the constructor for the next event instead. 

However, this causes problems in level 4, as the execution of 1 event does not cause the other events in my PriorityQueue to have a changed configuration of the server in their serverList. 

The only solution I can think of at the moment is to remove my code that creates a deep copy, and just change the contents of the serverList with .set method instead, but I am uncertain if that violates Event being Immutable. 

Please help me clarify my doubts! And if doing the above violates immutability, what other way can I use to update my serverList each time I execute

**Comment by domlimm** [comment]
Hi Sean, whatever you said it's correct. So we were told that each Server is immutable, however the only way i think we can do this is to update the serversList with a `new Server(...);` using `List.set(...)`

I've done all my updating inside the stateEvent classes themselves.

Maybe take a look at these #76, #136  and the opened/closed issues relating to Project 1 on how to go about dealing with this

**Comment by FergusMok** [comment]
You could still continue to implement level4 using your deep-copy, but I don't think it's the more "elegant" design. The one @domsterthebot mentioned should be better.

A way to do this would be to create a new instance of every other unexecuted Event every time you poll, with the updated Customer / Server from the previous execution. Through this, the previous instance will just be merely discarded, and your new instance will be added back.

**Comment by SeanEng** [comment]
Thanks for the help guys, I've decided to use the method mentioned by @domsterthebot .

> update the serversList with a `new Server(...);` using `List.set(...)`
