### ISSUE TITLE
Project 1: unable to use class until another is declared

### ISSUE THREAD

**Issue by fantablack** [nus-cs2030/2021-s1#140]
# Description 
I am currently working on level 4. I legit thought all was good thus far until I submitted my code for level 3 (which passed all test cases in the project brief). To my horror, I encountered: 
![image](https://user-images.githubusercontent.com/12153882/95009418-8b5bc980-0654-11eb-9fe5-30b0c99eb12c.png)

So, I re-designed what was originally an abstract Event class to an Event interface now (since my child classes can no longer inherit fields from Event if they are all private final).

Sadly, I now can't even run a single test case from level 3, and I can't for the love of God figure out why. Any help would be greatly appreciated esp since its the last day already jesus christ

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/12153882/95009529-58fe9c00-0655-11eb-88e9-97e92a8e8a84.png)

**Comment by marcuspeh** [comment]
Did you open all your events? Perhaps your leave event is misspelled

**Comment by fantablack** [comment]
Oh my god apparently it was because my LeaveEvent didn't implement an abstract method from its implemented interface. Man just wish that I could get a more accurate and relevant error message.

Thanks @marcuspeh 👍 , your comment led me on an investigation within my LeaveEvent that helped me to realize what was wrong.
