### ISSUE TITLE
Lab 4 Level 5

### ISSUE THREAD

**Issue by hengyiqun** [nus-cs2030/2021-s1#143]
# Description 
Help needed for Lab 4 Level 5

## Topic: 
During the test case for toArray(new String[0]), my program returns the following output which differs slightly from the expected output. I am not sure how this error with my program arises. Did anyone face similar issues and have successfully resolved it?

## Screenshots 

Screenshots (if any)
![image](https://user-images.githubusercontent.com/20364508/95021277-a48b6700-06a2-11eb-8653-e6c1e4e5c123.png)

**Comment by lkldev** [comment]
Hi, it seems like your code did not "override" the `ArrayStoreException` error. Did you try to catch the `ArrayStoreException` in your `toArray` method and throw a new `ArrayStoreException` error (with the customized message) from there?

**Comment by jessicajacelyn** [comment]
In your catch instead of `System.out.println(e)` try throwing in a new `ArrayStoreException` instead, so it will be like:
```
catch (Exception e) {
    throw new ArrayStoreException("Cannot add element to array as it is the wrong type");
}
```

**Comment by hengyiqun** [comment]
Thanks for the kind help. It worked for me!
