### ISSUE TITLE
How to resolve java.lang.UnsupportedOperationException?

### ISSUE THREAD

**Issue by merylseow** [nus-cs2030/2021-s1#156]
# Description 
Hi does anybody know how to resolve this error? I think it has to do with the temp.add(input) function of List but I'm not sure why it doesn't work and how to go about correcting it.

## Topic: 
List, ArrayList

## Screenshots (if any): 
![Screenshot 2020-10-06 at 5 36 29 PM](https://user-images.githubusercontent.com/71954278/95211233-e50fef80-081e-11eb-97b6-06e60bcf8b00.png)
![Screenshot 2020-10-06 at 9 57 55 PM](https://user-images.githubusercontent.com/71954278/95211320-007afa80-081f-11eb-87bc-4445a510b672.png)

**Comment by waynetee** [comment]
Your temp seems to be a list that does not support the add operation.

I'm not sure how you are getting your temp but you can try `new ArrayList<>(temp)` to get a list that can be added to

Hope this helps

**Comment by merylseow** [comment]
Hi Wayne! Thanks for replying my question :)
What I did was that I had an attribute `private final List<ScheduledClass> classList;` and the issue first surfaced when I used classList.add(input) so I thought maybe could be due to the immutability of the list so I went to introduce a new variable temp `List<ScheduledClass> temp = new ArrayList<>(classList)` but still doesn't seem to work :/

**Comment by jessicajacelyn** [comment]
I found this online and hope it might help! 
This error often occur when you're trying to add things to a fixed-sized List.

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/46324855/95220001-9404f900-0828-11eb-9e75-d847eed7bfb3.png">

[src: https://www.baeldung.com/java-list-unsupported-operation-exception]

**Comment by waynetee** [comment]
Hi Meryl, here's my attempt at reproducing the problem.

```
jshell> List<Integer> a = Arrays.asList(1)
a ==> [1]

jshell> a.add(2)
|  Exception java.lang.UnsupportedOperationException
|        at AbstractList.add (AbstractList.java:153)
|        at AbstractList.add (AbstractList.java:111)
|        at (#2:1)

jshell> List<Integer> b = new ArrayList<>(a)
b ==> [1]

jshell> b.add(2)
$4 ==> true
```
As you can see, making a new list works in this case. So it's a little strange why it isn't working for you

How are you constructing classList? Is it some special list?

**Comment by ghost** [comment]
In temp.add(c), are you sure about c being of type ScheduledClass, or is c an index pointing somewhere? Maybe that could be the problem, I'm not too sure, but the problem (in theory) should not be about the ArrayList not supporting the add() function.

**Comment by bwangpj** [comment]
Hi Meryl, you seem to be inadvertently using an immutable list somewhere; furthermore the root of the problem seems to arise via a `sort` that you are calling on this list. 

How was your `classList` initialised? Note that the `List.of` method, as specified in the Java API, returns an _immutable_ list. For example:

```
jshell> List<Integer> newList = List.of(3,2,1)
newList ==> [3, 2, 1]

jshell> Comparator<Integer> someComparator = ...

jshell> newList.sort(someComparator)
|  Exception java.lang.UnsupportedOperationException
|        at ImmutableCollections.uoe (ImmutableCollections.java:72)
|        at ImmutableCollections$AbstractImmutableList.sort (ImmutableCollections.java:111)
|        at (#3:1)
```

This almost exactly reproduces the error you encountered.

**Comment by merylseow** [comment]
Hi everyone! Thanks for helping me, I have finally solved the issue!
