### ISSUE TITLE
PE1 clashWith()

### ISSUE THREAD

**Issue by nicolej2122** [nus-cs2030/2021-s1#159]
<img width="704" alt="Screenshot 2020-10-08 at 1 46 10 AM" src="https://user-images.githubusercontent.com/60281524/95368230-6a230380-0908-11eb-874d-4848e10c342a.png">
Why are these two classes not considered to be clashing?

**Comment by dtse2401** [comment]
I assume you mean the last two lines of output. In that case, then it's because the modules are different

**Comment by nicolej2122** [comment]
<img width="713" alt="Screenshot 2020-10-08 at 2 12 39 AM" src="https://user-images.githubusercontent.com/60281524/95370726-cfc4bf00-090b-11eb-805d-9709c76a8994.png">
But isn't the module different in this as well, but here it is considered to be clashing

**Comment by dtse2401** [comment]
There it clashes because the venue is the same. If the venue were different, there would be no clash. 

Level 3 alone does not test for many of the cases that level 4 does, I would suggest relying on test4 to check your logic for clashWith!

**Comment by SkyBlaise99** [comment]
Actually, you need both level 3 and level 4 to check. I had once that I passed level 4 but then failed level 3 instead

**Comment by merylseow** [comment]
I had the same issue initially too since the phrasing seems unclear. You may want to refer to #152, I think they pretty much clarified everything.
