### ISSUE TITLE
PE1 Level 4

### ISSUE THREAD

**Issue by KaushikR1999** [nus-cs2030/2021-s1#161]
# Description 
Hi, so my add method in the Schedule class has a return type of Schedule and thus whenever the add method is invoked and a new Schedule is returned, the toString method of the new Schedule is invoked too. However, this results in my code failing the codecrunch test cases, as it only requires the toString method to be invoked when System.out.println() is called on the Schedule object. Thus, I'm unsure if there's a way to ensure that the toString method is invoked only when System.out.println() is called on the object. Hope someone can assist me in this issue. Thank you.

## Screenshots (if any): 
<img width="1331" alt="PE1 Level 4" src="https://user-images.githubusercontent.com/58514719/95533681-654c7580-0a16-11eb-84f4-3f5bb78d31f9.png">

**Comment by merylseow** [comment]
Hm I'm not sure how you implemented your toString method but from your output it seems like you put your System.out.println() in your toString, which shouldn't be the case. If it's possible can you share your toString code?

**Comment by KaushikR1999** [comment]
Hi yes sorry I just realised it's because I'm printing the contents of the list in my Schedule object instead of returning them. But I'm unsure of how to return items in a list line by line?

Currently my toString method prints the contents of the list through a loop and returns "" (an empty String)

**Comment by lkldev** [comment]
Hi, you can loop through your list in the toString method and concatenate the objects into a String variable instead of using `System.out.println` in your toString. You can then return the String variable. Hope this helps :)

**Comment by merylseow** [comment]
Yep as mentioned above. Introduce a variable `st = ""`, run a for loop through your list and keep concatenating to st, then return st.

**Comment by charoi** [comment]
Yup! Also would help if you used "\n" so your string is returned line by line. :)

**Comment by KaushikR1999** [comment]
Thanks for all the help! I realised I had forgotten about "\n" and that's why I was struggling
