### ISSUE TITLE
PE1 Cannot find symbol:class Schedule?

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#162]
I’ve had it up to my neck with Codecrunch, my entire code works fine in my terminal & in jshell, but when I upload the files to Codecrunch, it somehow is not able to find the Schedule class?? What is going on?

And before anyone asks:
- Yes I have made all properties private & final, and classes public.
- Yes I have uploaded all my other classes that are used for Schedule()
- Yes I have checked for any possible spelling mistakes in my code. 

The only possible explanation I can think of is that some part of my code logic has been disallowed on codecrunch, maybe a package import, which rendered my entire code uncompilable.

My only imports were java.util list, arraylist, and comparator, I didn’t use any obscure 3rd party library/methods, what went wrong?

![Screenshot 2020-10-09 at 12 37 42 PM](https://user-images.githubusercontent.com/39799639/95544233-1958fb00-0a2d-11eb-9f0e-b75434a673ca.jpg)
![Screenshot 2020-10-09 at 12 37 52 PM](https://user-images.githubusercontent.com/39799639/95544237-1b22be80-0a2d-11eb-8c85-73075be409e5.jpg)

**Comment by domlimm** [comment]
You probably didn't implement this constructor:

```java
public Schedule () { ... }
```

**Comment by EssWhyy** [comment]
@domsterthebot Nope, I have already implemented an overridden constructor. Still doesn't register on Codecrunch...
If anyone wants to check my full code, can send me a private message.
<img width="532" alt="Screenshot 2020-10-09 at 3 02 57 PM" src="https://user-images.githubusercontent.com/39799639/95553311-e02a8600-0a40-11eb-996e-fddddaf8ae00.png">

**Comment by marcuspeh** [comment]
Try change the class name for class2 to lesson or something like that

**Comment by EssWhyy** [comment]
I figured it out, turns out I was missing an import statement for one of my files, so even though it worked in jshell, it wouldn't actually compile.
