### ISSUE TITLE
KeyableMap<Optional<V>>

### ISSUE THREAD

**Issue by yhtMinceraft1010X** [nus-cs2030/2021-s1#163]
Not sure why, but I'm getting something like this:
![image](https://user-images.githubusercontent.com/69678785/95568355-b3816900-0a56-11eb-8c8a-174826f10806.png)

**Comment by yhtMinceraft1010X** [comment]
Turns out putting double <> isn't recognised for declaring a new class. My bad.

**Comment by wei2912** [comment]
If you'd like to implement this behaviour, you can try using something like `class KeyableMap<V extends Optional>` (see https://www.tutorialspoint.com/how-can-we-restrict-generics-type-parameter-to-sub-classes-of-a-particular-class-in-java). That said, your `KeyableMap` should not require this behaviour. IIRC this part of the lab states only to change the `get` method such that it returns an `Optional`, not to enforce that `KeyableMap` has a type parameter restricted to `Optional`.
