### ISSUE TITLE
PE1 level 4 test case 5

### ISSUE THREAD

**Issue by adelineT-jy** [nus-cs2030/2021-s1#167]
Hi, does anyone know what might have caused this issue?
Thank you. 
![image](https://user-images.githubusercontent.com/72067023/95595258-8cd72880-0a7e-11eb-88a0-62cf9fc84e24.png)

**Comment by bwangpj** [comment]
The lectures in lines 14 and 15 of your output clash in timing. Same for lines 16 and 17.

**Comment by chuashiqi** [comment]
it's because line 14 clashes with line 15 and line 16 clashes with line 17! might wanna check your clashWith method

**Comment by adelineT-jy** [comment]
ohhh thank you! I didnt realise that.
