### ISSUE TITLE
Vim AutoComplete Plug in

### ISSUE THREAD

**Issue by KaiyueSong** [nus-cs2030/2021-s1#17]
# Summary
Want to know how our vim can be like the one in the videos where we don't need to type everything word by word.

## Description 
Suppose I want print out sth, I need to write:
     System.out.printf("%s says Hello World!\n", this.name);
But the teacher has some auto completed things for him to choose.

I installed supertab but it is not as powerful as the teacher's is.

Is it achieved by adding some Plug-ins? If yes, what is the name of it?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/69779034/90482770-522fce80-e166-11ea-981e-0e2cb66c2669.png)

**Comment by yonggqiii** [comment]
See issue #10, the YouTube video explains it all.
