### ISSUE TITLE
Implementing abstract methods in subclasses

### ISSUE THREAD

**Issue by juayhee** [nus-cs2030/2021-s1#171]
# Description 
My understanding is that subclasses should always implement the abstract methods of the parent classes.
For example, in the Comparator<T> interface:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Comparator.html

However, why is it that when creating a comparator class that implements Comparator, we sometimes only override the compare() abstract method? What about the equals() abstract method?

## Topic: 
Comparator,  Java API

**Comment by ramapriyan912001** [comment]
I reckon that given the absence of an equals method, it would just default to the Object equals method, given that all classes automatically inherit from the Object class anyways.

"Note that it is always safe not to override Object.equals(Object). However, overriding this method may, in some cases, improve performance by allowing programs to determine that two distinct comparators impose the same order."
-From the equals method section of the documentation for the Comparator interface

Hope this helps!

**Comment by juayhee** [comment]
So I suppose, when implementing Comparator objects using lambda expressions, the compiler will choose the override the method in the Comparator interface that does not have a superclass implementation already? (so in this case, the compare() method instead of the equals() method, since equals is already provided by Object)
