### ISSUE TITLE
PE Level 4

### ISSUE THREAD

**Issue by sushmit98** [nus-cs2030/2021-s1#174]
Hi Guys! One of the test cases in level 4 is System.out.println(s0) again, after adding L1 and T1 to Schedule s. The output for s is correct, but for some reason, my s0 is getting updated too. Does anyone have any idea on why this might be the case? Below is my output for reference if what I mentioned above was a bit unclear.

My output:
<img width="673" alt="Screenshot 2020-10-10 at 10 27 35 PM" src="https://user-images.githubusercontent.com/59364334/95657582-cd4ea900-0b47-11eb-9100-cee9564d4bbb.png">

Correct output on CodeCrunch
<img width="657" alt="Screenshot 2020-10-10 at 10 28 10 PM" src="https://user-images.githubusercontent.com/59364334/95657599-e3f50000-0b47-11eb-9744-74512f69125a.png">

**Comment by CWei88** [comment]
When you return Schedule using add, did you use the same list for the classes that you added. 

So for example, under your add function, you added the class using this.list.add(class), the list will be updated for both Schedule s0 and Schedule s, as the list is pointing to the same reference. Hence, updating the list in s will also update the list in s0.

You can look at #59 for reference

**Comment by sushmit98** [comment]
Actually, I didn't use the same list. I instantiated a new list and added it to that list. That's why I was a bit confused about why the original list was getting updated. This is a screenshot of what i did.

<img width="309" alt="Screenshot 2020-10-11 at 11 19 11 AM" src="https://user-images.githubusercontent.com/59364334/95669468-99a96880-0bb3-11eb-9e22-fd706ad8412c.png">

**Comment by chuashiqi** [comment]
i believe this is because newSched and this are pointing to the same list. Instead, you should create a new ArrayList and then add all the classes from classSched to newSched

**Comment by CWei88** [comment]
Yes when you assign this.classSched to newSched, you are basically referencing to the original classSched list. So when you add to newSched, it will look at the list it is assigned to, which is this.classSched and update this.classSched. Thus, this causes the original list in s0 to also update as it using the same this.classSched list.

Instead, you should initialise a new ArrayList and iterate through classSched and add it to newSched so that the newSched is different from classSched

**Comment by sushmit98** [comment]
Alright, thanks a lot guys! I was under the impression that since it's private final, it shouldn't be an issue as it'll point to a new list. But yeah it makes sense and it works now.
