### ISSUE TITLE
Lab 5 Main.java ifPresentOrElse

### ISSUE THREAD

**Issue by CWei88** [nus-cs2030/2021-s1#175]
# Description 
For Lab 5 Level 6 when I was crafting Main.java using ifPresentOrElse, it returned an error of incompatible types. I was wondering why this error had occurred as my method does return an Optional class and I don't really know why ifPresentOrElse does not work. Did I misinterpret how to use ifPresentOrElse or can someone enlighten me? I will attach my screenshots for both the error and my code below. Thanks!

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![Cap 3](https://user-images.githubusercontent.com/64974354/95658291-db9ec400-0b4b-11eb-97f2-2131cacb09e9.PNG)
![More code](https://user-images.githubusercontent.com/64974354/95658292-dd688780-0b4b-11eb-864b-f51e6f419335.PNG)

**Comment by lkldev** [comment]
Hi, `ifPresentOrElse` takes in the parameters `Consumer` and `Runnable`, which both are functional interfaces. However, you are passing an Optional object into ifPresentOrElse. You should instead pass lambdas (or a `Consumer` function and a `Runnable` function) to `ifPresentOrElse` method. The `Consumer` basically tells the method what to do if the value is present, and the `Runnable` tells it what to run instead if no value is found. An example will be:
```
Optional<String> s = Optional.of("ABCDE");
s.ifPresentOrElse(x -> System.out.println(x), () -> System.out.println("No value found"));
```
which will print `ABCDE` as the output. you can change `s` to `Optional.empty()` and it will print `No value found`. Hope this helps!

**Comment by yuanxintaxon** [comment]
"(Optional).ifPresentOrElse."  it check optional instead of exact value. 
I see that you are taking out the value from optional using flatmap.

**Comment by CWei88** [comment]
@lkldev @yuanxin1997 Ah I see. Thanks for the help. It works now!
