### ISSUE TITLE
PE Level 4

### ISSUE THREAD

**Issue by elizabethh07** [nus-cs2030/2021-s1#176]
hello! is anyone able to help me with this? i am not sure why all my output is not printed out. Thanks in advance! 

## Screenshots (if any): 
My output:
![image](https://user-images.githubusercontent.com/65172909/95659166-b614b900-0b51-11eb-9e4a-636ba9401393.png)

Correct output:
![image](https://user-images.githubusercontent.com/65172909/95659200-f6743700-0b51-11eb-9ae7-70c915513fb6.png)

**Comment by KaushikR1999** [comment]
There is either an issue with your clashWith method or your toString method. Are you concatenating all your lectures/tutorials properly in your toString method before you return it?

**Comment by elizabethh07** [comment]
@KaushikR1999 hello yes i did concatenate all of them before returning it. so i'm not too sure where the problem is. for clashWith, i passed all the test cases for Level 3, but i'm unsure if i covered all the possible events.

**Comment by KaushikR1999** [comment]
@elizabethlau hi yep theres more kinds of clashes in level 4 so maybe you should check if it covers all of that too? and maybe you could post a screenshot of your toString method here so that it's easier to find the bug? Thanks

**Comment by elizabethh07** [comment]
@KaushikR1999 
this is for Lecture.java
![image](https://user-images.githubusercontent.com/65172909/95659824-52d95580-0b56-11eb-80cd-ff529b54d1fd.png)

this is for Tutorial.java
![image](https://user-images.githubusercontent.com/65172909/95659848-85834e00-0b56-11eb-893a-1bf45d1edf89.png)

this is for Schedule.java
![image](https://user-images.githubusercontent.com/65172909/95659880-b1063880-0b56-11eb-82eb-64634701dbc9.png)

are these sufficient? thanks!

**Comment by KaushikR1999** [comment]
@elizabethlau Hi I think the issue is because you're returning at each iteration instead of simply concatenating in your Schedule's toString method. You should remove the 2 returns in your loop and only return at the end, after concatenating all the classes together first. 

Also add a "\n" when concatenating each class to your output string so that each class is printed on a new line. 

Hope this helps :)

**Comment by elizabethh07** [comment]
@KaushikR1999  yes it works! thank you very much :)
