### ISSUE TITLE
Can't get Java Scanner to stop scanning.

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2030/2021-s1#178]
# Description 
![image](https://user-images.githubusercontent.com/13763067/95665412-96e24f80-0b82-11eb-9181-99fd1979378f.png)

How do I get the scanner to stop scanning? I can never break out of this loop because sc.hasNextLine() is constantly returning true while waiting for user input. I pressed Ctrl+D but that doesn't trigger the scanner to end. Yet for some reason when I upload to CodeCrunch the grader is able to trigger the scanner to end and I can get an A.

The only possible workaround is to check if studentKey.equals("null") but it's really ugly code.

**Comment by SkullPirateTK** [comment]
Maybe sc.hasNext() might work?

**Comment by marcuspeh** [comment]
Nope i believe you can break out. You need to terminate the program in order to stop it from scanning

**Comment by yuanxintaxon** [comment]
sc.close().  is this what you are looking for?

**Comment by TypeDefinition** [comment]
@yuanxin1997 helped me figure out. Ctrl+D works when the program is compiled and running, but it does not work in jshell. So the solution is just to run in compiled mode and not jshell.
