### ISSUE TITLE
[PE] Sorting of Schedule

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#179]
Quick question:

I've my sorting done in the `toString()` method of my Schedule class. It doesn't matter if we sort in the add or toString method right?

**Comment by TypeDefinition** [comment]
It's very bad practice to have side effects in your toString method. toString should only return the string representation of the current state. Sorting in it is having a very unexpected side effect.

**Comment by domlimm** [comment]
> It's very bad practice to have side effects in your toString method. toString should only return the string representation of the current state. Sorting in it is having a very unexpected side effect.

Ah yes!! I forgot about side effects, thanks @TypeDefinition !!!
