### ISSUE TITLE
What else do I need to add to my vimrc file?

### ISSUE THREAD

**Issue by kaushikkrdy** [nus-cs2030/2021-s1#18]
I copied and pasted the .vimrc file provided but when I watch the videos on Luminus I realised some features on the vim in the videos is not present in my own vim (such as auto completing brackets or suggesting a list of possible code when I am typing code like java.util). What else do I need to add to my .vimrc file? Thanks.

**Comment by yonggqiii** [comment]
@kaushikkrdy The default .vimrc file is all you need. Autocompletion is something extra that I use personally, and I've shown a link to a video which describes how to get that feature somewhere in the earlier issues.
