### ISSUE TITLE
Lab 5 Questions

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#183]
Hey guys, I've got a question regarding HashMaps for level 2 of Lab 5. The instructions require the Module class to be able to put an Assessment Object into its HashMap. `new Module("CS2040").put(new Assessment("Lab1", "B"))`

I'm confused on how to get this to work. Java API states that the .put() requires 2 arguments, a key and a value. However the above only has 1 argument. How is this possible?

**Comment by CWei88** [comment]
The put function in Module is not the same as the put function in Java API. You will need to define a put function that takes in one argument and put it into a HashMap. The key in this case is the key of Assessment and the value is the Assessment itself.

**Comment by marcuspeh** [comment]
The put `new Module("CS2040").put(new Assessment("Lab1", "B"))` is a method in Module and its different from HashMap::put
