### ISSUE TITLE
Lab 5 Level 3

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#185]
# Description 
Hi, I was wondering when we override the **put** function in both Student and Module class, will we have to specify the parameter type v? 
eg. for Student class, should it be "KeyableMap(v) put(V item)" or "KeyableMap(Module) put(Module item)"? 
Thanks in advance!

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by lkldev** [comment]
Hi, Since the `Student` and `Module` classes are not generics, you will have to specify what is `V` as they will not know what type `V` is.

**Comment by jiehuixx** [comment]
Hi, however, I'm a little confused. 
For instance in this test case: new Student("Tony").put(new Module("CS2040").put(new Assessment("Lab1", "B"))),
new Student("Tony").put(new Module("CS2040") returns a Student object hence, how is it able to take in an assessment?

**Comment by lkldev** [comment]
Hi, I think you might have misread the test case. In this case, `new Student("Tony").put(new Module("CS2040").put(new Assessment("Lab1", "B")))`, the `Assessment` object is being passed into `Module` instead of `Student`. if I were to rewrite the statement, it will be 
```
Module m = new Module("CS2040").put(new Assessment("Lab1", "B"));
Student s = new Student("Tony").put(m);
```
