### ISSUE TITLE
Lab 5 Level 3

### ISSUE THREAD

**Issue by sushmit98** [nus-cs2030/2021-s1#186]
Hi guys! I'm having trouble implementing the KeyableMap class. When I try to compile it, I get an error that says <identifier> expected at the two constructors. I've tried searching on stackoverflow but I've not been able to find anything really helpful yet. Is my logic of implementation wrong? Here is my code: 

## Screenshots (if any): 
![Screenshot 2020-10-12 at 4 31 21 PM](https://user-images.githubusercontent.com/59364334/95723983-5ed52c80-0ca8-11eb-8782-df293faf54f8.png)

![Screenshot 2020-10-12 at 4 31 56 PM](https://user-images.githubusercontent.com/59364334/95724044-73192980-0ca8-11eb-8ea4-880a888a961b.png)

**Comment by wei2912** [comment]
Your constructors should be `public KeyableMap(...)` without the `<V>`.

**Comment by sushmit98** [comment]
Oh right! That's silly of me. Thanks!

**Comment by wei2912** [comment]
No worries, Java has a tendency to spit out cryptic errors for such typos 😂
