### ISSUE TITLE
Lab 05 - getGrade()

### ISSUE THREAD

**Issue by limyapkai** [nus-cs2030/2021-s1#188]
![image](https://user-images.githubusercontent.com/27536739/95822431-7a9b0a00-0d5e-11eb-93d0-92a5712bdc9d.png)

Hi Hi! Would like to ask why does getGrade() complains even though I haven't implement the Optional Function yet ? :0 Hmmm

**Comment by marcusleejw** [comment]
hi, can you show your module implementation? it seems like you are not extending your module class properly which leads to a cannot find symbol error since the method getGrade() is in the Assessment class

**Comment by waynetee** [comment]
Interesting error, what is the return type of your Module.get method?

**Comment by limyapkai** [comment]
![image](https://user-images.githubusercontent.com/27536739/95844437-7fba8200-0d7b-11eb-8967-5ca68a1d3944.png)
Hi @marcusleejw @waynetee  Here is my Module Class. Apparently, needed to do a @SuppressWarnings Sighh..

**Comment by waynetee** [comment]
You should use generics, your KeyableMap should be a generic class that holds any keyable type.
Your Module is a specific KeyableMap that holds a specific type

**Comment by marcuspeh** [comment]
> ![image](https://user-images.githubusercontent.com/27536739/95844437-7fba8200-0d7b-11eb-8967-5ca68a1d3944.png)
> Hi @marcusleejw @waynetee Here is my Module Class. Apparently, needed to do a @SuppressWarnings Sighh..

Idt can use @SuppressWarning. Codecrunch will fail it i think. Btw, dont need assign a to assignment then pass it to hashmap.

**Comment by limyapkai** [comment]
![image](https://user-images.githubusercontent.com/27536739/95847844-cf9b4800-0d7f-11eb-8fcb-28671fff1506.png)


Ahh I see okay, I amended my Module class. Hope this is the right way to use generics

**Comment by marcuspeh** [comment]
> ![image](https://user-images.githubusercontent.com/27536739/95847844-cf9b4800-0d7f-11eb-8fcb-28671fff1506.png)
> 
> Ahh I see okay, I amended my Module class. Hope this is the right way to use generics

Looks good but right you need convert from keyable<assignment> to module. So use `return (Module)super.put(a)`

**Comment by limyapkai** [comment]
Ah yes.. Silly me Thanks @marcuspeh

**Comment by jeffreytjs** [comment]
Is the Optional Function supposed to make getGrade() display error?
![image](https://user-images.githubusercontent.com/19368296/97784616-db3d9a00-1bda-11eb-8464-278d26a58878.png)

Can anyone give hints on how to resolve this error? Is it to modify the getGrade() function to look into the value of the Optional or is it that I am not extending my Module class properly?

I have included a screenshot of my Module class if it helps.
![image](https://user-images.githubusercontent.com/19368296/97784677-37082300-1bdb-11eb-84f4-29c36300a887.png)

**Comment by waynetee** [comment]
What is the return type of your Module.get method?

**Comment by jeffreytjs** [comment]
Is it of Optional type? Or do you mean if the value is of Assessment type?

Edit:
The return type is java.util.Optional

**Comment by waynetee** [comment]
Oh, the error is expected/"correct".

**Comment by jeffreytjs** [comment]
Oh okay I get what you mean now, that test case was not supposed to be tested in test4.jsh.
I tried to ensure backward compatibility by checking against test3. Haiz, got to spend a bit more time to understand these things.

Thank you for your help! @waynetee
