### ISSUE TITLE
Lab 5 Level 3 Trouble Understanding Generics/Wildcards

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#189]
My implementation for KeyableMap works just fine except for put(), the compiler claims there is no method getKey() for the generic object (V item).  

<img width="825" alt="Screenshot 2020-10-13 at 3 56 34 PM" src="https://user-images.githubusercontent.com/39799639/95832377-c2289280-0d6c-11eb-93d6-c7688058f620.png">

So now I have 2 questions.

1.	Why does Java not simply allow this? It doesn’t know what type of object (V item) is, since it is a generic. The input item may have the getKey() method, and if it doesn’t, that should be when it raises an error (during runtime)?

2.	What is the correct workaround for this? My guess is that it has something to do with wildcards/converting (V item) into an appropriate type, but I’m not sure.

 In fact, I'm still not entirely sure of how wildcards/generics conversions work. If anyone can provide me an explanation, I will be very grateful :)

**Comment by marcusleejw** [comment]
hi, did you declare V extends Keyable in your class header?

**Comment by CWei88** [comment]
When you initalise the KeyableMap class, you should define V to extend Keyable.
So the start would be
`class KeyableMap<V extends Keyable> {`

**Comment by domlimm** [comment]
Following what marcus and CWei have said, and in Level 3 it states,

> V must be a subtype of Keyable.

Thus, in Keyable you've the `getKey()` method and it'll be available for `item.getKey()` once you define V to extend Keyable in your KeyableMap class.

**Comment by EssWhyy** [comment]
Oh okay thanks! Will try it out later, didn't know you can extend a generic from an interface...

**Comment by domlimm** [comment]
Hey wait up!! Your `Keyable` interface should just be this,

![image](https://user-images.githubusercontent.com/46486515/95852780-ea24ef80-0d86-11eb-966b-2886c4daefa2.png)

And then following what @CWei88 said on how your `KeyableMap` should look like!
