### ISSUE TITLE
Lab 5 Level 3 Unchecked Call Warnings	

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#192]
<img width="849" alt="Screenshot 2020-10-13 at 10 16 38 PM" src="https://user-images.githubusercontent.com/39799639/95873664-b8ba1d00-0da2-11eb-9c41-dd686a20ca9b.png">

My Student class works functionality-wise, but I am still facing trouble with subclassing KeyableMap to the Student class, getting tons of unchecked call/conversion warnings relating to the 3 different types: Hashmap<String,V>, Hashmap<String,Module> and rawtype Hashmap.

 Pretty sure this is a wildcards issue, but I am so bad at wildcards and generics that I do not know where to start. 
 Why do these warnings keep happening and how do I fix it?

**Comment by limyapkai** [comment]
Hi Hi! I faced simillar issues at the start. Just have to make sure that when you create KeyableMap it has to be KeyableMap<V extends Keyable> V can come in the form of Module , Student etc. which themselves also extends to Keyable as required by the lab. Not sure if this helps :)

**Comment by EssWhyy** [comment]
<img width="676" alt="Screenshot 2020-10-13 at 10 40 05 PM" src="https://user-images.githubusercontent.com/39799639/95875903-1b141d00-0da5-11eb-9760-0953ffa0bad7.png">

Yep I already had KeyableMap<V extends Keyable> implements Keyable and my current Student class constructor is as such. But still don't know how to fix the typecasting warnings.

**Comment by zimmmz** [comment]
hellooo. I think what he mean is that in your KeyableMap class should be a KeyableMap &lt;V&gt; instead of just KeyableMap and the V can come in a form of Module/Student. Since in the  qns for lvl3 it mentioned that KeyableMap is going to be a generic class. So in a way for your student class will be a class Student extends KeyableMap &lt;Module&gt; implements Keyable?? nt sure if it helps..

**Comment by xingaporean** [comment]
KeyableMap<stuff>

**Comment by SeanEng** [comment]
> hellooo. I think what he mean is that in your KeyableMap class should be a KeyableMap <V> instead of just KeyableMap and the V can come in a form of Module/Student. Since in the qns for lvl3 it mentioned that KeyableMap is going to be a generic class. So in a way for your student class will be a class Student extends KeyableMap <Module> implements Keyable?? nt sure if it helps..

yup this, so for example your student class should extend KeyableMap<Module>. Also, make sure to check for that your return type for put should be KeyableMap<V> as well instead of KeyableMap

**Comment by marcuspeh** [comment]
> <img alt="Screenshot 2020-10-13 at 10 40 05 PM" width="676" src="https://user-images.githubusercontent.com/39799639/95875903-1b141d00-0da5-11eb-9760-0953ffa0bad7.png">
> 
> Yep I already had KeyableMap implements Keyable and my current Student class constructor is as such. But still don't know how to fix the typecasting warnings.


For your KeyableMap based on student, the parameter takes in a HashMap<String, module>. Is that the same as your HashMap in KeyableMap? Based on the error output, it seems like you did HashMap<String, V> and you assumed that V is Module. I’m not sure if you declare the V in the class KeyableMap(ie `class KeyableMap<V>`) but you to declare V before you can use V. Also, your declaration of Student did not pass in the V to KeyableMap (`class Student extends KeyableMap<Module> extends Keyable`)

**Comment by EssWhyy** [comment]
> > <img alt="Screenshot 2020-10-13 at 10 40 05 PM" width="676" src="https://user-images.githubusercontent.com/39799639/95875903-1b141d00-0da5-11eb-9760-0953ffa0bad7.png">
> > Yep I already had KeyableMap implements Keyable and my current Student class constructor is as such. But still don't know how to fix the typecasting warnings.
> 
> For your KeyableMap based on student, the parameter takes in a HashMap<String, module>. Is that the same as your HashMap in KeyableMap? Based on the error output, it seems like you did HashMap<String, V> and you assumed that V is Module. I’m not sure if you declare the V in the class KeyableMap(ie `class KeyableMap<V>`) but you to declare V before you can use V. Also, your declaration of Student did not pass in the V to KeyableMap (`class Student extends KeyableMap<Module> extends Keyable`)

Ok I see thanks it works. So basically, I had to override/fill in the generic variable V when subclassing from the generic class KeyableMap
