### ISSUE TITLE
Lab5 Level 5

### ISSUE THREAD

**Issue by dri12** [nus-cs2030/2021-s1#193]
# Description 
I was doing the getGrade() function in roster class and I used the get() function of Optional to get the initial value as shown in the image below. It compiled without any errors in my local machine. However, upon submitting to codecrunch, I encountered this compilation error. May I know why?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/71648569/95951133-6c192500-0e28-11eb-9efd-b644e5d78df7.png)

**Comment by lkldev** [comment]
Hi, according to CC, the profs have disallowed the use of `Optional::get`  and `Optional::isPresent` method.  Although this note is found in level 6, I believe it probably applies to level 5 as well. You might want to find a way around it through the use of `Optional::map` and `Optional::flatMap`. Hope this helps!

**Comment by marcuspeh** [comment]
The question stated not to use get() or isPresent() at the last part so codecrunch will fail if you use either

**Comment by dri12** [comment]
Thanks @marcuspeh  @lkldev for your help. Appreciate it.
