### ISSUE TITLE
Lab5 NoSuchRecordException Handling

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#194]
I tried creating a new exception called NoSuchRecordException which is thrown after orElseThrow() throws a NoSuchElementException. (exception wrapping). 

![image](https://user-images.githubusercontent.com/65516485/95958411-b2c04c80-0e33-11eb-8699-deae1e8738f9.png)

However, it doesn't seem to fit the output required in Part 5. What is required is to only print e.g. "No such record: Tony CS1231 Exam" without the exception itself. 

![image](https://user-images.githubusercontent.com/65516485/95957981-0aaa8380-0e33-11eb-97f1-c512f48e78a4.png)

How do I go about handling this.

**Comment by marcuspeh** [comment]
You could print out the error message when the try catch catches the error instead of throwing the exception.

**Comment by darrenhoon** [comment]
notice how one of the sample execution line in level 5 is:

`roster.get("Natasha").flatMap(x -> x.get("CS2040")).flatMap(x -> x.get("Lab1")).map(Assessment::getGrade)`

what if we changed **roster**, **"Natasha"**, **"CS2040"**, **"Lab1"** to their respective parameter variables / object references (eg **this**, **studentName**, etc...) and use this statement in the method?

then if you want the no such record message, just do a

return `something`.orElse(String.format("No such record: %s %s %s", id, mod, assessmentTitle));

it is a one-line answer (but it could be quite a long sentence so do edit if the checkstyle make noise)

**Comment by xingaporean** [comment]
the answer to this qn is staring at you in the lab hahah

**Comment by rezlite** [comment]
Instead of orElseThrow() try orElse(String.format("error message)

**Comment by marcusleejw** [comment]
you can try orElse(new NoSuchRecordException().getMessage())

**Comment by colintkn** [comment]
Yes haha. orElse is the answer.  Thank you.
