### ISSUE TITLE
Lab 5 Lvl 3 

### ISSUE THREAD

**Issue by seksek13** [nus-cs2030/2021-s1#197]
# Description 
After creating the generic class, I was able to put assessment in the module class but in the student class, there is an error stating "incompatible type". Can someone advise me on how to resolve this error?

## Screenshots 
<img width="619" alt="Screenshot 2020-10-14 at 7 23 48 PM" src="https://user-images.githubusercontent.com/69745285/95983385-1a868f80-0e54-11eb-8c32-19d501b30e71.png">

**Comment by yhtMinceraft1010X** [comment]
You might wanna check whether your class Module actually extends KeyableMap<Assessment> or if you used super in your constructor for Module.

**Comment by marcusleejw** [comment]
hi, if it helps you should check if your Student extends KeyableMap<Module>.

**Comment by seksek13** [comment]
> You might wanna check whether your class Module actually extends KeyableMap or if you used super in your constructor for Module.

I did extend to KeyableMap 

> hi, if it helps you should check if your Student extends KeyableMap.

Yes, my Student extends to KeyableMap<Module>

**Comment by Chen-Yiyang** [comment]
> You might wanna check whether your class Module actually extends KeyableMap or if you used super in your constructor for Module.

Could you please explain this, cuz I face the same problem. Do you mean that we should not use super in Module's constructor?

**Comment by marcuspeh** [comment]
Is your KeyableMap a generic function? Since you to have the type of the student/module/assessment for hashMap, you need to declare it as a generic function. I think thats why there this incompatible type thing

**Comment by waynetee** [comment]
What's the return type of module.put?
What's the parameter type in student.put?

**Comment by limeugene** [comment]
Since there can be a chain of put operations, each put operation should return a Module type for Module class (question also states that the put operation should be overriden by all sub classes), in order for subsequent put operations to work properly.

**Comment by SkyBlaise99** [comment]
Did you type cast KeyableMap<Assessment> into Module? IIRC, you need to do so as an output for module.put

**Comment by e0420658** [comment]
hi, i got the same error, you need to check that it extends KeyableMap with the type assessment/module/student stated within <>

**Comment by ghost** [comment]
Student extends KeyableMap< Module > implements Keyable

Module extends KeyableMap< Assessment > implements Keyable

**Comment by SkyBlaise99** [comment]
> Student extends KeyableMap< Module > implements Keyable
> 
> Module extends KeyableMap< Assessment > implements Keyable

the implements Keyable is redundant alr, you can just drop it
