### ISSUE TITLE
Generics (Easy)

### ISSUE THREAD

**Issue by aucjl** [nus-cs2030/2021-s1#198]
# Description 
Hello, I'm still a bit confused about generics. I'll use the questions from lab 4 as examples. 

1. Why do we have to use `Predicate<? **super** T> p` instead of `<? **extends** T>.` I am aware that super is a lower-bounded wildcard and how it can access all the parent classes above T and extends will be able to access anything that is a child class of T, all the textbook stuff but I still cant really connect the concepts.

2. Please explain the use of `<? super T, ? extends R>` instead of `<T,R>` or `<? extends T, ? super R>` for map.

3. For map function, why do we require the additional `<R>` in the method signature`public <R> ImmutableList<R> map(Function<? super T, ? extends R> f)` unlike for filter function? When do we use an additional `<R>`? I thought we would have declared that we are using R at `ImmutableList<R>` already so why an additional <R> before ImmutableList only for map function (vs filter function). 

Actually why does it make sense to return something possibly more specific than the input? 

Thank you so much!

## Topic: 
Generics, Wildcards, Functional Interfaces

## Screenshots (if any): 
Insert Images here if necessary

**Comment by waynetee** [comment]
Hi @aucjl ,

Here's some intuition for extends and super:

If you to test if a square is yellow, you would need an isYellow() predicate. Now, both isYellow(Square) and is Yellow(Shape) will work, hence we use ? super T for predicates.

For map, to create an immutableList<Circle>, we can use a function that returns either Circle or YellowCircle but not Shape. Hence we use ? extends R for the output of the function.

For your third question, R is a new variable specific to the method so you need to declare it. T in the filter function is the one already declared in your class.

Let me know if you have other questions.

**Comment by TypeDefinition** [comment]
Remember, the first Generic parameter is the INPUT of the function, and the second parameter is the OUTPUT of the function.

Image this use case:
![image](https://user-images.githubusercontent.com/13763067/96283679-25395400-100f-11eb-9f16-e2f8b50204e1.png)

Hopefully this clears things up for you. :)

**Comment by TypeDefinition** [comment]
@aucjl 
If your question was answered please close the issue thanks!

**Comment by aucjl** [comment]
> Hi @aucjl ,
> 
> Here's some intuition for extends and super:
> 
> If you to test if a square is yellow, you would need an isYellow() predicate. Now, both isYellow(Square) and is Yellow(Shape) will work, hence we use ? super T for predicates.
> 
> For map, to create an immutableList, we can use a function that returns either Circle or YellowCircle but not Shape. Hence we use ? extends R for the output of the function.
> 
> For your third question, R is a new variable specific to the method so you need to declare it. T in the filter function is the one already declared in your class.
> 
> Let me know if you have other questions.

Hello your explanation cleared a lot of things up for me! However I'm still a bit confused about q2, why can we return either Circle or YellowCircle but not Shape? I suppose T now here refers to Circle. If map takes in a `? super T` (e.g. Shape) how does it return a `? extends T` (e.g. yellow circle) something more specific than it was?

**Comment by waynetee** [comment]
Hi @aucjl, glad my explanation helped.

Take this example:

```
Optional<Shape> shapeBox = ...;
Optional<Circle> circleBox = shapeBox.map(CircularisingFunction);
```

Function signature for map:
`<R> Optional<R> map(Function<? super T, ? extends R> f)`

In this case, because you are assigning to circleBox, R automatically becomes Circle, and T would be Shape
So f is any function that can take in a Shape and output a Circle.
A function that takes in an Object and outputs a YellowCircle will work,
But one that takes in a square and outputs a shape won't.
This is reflected by <? super T, ? extends R>

As for how a circularising function might exist, that's a separate question that depends on the context, it may be just a function that creates a circle big enough to enclose the shape for example.

**Comment by aucjl** [comment]
@waynetee ohh thank you so much this is really clear!
