### ISSUE TITLE
Java Reflection

### ISSUE THREAD

**Issue by TarciusW** [nus-cs2030/2021-s1#200]
##Description 
Good day,

I was doing Lab 4 when I unintentionally stumbled into using Java Reflections in my code (caught be codecrunch compiler)
After changing a few things the error message disappeared.

The issue is that I have no idea what I did that was using java reflections, at least not intentionally, and from looking online it seemed that java reflections mainly utilise the java.util.reflect package.

My question is, in what situation will I find myself utilizing this concept of java reflection outside of the package? 

## Topic: 
Java reflections

## Screenshots (if any): 
Insert Images here if necessary

**Comment by SkullPirateTK** [comment]
If you are getting the runtime class of an object in your program then you are most likely using reflection.

**Comment by adamozh** [comment]
Codecrunch may check your variable or method names, so maybe one of your methods are something along the lines of  "getClass" or "getName" codecrunch may reject it.

Generally, I don't think this mod should require any reflection

**Comment by rajobasu** [comment]
Reflections is pretty useful but kindof breaks oop in some sense (?!) It helps you get the states of objects, procure its method and its variables (even if private) at runtime. It provides wrappers for functions, variables etc which we can use at runtime without necessarily knowing the names of those classes.

**Comment by TarciusW** [comment]
thank you for your help!

**Comment by TarciusW** [comment]
Thank you for all your responses! i will be closing this thread.
