### ISSUE TITLE
Lab6 level 2

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#203]
Hi, we are supposed to make Logger an interface which is implemented by LoggerImpl. Im a bit confused on how LoggerImpl should be constructed as the instances should be instances of Logger? 

This is my constructor so far:
![image](https://user-images.githubusercontent.com/71011712/96255691-ecd34f00-0fe9-11eb-9691-89d327f1742b.png)

**Comment by FergusMok** [comment]
Hello, I think you're on the right track, just missing the log variable for level 1 to work.
As LoggerImpl implements the Logger interface, it can have the compile time type of Logger and run time type of LoggerImpl, and still have the LoggerImpl functionalities, as long as the Logger interface has the LoggerImpl functions (by default abstract) .

Relatively more layman terms : 
i.e Logger<String> myLogger = Logger.make("Hello") is ok, and myLogger can still run LoggerImpl functions, myLogger.printlog(), ASSUMING Logger.make() returns a LoggerImpl ( doesn't matter that it returns of type Logger ).

**Comment by charoi** [comment]
I think the way I visualised it was like Lists, which are also monads.
List<Integer> list = new ArrayList<>();
In our lab Logger would be similar to List, an interface, while LoggerImpl is like ArrayList. Most of your methods should hence be in LoggerImpl<T> but they should appear abstract in Logger<T>

**Comment by e0420658** [comment]
i see.. thanks guys!
