### ISSUE TITLE
Lab 6 equals

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#208]
Hi, I was wondering how do I go about creating this method? My current implementation is as follows which obv can't work in level 3.

<img width="269" alt="cs2030lab6 #2" src="https://user-images.githubusercontent.com/71959340/96333301-9aeb0180-109b-11eb-982e-3676b72f4a35.png">

I was wondering how do you check if the logs are the same? Given that we are constantly making a new object every time Logger.make is called. Please help thankss.

**Comment by SkyBlaise99** [comment]
Checking the log depends on how you implement your log. For me, the log is in `String` so i just call `this.log.equals(logger.log)`

**Comment by jiehuixx** [comment]
Em sorry but does that mean your Logger.make function does not create a new object?

**Comment by SkyBlaise99** [comment]
Erm mine call `new LoggerImpl(thing, log)`

**Comment by jiehuixx** [comment]
Ah okay, I know what i'm missing alr thanks!

**Comment by limyapkai** [comment]
Hi! Just want to ask, so for this equals method, we need to check the log in order to determine if the new LoggerImpl that is created are "equals" is it? :) I was only focussing on the values and the typecast and I forgot about the List of Strings that could be potentially useful for the check

**Comment by marcuspeh** [comment]
> Hi! Just want to ask, so for this equals method, we need to check the log in order to determine if the new LoggerImpl that is created are "equals" is it? :) I was only focussing on the values and the typecast and I forgot about the List of Strings that could be potentially useful for the check

Yup you need check the log

**Comment by limyapkai** [comment]
@marcuspeh Ahh yes okay cool thanks bro :)
