### ISSUE TITLE
Lab 6 level 5 misconception

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#209]
![image](https://user-images.githubusercontent.com/51086295/96334071-907f3680-10a0-11eb-9592-bc5f338567e0.png)

Why is Value changed! New value = 15 here ? 

f(10) -> f(5) ->f(16) .... 

Can pass the rest of the test case except for this
Thanks

**Comment by SkyBlaise99** [comment]
5 * 3 -> 15
15 + 1 -> 16
this is the 3n+1 case

**Comment by chongweil907** [comment]
@SkyBlaise99 ahh icic thanks

**Comment by jiehuixx** [comment]
Hi, may I enquire how should I go about to resolve this issue?

**Comment by marcuspeh** [comment]
> Hi, may I enquire how should I go about to resolve this issue?

Basically multiple it by 3 then add 1
