### ISSUE TITLE
Submission of Lab 6's test5.jsh file 

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#212]
Hello, currently I've ran the test5.jsh in my own vim, and the outputs are correct and there's no errors whatsoever.
However, submission to CodeCrunch gives me this error. I've also included my own code's method signature. There are 2 additional "helper" methods (mult and bMult) that f calls. Does anyone know of a solution?

![image](https://user-images.githubusercontent.com/10182564/96358520-a04b5900-113a-11eb-9885-021ff119aa65.png)
![test5](https://user-images.githubusercontent.com/10182564/96358564-2f587100-113b-11eb-96f8-84ac0772224d.png)

**Comment by chongweil907** [comment]
erm is it because u uploaded it as test5.jsh. U shld upload it as level5.jsh

**Comment by FergusMok** [comment]
Damn yes, my bad I saw wrongly. Thanks alot
