### ISSUE TITLE
How to exit fedora on windows

### ISSUE THREAD

**Issue by Paulynlhx** [nus-cs2030/2021-s1#213]
Hi, does anyone know how to exit fedora on windows? There's once I spammed esc and it exited and another one where I clicked Ctrl+Alt+delete or the power button and it worked. I'm not sure what's the proper way and it takes me some time to finally exit fedora. Thank you in advance!!

**Comment by marcuspeh** [comment]
Type `poweroff` to power off or `reboot` to boot back into windows

**Comment by Paulynlhx** [comment]
i see, thank you !!
