### ISSUE TITLE
Recitation 8 file not found error

### ISSUE THREAD

**Issue by benluiwj** [nus-cs2030/2021-s1#216]
Hi everyone, I am a Mac user who is unable to use the jpp command on any of the java files after following the instructions in the appendix. Does anyone have a solution? I thought it was a bash version issue so I updated it but still the same issue. 

 

![Screenshot 2020-10-21 at 7 24 51 PM](https://user-images.githubusercontent.com/67570985/96720760-bfb5e080-13dd-11eb-9a68-6eeff94a34ae.png)

**Comment by rajobasu** [comment]
Can you show the full code for the class maybe? In particular, which is the file that is not found?

**Comment by benluiwj** [comment]
hi @rajobasu, the file not found is processed/LazyList.java when I try to jpp LazyList.java. There isn't really a 'full code' per say because I was just following the instructions from the recitation's appendix

**Comment by xSaints19x** [comment]
Based on what I know, jpp changes the parts of the code and then saves the changed file into the processed folder. So my best guess on what's missing is "export CLASSPATH=~/recit8/processed:$CLASSPATH"  , which is to save the changed file into the processed folder. Maybe you can try and see if it works?
