### ISSUE TITLE
Lab 6 Level 4 printlog() Logger vs LoggerImpl

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#219]
<img width="836" alt="Screenshot 2020-10-23 at 12 55 48 PM" src="https://user-images.githubusercontent.com/39799639/96958517-45e23c00-1530-11eb-84ee-38d28da8b544.png">

This part of the test code fixes the output type from flatmap as a Logger, so when I try a.printlog(), I get an error saying there is no method printlog() found for a, since my printlog() method is under LoggerImpl.

But I can't write the printlog() method to the Logger interface directly as I can't access the Loggerimpl list from there, so what should I do?

**Comment by marcuspeh** [comment]
You can make the abstract method of printlog() in the interface

**Comment by kohkenneth** [comment]
i think you can try declaring printlog() as an abstract method in the interface

**Comment by EssWhyy** [comment]
Oh yeah I forgot that I could declare an abstract interface method, then create the relevant logic in the subclass/implementing LoggerImpl class. Thanks
