### ISSUE TITLE
Dealing with null supplier

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#222]
Hi all, I am stuck on how to throw an exception if supplier given is null. 
Specifically this testcase:

jshell> Supplier<Integer> si = null
jshell> try { Lazy.of(si); } catch(Exception e) { System.out.println(e); }

Thanks

**Comment by juayhee** [comment]
You should wrap the supplier in an Optional, specifically with Optional.ofNullable(si).

So, if si is null, Optional.ofNullable(si) = an empty Optional, as per the API. 
Then, .orElseThrow() will throw the desired NoSuchElementException on an empty Optional.

**Comment by chongweil907** [comment]
@Craftarc ahh that works. Thanks so much for the help !
