### ISSUE TITLE
Unable to pass test case in codecrunch

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#224]
Hi all, I have managed to pass all the testcases provided.

However, when I upload my code into codecrunch, I got this particular error:

![image](https://user-images.githubusercontent.com/51086295/97036464-75c62980-159a-11eb-99af-3d6d215724d7.png)

For my implementation, this.value is an Optional and shld have a get method associated with it.
![image](https://user-images.githubusercontent.com/51086295/97036599-a1491400-159a-11eb-9eac-a3be3a9dfbce.png)
 
Does anyone have an idea what is wrong? Thanks in advance !

**Comment by aaron-ljx** [comment]
If your this.value is an Optional, then it is because Optional.get() is banned in Codecrunch.

**Comment by chongweil907** [comment]
@aaron-ljx right thanks.
