### ISSUE TITLE
Lab 7 level 6 memoization

### ISSUE THREAD

**Issue by charoi** [nus-cs2030/2021-s1#227]
# Description 
Error in memoizing
## Topic: 
Hi there, does anyone know how the memorization works for this lab? I mean if we call the 3rd index how isit supposed to know index 5 was called?

## Screenshots (if any): 
![error](https://user-images.githubusercontent.com/41200981/97111725-74703a80-171b-11eb-9244-163b1f8be367.png)

**Comment by ghost** [comment]
You can compare the index with the current size of the list :)

**Comment by marcuspeh** [comment]
Maybe you can store the data in a list. So if your list has 6 elements (ie after u get index 5), when u call index 3, it can just get from the list
