### ISSUE TITLE
Lab 1 maxDiscCoverage

### ISSUE THREAD

**Issue by enqiilim** [nus-cs2030/2021-s1#23]
# Description 
I managed to pass the testcases given but not on the codecrunch. What's wrong?

## Topic: 
public int findMaxDiscCoverage(Point[] points){
	int maxDiscCoverage = 0;

	for(int i = 0; i < points.length - 1; i++){
		for (int j = i + 1; j <  points.length; j++){
			int counter = 0;
			if(distb(points[i],points[j]) <= 2){
				Circle c = createUnitCircle(points[i],points[j]);
				for (Point p: points){
					if (contains(c,p)){
						counter++;
					}
				}
			}
		if (counter > maxDiscCoverage);
		maxDiscCoverage = counter;
		}
	}		
	return maxDiscCoverage;
}

public double distb(Point p, Point q){
	double dx = p.x - q.x;
	double dy = p.y - q.y;
	return Math.sqrt(dx * dx + dy * dy);
}

public boolean contains(Circle circle, Point p){
	return distb(circle.centre, p) <= circle.radius;
}
## Screenshots (if any): 
Insert Images here if necessary

**Comment by SkyBlaise99** [comment]
There's a error in your code. `if (counter > maxDiscCoverage);`
