### ISSUE TITLE
Lab 6 Level 2 Wrong Error Thrown

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#230]
<img width="1031" alt="Screenshot 2020-10-26 at 4 07 48 PM" src="https://user-images.githubusercontent.com/39799639/97148886-cf9b3f00-17a6-11eb-9225-8d021ab578b3.png">

My function outputs are correct when I tested for all 5 levels, but for the chaining of make() in level 2, instead of an ‘illegal static interface method call’ error thrown, I get a ‘cannot find symbol’ error.

Why is that? I put a non-abstract public static make() as part of the Logger interface and have LoggerImpl implement it, just like the question said.

**Comment by lkldev** [comment]
Hi, what do you mean by putting a non-abstract public static `make()` for `LoggerImpl` to implement it? Static methods cannot be overridden and the `make()` method should be implemented in the `Logger` interface itself. Maybe you would like to share how you implemented the `make()` method in `LoggerImpl`.

**Comment by juayhee** [comment]
I'm having the same problem. I implemented the static make() method in in Logger, but its return value is a LoggerImpl. This is so chaining method calls such as Logger.make(5).map() are called on a LoggerImpl, rather than a Logger (which has none of the methods map, printlog etc.) 

However, I noticed that the error EssWhyy is trying to elicit only comes about if the return value is a Logger instead. The correct error arises when the static make method is called on a Logger object. The error he currently outputs is probably, like me, due to his return type being LoggerImpl. LoggerImpl does not have a make method, hence "symbol not found".

I'm personally conflicted as to how a Logger can take in method calls like .printlog() in later tests, as as far as I am aware, Logger only has the static method and none of the other methods.

An example of the test I am confused about:
`jshell> Logger<Integer> a = Logger.make(5)`
`jshell> a.printlog()` <- a is a Logger, so how is it accepting the printlog() method?

**Comment by EssWhyy** [comment]
> Hi, what do you mean by putting a non-abstract public static `make()` for `LoggerImpl` to implement it? Static methods cannot be overridden and the `make()` method should be implemented in the `Logger` interface itself. Maybe you would like to share how you implemented the `make()` method in `LoggerImpl`.
<img width="878" alt="Screenshot 2020-10-26 at 5 02 51 PM" src="https://user-images.githubusercontent.com/39799639/97153260-27d53f80-17ad-11eb-9922-02c475d7f18e.png">

I wrote the make() function with the relevant logic in Logger and had LoggerImpl implement Logger.

**Comment by aaron-ljx** [comment]
> 
> 
> > Hi, what do you mean by putting a non-abstract public static `make()` for `LoggerImpl` to implement it? Static methods cannot be overridden and the `make()` method should be implemented in the `Logger` interface itself. Maybe you would like to share how you implemented the `make()` method in `LoggerImpl`.
> 
> <img alt="Screenshot 2020-10-26 at 5 02 51 PM" width="878" src="https://user-images.githubusercontent.com/39799639/97153260-27d53f80-17ad-11eb-9922-02c475d7f18e.png">
> 
> I wrote the make() function with the relevant logic in Logger and had LoggerImpl implement Logger.

Change to public static <U<U>> Logger<U<U>> make and see if it works? That was what worked for me.

**Comment by lkldev** [comment]
> I'm personally conflicted as to how a Logger can take in method calls like .printlog() in later tests, as as far as I am aware, Logger only has the static method and none of the other methods.
> 
> An example of the test I am confused about:
> `jshell> Logger<Integer> a = Logger.make(5)`
> `jshell> a.printlog()` <- a is a Logger, so how is it accepting the printlog() method?

Hi @Craftarc, inorder for Logger to know these methods, we have to abstract these methods in Logger and have LoggerImpl to override these methods.

**Comment by lkldev** [comment]
> > Hi, what do you mean by putting a non-abstract public static `make()` for `LoggerImpl` to implement it? Static methods cannot be overridden and the `make()` method should be implemented in the `Logger` interface itself. Maybe you would like to share how you implemented the `make()` method in `LoggerImpl`.
> 
> <img alt="Screenshot 2020-10-26 at 5 02 51 PM" width="878" src="https://user-images.githubusercontent.com/39799639/97153260-27d53f80-17ad-11eb-9922-02c475d7f18e.png">
> 
> I wrote the make() function with the relevant logic in Logger and had LoggerImpl implement Logger.

Ah I misunderstood what you intially meant. Yeap, as what @aaron-ljx mentioned, changing the return type to `Logger` works for me.

**Comment by EssWhyy** [comment]
@aaron-ljx Oh nice, it works, thanks! Though, I had to change most of my other method return types to Logger instead of LoggerImpl to fit with the interface. Wonder why does changing the return type make such a big difference? 

Honestly, separating the code logic into Logger and LoggerImpl makes it so much more complicated especially when it's just to serve the one functionality of preventing make() chains...

**Comment by toahi** [comment]
> d none of the other methods.
> 
> An example of the test I am confuse

I am very confused by this as well. How come the return type is logger but the object that is returned is an instance of LoggerImpl
