### ISSUE TITLE
Lab 7 level 4/5 unchecked warning in equals

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#231]
Hi i hope someone can enlighten me here.
For the equals method of level 4, I type casted obj as Lazy<T> and it worked normally before level 5. However, when I made T extends Comparable<T> for level 5, i started to get a warning that I'm using an unchecked cast. I tried a few ways already but nothing seems to remove it. Below is my code for equals and the warning.

![Untitled](https://user-images.githubusercontent.com/70895902/97172450-020a6380-17ca-11eb-8031-18ee5dbe3684.png)
![image](https://user-images.githubusercontent.com/70895902/97172555-21a18c00-17ca-11eb-8cea-1926319fb80f.png)

**Comment by marcuspeh** [comment]
Prof covered this before iirc. Try `Lazy<?>  newobj = (Lazy)obj;`

**Comment by kohwenjie** [comment]
Oops. it works now thx alot @marcuspeh
