### ISSUE TITLE
lab 7 level 6

### ISSUE THREAD

**Issue by limyingying2000** [nus-cs2030/2021-s1#234]
Hi, 

I am getting a mismatched number of' op called' to pass some of my test cases for level 6. Can someone explain to me the train of thought for the test case output again, because I may not have understood it correctly and I am attempting to find the bug in my codes? 

For instance,

jshell> list.get(12)
op called
op called. 

Please explain along the line of how did Unary Operator get called only twice?  and the following as well. 

jshell> list.indexOf(10)
op called
op called
op called
op called
op called
$.. ==> 10

Thank you!!

**Comment by ArizonaTay** [comment]
The list contains 10 elements. Thus, it needs to compute 2 additional elements.  (list.indexOf(10) was previously ran )

The list contains 5 elements. Thus, it needs to compute 5 additional elements before it can retrieve the position of the object. (list.get(5) was previously ran)

**Comment by colintkn** [comment]
Can I get some input with moving forward with level 6? I'm stuck at thinking how to move 
forward with the recursion since we can't use null. What can the base case be? 

```
static <T extends Comparable<T>> LazyList<T> generate(int n, T seed, UnaryOperator<T> f) {
        if (n <= 0) {
           return new LazyList<T>(null, ()-> null); 
        }
        Lazy<T> head = Lazy.of(seed);
        Supplier<LazyList<T>> tail = () -> LazyList.generate(n-1, f.apply(seed), f);
        return new LazyList<T>(head, tail);
    }
```

**Comment by waynetee** [comment]
@colintkn nice approach, I think this method is more elegant but more challenging

Think about it, do you really need a base case?

**Comment by charoi** [comment]
@colintkn actually the code for generate in LazyList is very similar to the generate method in EagerList

**Comment by bryanwee023** [comment]
@colintkn Seems like your approach is similar to the infinite LazyList implementation covered during the lecture, which I don't think is the method intended for this lab. I think the lab wants you to have LazyList store a List of Lazy objects (thus, as charoi mentioned, your code for generate will be very similar to EagerList). 

But your implementation seems fine, no need to include base case because there's nothing wrong with an infinite list (the test cases don't require us to terminate the list). But saying that, an infinite implementation is inherently lazy, making Lazy itself redundant lol.

**Comment by xingaporean** [comment]
> Can I get some input with moving forward with level 6? I'm stuck at thinking how to move
> forward with the recursion since we can't use null. What can the base case be?
> 
> ```
> static <T extends Comparable<T>> LazyList<T> generate(int n, T seed, UnaryOperator<T> f) {
>         if (n <= 0) {
>            return new LazyList<T>(null, ()-> null); 
>         }
>         Lazy<T> head = Lazy.of(seed);
>         Supplier<LazyList<T>> tail = () -> LazyList.generate(n-1, f.apply(seed), f);
>         return new LazyList<T>(head, tail);
>     }
> ```

can use null?

**Comment by TarciusW** [comment]
> Please explain along the line of how did Unary Operator get called only twice? and the following as well.

The value from op is lazy! and the values are stored. so previously op was called until the value 10, but after that the value for 12 is being queried so op gets called two more times! it only gets called:
1. as many times as required to get the value
2. the value has not yet been stored

hope this helps! :+1:  :smile:

**Comment by limyingying2000** [comment]
thank you for all of your help! I managed to debug it!!! 👍
