### ISSUE TITLE
Lab 7 Level 4 Dependency on java.util.Objects

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#236]
<img width="433" alt="Screenshot 2020-10-29 at 3 59 16 PM" src="https://user-images.githubusercontent.com/39799639/97541417-15067900-1a00-11eb-9935-fe388c9f143d.png">

Why does this error show up on Codecrunch? Is it because I used ‘instanceof’ in my equals() method? I used it in the previous labs and didn’t get such an error.

**Comment by domlimm** [comment]
May I ask how you used the `instanceof`? I use `instanceof` too in all my equals method!

**Comment by CWei88** [comment]
I don't think it is because of the `instanceof` method in equals since mine worked fine. Was there any other portion of your code where you had used an Object and typecasted it back to `Lazy<T>` or `LazyList<T>` ?

**Comment by marcuspeh** [comment]
Did you use Objects.requireNonNull()? Prof just said we arent allowed to use Objects class so that includes requireNonNull()

**Comment by EssWhyy** [comment]
Yeah I just realised that I did use Objects.requireNonNull(), and Codecrunch detected it. But my previous submissions included it and didn't have the error pop up. It's likely the prof added in the check a few hours ago.

**Comment by marcuspeh** [comment]
> Yeah I just realised that I did use Objects.requireNonNull(), and Codecrunch detected it. But my previous submissions included it and didn't have the error pop up. It's likely the prof added in the check a few hours ago.

Yup probs that. My codes got that too
