### ISSUE TITLE
Lab 7 lvl 2

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#238]
Hi i read from some post that this error on code crunch is because of the early usage of the Supplier .get() function. 
Can someone help me out here. I am not actually sure how I can actually rectify this without using .get() early and applying the function on the return value of the .get(). I can get past the test2.jsh file with the current code, and i store the cached value in an Arraylist in the Lazy object.

![image](https://user-images.githubusercontent.com/70895902/97585222-dbe7fc00-1a33-11eb-8ac2-d10ef50fdbbd.png)

![image](https://user-images.githubusercontent.com/70895902/97584568-2026cc80-1a33-11eb-9f5c-b3eaa54a4c89.png)

**Comment by charoi** [comment]
Hi there! 
I had the same testcase error after the regrading. To pass this you have to push this Lazy return value into a supplier and construct a **new** Lazy instance ie `new Lazy( () -> ...) `

The ... should be of type U btw.

Hope this helps!

**Comment by srj31** [comment]
func.apply(this.get()) is not "Lazy", as the get will eagerly find the current value of this. You need to use a supplier to make it Lazy

**Comment by kohwenjie** [comment]
@srj31 @charoi ahh i see, at first i tried to make it lazy but there was even more errors showing so i thought it was the wrong approach. it works right now. Thanks a lot!
