### ISSUE TITLE
Lecture 2 Static Binding & Typecasting

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#24]
# Description 
Hi guys, I am a question regarding the typecasting in the code for explaining Static Binding.

## Topic: 
Static Binding, Typecasting 

## Screenshots 
Prof explained that we had to typecast obj by doing (Point) obj so that obj can be recognised as Point class type. 
![image](https://user-images.githubusercontent.com/70444061/91640876-4f30ba00-ea53-11ea-8327-8aa576a855fb.png)

In the code for explaining Static Binding, both the Circle and FilledCircle had to be typecasted as Circle.
I don't understand because:
1) The first element in the array is already of a Circle object so why must it be typecasted?
2) Why are we typecasting the second element as (FilledCircle)?
![image](https://user-images.githubusercontent.com/70444061/91640898-7be4d180-ea53-11ea-832f-58df6d89c98d.png)

I hope I'm making sense! Would appreciate any help :)

**Comment by chongweil907** [comment]
I don't think it needs to be typecasted. Polymorphism will print the toString() method of FilledCircle as it will override it's parent Circle class. I think the above example is to showcase how to achieve the same behaviour if you did not consider polymorphism(late binding). Do correct me if I am wrong.

**Comment by hhhhanz** [comment]
Yes, I get that this is to show the alternative to dynamic binding! 

So in this case, what is the (Filled Circle) circle for?

**Comment by chongweil907** [comment]
Ohh I got what u meant. I think the typecast in this case is redundant.

**Comment by domlimm** [comment]
Im thinking it's because Filled Circle extends Circle which means inheritance between the 2 classes exist and you can say that Filled Circle **is a** Circle. Therefore, @chongweil907 has said that typecast in the static binding is redundant.

**Comment by hhhhanz** [comment]
Ah I see! Okay, thank you so much :)
