### ISSUE TITLE
Project Level 2

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#245]
# Description 
Hi guys, we are expected to take in a new Function property into Event class and now all subclasses should not contain any argument in the constructors except for ArriveEvent which should take in the customer? I was wondering if this implementation is the way to go as execute will return a new shop and the nxt event. How are yall able to get the server that was 'assigned' to the customer at the arrive stage? for instance, to implement the function in Wait.java, we will have to retrieve the server that was assigned to it at the ArriveEvent and then mutate it to serve so that it transitions from Wait -> Serve?

Would be great if someone could help thanks!

**Comment by bryanwee023** [comment]
Hmm where was it explicitly stated that the constructors of subclasses have no arguments? Aren't these the only 2 constraints?
![Screenshot 2020-10-31 at 10 48 28 PM](https://user-images.githubusercontent.com/72504548/97782220-43847f80-1bcb-11eb-9c06-bd02d4541be3.png)

**Comment by e0420658** [comment]
erm im taking the dummyevent code as an example

**Comment by lkldev** [comment]
Hi, there is no limitation to the number of arguments `Event` class and subclasses of `Event` class can have. The `DummyEvent` class is an example of how we should call our `Event` class with a `Function` as one of the argument. 
![image](https://user-images.githubusercontent.com/49238386/97784942-1f319e80-1bdd-11eb-9beb-fb0e0c6d4cac.png)
If you refer to the last line in the image above, it says that they assume `Event` class has a constructor that only takes in a `Function` as an argument. Hope this helps :)

**Comment by e0420658** [comment]
ahh okay i get it thnx!
