### ISSUE TITLE
Project 2 Level 2

### ISSUE THREAD

**Issue by guccilerino** [nus-cs2030/2021-s1#246]
Hi profs, can I clarify on the statement below which was given in Level 2 of Project 2.

"Invoking execute with a Shop will result in a Pair comprising a Shop (which is empty), and another DummyEvent. As you can see, other than Event itself, all specific types of events — arrive, serve, wait, done and leave, can now be fully specified with their relevant properties, and the addition of only one toString() method. Note that this constraint shall be enforced during grading. You still have the liberty of constructing your Event class in any way you wish."

Previously for project 1, I used Event class as an abstract class with abstract method execute(), overwriting it in each sub class of Event . Does this mean that I need to recode everything such that my subclasses only has the toString() method?

**Comment by Terence-Sim** [comment]
You may still retain your existing Event subclasses. But now, we will invoke the new `execute(s)` method, ignoring your previous ones. 

This means your existing subclasses must now call the parent constructor with the appropriate Function property, like what is shown in `DummyEvent`.  You will also need to override the `toString()` method, to return the type of the event, eg, Arrive, Wait, etc.

**Comment by guccilerino** [comment]
Ok thank you
