### ISSUE TITLE
Lab 5 Level 6 Output Error

### ISSUE THREAD

**Issue by kaushikkrdy** [nus-cs2030/2021-s1#247]
Hi could someone help me figure out what's the issue here? I get the correct output (except for the first one saying BD, but I think that's because I'm pressing CTRL-D to exit the scanner) when I try it out on the terminal but CodeCrunch says it's producing the wrong output. Anyone else had this same issue?

<img width="560" alt="Screenshot 2020-10-31 at 8 22 58 PM" src="https://user-images.githubusercontent.com/70100131/97779130-25ad1f80-1bb7-11eb-9588-1295e339e54a.png">

<img width="350" alt="Screenshot 2020-10-31 at 8 23 13 PM" src="https://user-images.githubusercontent.com/70100131/97779135-2e9df100-1bb7-11eb-8ae8-6b0f6b29d6de.png">

**Comment by hhhhanz** [comment]
I'm not sure if I'm on the right track here but doesn't seem like you should need to use Ctrl+D to exit the scanner. The scanner should stop running if you provide the correct conditions? something like a sc.hasNext()?

**Comment by kaushikkrdy** [comment]
Hi @hhhhanz thanks for the help! Realised I could have used hasNext() and didn't account for the variable whitespace between inputs, it works now
