### ISSUE TITLE
Java Codestyle

### ISSUE THREAD

**Issue by wongzw** [nus-cs2030/2021-s1#25]
# Summary
Hi! I understand that we will eventually have to follow Java code style and pass the code style checker for our project. Can I get some clarification on which and where to find more information regarding Java code style?

I have found the following pages and not sure if they are accurate

1. Google Java Code Style: https://google.github.io/styleguide/javaguide.html
2. Oracle Java Code Style: https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

Thank you!

**Comment by lkldev** [comment]
Hi, I am unsure which code style CS2030/S follows, but they have their own code style checker. you can find more information about them [here](https://github.com/nus-cs2030/2021-s1/wiki/Setting-Up-Checkstyle). You can run them against your code and they will inform you which part of the code does not adhere to their code style.

**Comment by pchunky** [comment]
There is a CS2030 Java Style guide defined here: https://www.comp.nus.edu.sg/~cs2030/style/
You can probably take a look.

**Comment by darrenhoon** [comment]
will we be taught officially via lectures/labs to follow the code style or it is something we have to pick up ourselves? because if it is the former, it will really be trial and error, using only the checkstyle files provided as feedback for our code

**Comment by lkldev** [comment]
@darrenhoon I doubt it will be taught officially via lectures or labs, probably you can read through the style guide  @purfectliterature has mentioned and try to practice it while doing your labs.

**Comment by limyingying2000** [comment]
<img width="979" alt="Screenshot 2020-09-06 at 14 12 55" src="https://user-images.githubusercontent.com/65782648/92319473-290aab80-f04b-11ea-8dc9-94c8e795536d.png">
Hi, I can't seem to call 'checkstyle *.java' after downloading the files from the link. May I ask which step did I miss? 
Thank you. #

**Comment by lkldev** [comment]
hi @limyingying2000, you can't call checkstyle as you have not set the alias for that command. to run checkstyle you should run the following command: 
`java -jar ~/javalab/checkstyle-8.2-all.jar -c ~/javalab/cs2030_checks.xml *.java`

if you wish to set alias, you can refer to #37 .

**Comment by wongzw** [comment]
For alias you need to set-it up every time you launch ubuntu. If you want to set it permanently you need to follow this link for more details: https://www.cyberciti.biz/faq/create-permanent-bash-alias-linux-unix/
