### ISSUE TITLE
Lab 6 Level 1

### ISSUE THREAD

**Issue by jeffreytjs** [nus-cs2030/2021-s1#250]
# Description 
Hints needed to start on lab 6.
I don't really understand what it means by "Start by writing a static method make to wrap a value within a Logger" which would then produce an output like "Logger[5]". 

Are there any notes in the lecture slides other than lecture 4 last slide where it mentioned wrapper once? I think I am suppose to write an interface for Logger but is there a proper way to return "Logger[5]" or am I suppose to return it as a String that I construct myself?

## Topic: 
Lecture 4 Generics and Variance of Types(?)

## Screenshots (if any): 
Screenshot from Lab for reference:
![image](https://user-images.githubusercontent.com/19368296/97796344-bb928a00-1c4b-11eb-8d3b-608e15260a73.png)

**Comment by rcdl2222** [comment]
Hi, I think it means using a static method `make` to create the Logger object. For example, I don't call the constructor explicitly, but use a static method `make` to create an instance of Logger.

It's similar to "making" a Sandbox<T> if you want to refer to the slides.

The output Logger[5] will be from the toString() method. Hope this helps!

**Comment by hhhhanz** [comment]
static method means you don't have to create a Logger object in order to use the make() method. So you don't have to do Logger newLogger = new Logger and do newLogger.make(). 

When you call make, it returns a Logger object which has the value 5 and you use toString() to output it as Logger[5]

**Comment by jeffreytjs** [comment]
Oh I see, so the output is meant to be constructed like `"Logger[" + value + "]"`? 

Thank you @rcdl2222, I'll be sure to check out Sandbox again cos it's kind of hazy as to how to start since it looked like it "Logger[5]" could be some standard output format. 

I don't quite get how the static work, I'll leave this here first while I search in the other issues.

![image](https://user-images.githubusercontent.com/19368296/97796683-22b23d80-1c50-11eb-9cbf-81bf4593918c.png)

Edit:
Hi @hhhhanz, thanks for the explanation on static. I get how it works it now but I can't seem to be able to implement it for now.

**Comment by hhhhanz** [comment]
Your input doesn't need to be static - the usual private final T input should work & I think your make is supposed to return a Logger for Level 1 right!

**Comment by Clem-cpu** [comment]
The static is referring to the method not the value. You can't reference a static value with a static method so i think that's why the error is occurring. Setting your T input to be private final would still work as you are not updating the value inside Logger<T>. 

Instead, you are actually creating a new Logger every time you call the other functions such as map. 

Hint for later parts:
Try to figure out how you are able to store the previous values of Logger by making an overloaded constructor.

**Comment by xingaporean** [comment]
use static keyword

**Comment by jeffreytjs** [comment]
Thanks in advance for the help and hints!

But okay, maybe I still don't quite understand how to implement static. I'm sorry if I'm not suppose to be doing this but I really can't get this lab going. The more I try the more I feel like I don't understand generics anymore.

My code
![image](https://user-images.githubusercontent.com/19368296/97801255-3cff1200-1c76-11eb-968e-0d14b70ce717.png)

Error message
![image](https://user-images.githubusercontent.com/19368296/97801260-4b4d2e00-1c76-11eb-9c46-9d30913271ed.png)

**Comment by rcdl2222** [comment]
You will need to declare the generic type `<T>` in your static method, forgot the reason for it but it works

**Comment by leeleonard98** [comment]
Whenever its a static method, the return type has to be `<T>Logger<T>,` you can try this and see if it works

**Comment by Clem-cpu** [comment]
You have to declare the generic type before static as the static method creates a logger based on the input to the static Make() method. 

If using T again is too confusing you could declare <U> in-front of your static method and the return type would be Logger<U> with input U input

**Comment by jeffreytjs** [comment]
Yes, `<T>Logger<T>` works and I've managed to solve it with all your help. Thank you @leeleonard98, @rcdl2222 and @Clem-cpu I think you two were trying to describe the same thing as well.

Thank you all for your time @rcdl2222, @hhhhanz and @xing221 too.
