### ISSUE TITLE
Project 2 Level 2 - Implementing lambda functions for subclasses of Event

### ISSUE THREAD

**Issue by rcdl2222** [nus-cs2030/2021-s1#251]
This issue is regarding implementing lambda functions for subclasses of Event. Currently I'm working on ArriveEvent, which requires me to check through the servers in Shop to determine what kind of event is being output. 

But as the Function that is defined in the lambda expression is referred to in a static context, I am unable to use the non-static variable `customer` to create the instances of required Events that comes after ArriveEvent. 

As the DummyEvent shown in the example does not take in the `customer` variable, it does not have this problem.

Is there any way to create a non-static lambda expression/Function per say? 

## Topic: 
Project 2

## Screenshots (if any): 
Insert Images here if necessary

**Comment by guccilerino** [comment]
try
x -> {}
then define a method like how you normally would within the curly braces.
For eg. 
x -> {
    if (condition) {
        return new Pair<Shop,Event>(Shop, new Event);
    }
}

**Comment by rcdl2222** [comment]
> try
> x -> {}
> then define a method like how you normally would within the curly braces.
> For eg.
> x -> {
> if (condition) {
> return new Pair<Shop,Event>(Shop, new Event);
> }
> }

I did this and it doesn't work because ServeEvent requires an input variable `customer` which is non-static. Do I have to redefine my constructors in this case? Thanks for the reply!

**Comment by lkldev** [comment]
Hi, not sure if I understood your question correctly, but assuming your current constructor is something like `ServeEvent(Customer c)` you will still be able to call your constructor normally. In the lambda of your `ArriveEvent`, you can do smth like 
```
x -> {
return new Pair<Shop,Event> (x, new ServeEvent(customer));
}
```
Since you did not make any modification to the `customer` object. Hope this helps! :)

**Comment by Clem-cpu** [comment]
Not too sure if this is what you are referring to but, doing so will still allow you to access the Customer in your ArriveEvent.
ArriveEvent(Customer c) {
super(x -> return Pair.of(x, new ServeEvent(c))
this.c = c;
}

**Comment by rcdl2222** [comment]
Ok I finally got it to work, thanks @lkldev @Clem-cpu @guccilerino !
