### ISSUE TITLE
Can we use for loop for Project 2 from Level 3 onwards?

### ISSUE THREAD

**Issue by CWei88** [nus-cs2030/2021-s1#255]
As stated in the title, I just wanted to clarify if the limitations of no loops only applies to level 1 and 2 in the Pair, Shop and Event classes, or does it also to the Main class in Level 3 onwards? Thanks.

**Comment by raynerljm** [comment]
If I remember correctly Prof Henry mentioned that now we learnt streams we should use them instead of for loops. So I think the intention is that the entire Project 2 has no for loops.

**Comment by raynerljm** [comment]
Okay I asked my TA, seems like its okay to use while loops for polling events from our PQ.
