### ISSUE TITLE
Lab 6 Level 4

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#259]
Hi guys, am encountering the following error in my Level 4:
![image](https://user-images.githubusercontent.com/70444061/97841682-501aec00-1d21-11eb-8eb1-e8fc5131810e.png)
I tested using jshell that this works:
![image](https://user-images.githubusercontent.com/70444061/97841894-a9831b00-1d21-11eb-9473-4d6923a38252.png)

Anyone have any idea? :( 
My method returns a new LoggerImpl<U>(...,...) and my method return signature is Logger<? extends U>

**Comment by waynetee** [comment]
Hi, `Logger<? extends Integer>` is not a `Logger<Integer>` and hence cannot be assigned to it

**Comment by hhhhanz** [comment]
Hi @waynetee thanks for your help! I got it now :)
