### ISSUE TITLE
Unable to highlight in WSL Ubuntu 18.04

### ISSUE THREAD

**Issue by darrenhoon** [nus-cs2030/2021-s1#26]
# Unable to highlight in WSL Ubuntu 18.04
Hi guys, I am using the WSL Ubuntu 18.04 but I am unable to use my mouse to highlight texts. Same goes for copying and pasting into the unix terminal. Would really appreciate any advice for this issue faced

## Description 
I downloaded Ubuntu 18.04 from microsoft app store and I have even uninstalled and reinstalled the WSL but it still does not support highlighting of text

The weird thing is that I did the exact steps on my friend's Windows computer and in that computer, the highlighting is available by default after the WSL Ubuntu 18.04 is downloaded from the microsoft app store...

**Comment by domlimm** [comment]
Hi Darren,

For copying and pasting, just right click at the top of your terminal window and select `Properties` then under `Options` tab Check the 'Use Ctrl Shift C/V Copy & Paste.

![image](https://user-images.githubusercontent.com/46486515/91654803-91530d80-eade-11ea-9a73-a3d17145178a.png)

For the mouse settings, [please check this out!](https://unix.stackexchange.com/questions/139578/copy-paste-for-vim-is-not-working-when-mouse-set-mouse-a-is-on)

Hope this helps!

**Comment by darrenhoon** [comment]
Hi Dominic, thanks for the response.

I guess for others with the same issues, the following are the steps I made to improve the situation:

1. Enable Ctrl + Shift + C/V as shown above in Dominic's reply. what this does is that it allows you to paste things you copied from Windows over to the WSL Ubuntu 18.04 terminal. 

2. In the wsl terminal, do` vim ~/.vimrc`

3. in the .vimrc file, go into insert mode, create a new line at the end and add `set mouse=a`, then :wq the file


![Screenshot_10](https://user-images.githubusercontent.com/34526101/91675772-25b98080-eb70-11ea-9acc-44f2a5f833a0.jpg)


I guess for ppl with the same problem, the highlighting using mouse still does not work for the WSL Ubuntu 18.04 terminal, but at least it is working for vim
also, unless you edit more settings in the .vimrc file, the way to copy and paste lines in vim is still to yank in visual mode, not Ctrl + Shift +V

**Comment by waynetee** [comment]
Hi Darren, just to check, is your QuickEdit mode checkbox ticked under `properties` and `default`?

**Comment by darrenhoon** [comment]
Hi Wayne, it was not and after I enabled it, the highlighting works. thanks a bunch!
