### ISSUE TITLE
Project #2 Level 2 Test Cases

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#261]
In the Level 2 of Project #2, the question specifies that "As there could be varying ways in how your specific events are constructed, there will be no test cases. That said, you should still test out this new implementation of event generation on the inputs of the final level of Project #1 and check if the behaviour is the same.". My code passes the given test cases on ArriveEvent.

What test cases from Project #1 can we use here to test other events like Serve, Leave etc.?
Please provide some advice. Thank you!

**Comment by benluiwj** [comment]
I think they are referring to the main method output from project 1. Such that your output should still be the same as the last level of project 1 after making the appropriate changes

**Comment by weiyifei-evelyn** [comment]
@benluiwj  Thank you for your reply! Do you mean that we need to re-write a main class for the modified events, to check whether we get the same results as the the last level of Project #1?

**Comment by lkldev** [comment]
Hi, I think the question meant that if you use back the same test cases in the final level of project 1, i.e. the number of servers and the arrival times of each customer, your output should still correspond with the output given in the final level of project 1. Thus, you can create a main that takes in the input similar to that of project 1 and create a shop that takes in two servers. After that, you add in a new customer as to how you would in the final level of project 1 and start the simulation. The output should tally with the output from the final level of project 1. Essentially, changing the program to utilise `Shop` and `Event.execute(s)` should not modify how it would originally behave.

**Comment by weiyifei-evelyn** [comment]
@lkldev Thank you! Understand!
