### ISSUE TITLE
How to check whether a supplier is null without using null?

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#263]
How to check whether a supplier is null without using "null"?
For example, we have a method like:
`public String foo(Supplier s) {
    if (s == null) {
        throw new Exception("No value in the supplier");
    }
   return "okay";
`
However, I do not want to use s == null here. Is there any other way of checking null?
Thank you!

**Comment by e0420658** [comment]
hi, u can try wrapping the supplier in an optional and call Optional.ofNullable(s).orElseThrow(Supplier<? extends X> exceptionSupplier), can check it out in the API

**Comment by kohkenneth** [comment]
I think you can use Optional.empty

**Comment by weiyifei-evelyn** [comment]
Thank you for your suggestion @e0420658 @kohkenneth 
I get it right!
