### ISSUE TITLE
Project 2 illegal start of expression package cs2030.simulator;

### ISSUE THREAD

**Issue by sharleneq** [nus-cs2030/2021-s1#264]
Everything works when i compile the codes and run them as they produce the relevant outputs. However, there is an error message when i run jshell -q Server.java Shop.java as seen in the screenshot attached below. I was just wondering if any of y'all have this error message and is it okay to ignore it? Or are there any methods to resolve this error?

<img width="297" alt="Screenshot 2020-11-03 at 4 26 21 PM" src="https://user-images.githubusercontent.com/65596820/97963030-4fea2180-1df1-11eb-80f3-98a10acb927e.png">

**Comment by e0420658** [comment]
yep i have this error when opening files from all classes in the package, should be fine to ignore as output is correct. i think jshell does not compile the package at run-time, not sure why though.

**Comment by lkldev** [comment]
jshell interprets the file not as a whole, but line by line. Since `package` is not a valid statement in jshell, it throws the error, but continues to read the file as it is. This way, the classes in your files are still created, just the `package` statement is ignored. You can ignore these errors.

**Comment by sharleneq** [comment]
@e0420658 @lkldev okay, thank you!
