### ISSUE TITLE
Project 2 Level 4: Dealing with multiple input lengths from Scanner

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#266]
# Description 
Hi, for project level 4, it requires us to take in 1 additional input from the command line. But I'm not too sure how to identify the number of inputs and parse them correctly because the order of the inputs are different? I tried doing 
```
List<Double> inputs = new ArrayList<>();
while (scanner.hasNextDouble()) {
    inputs.add(sc.nextDouble();
}
```
but the scanner does not seem to know when to stop scanning. Does anybody know how to solve this issue?

## Topic: 
Scanner

**Comment by Clem-cpu** [comment]
Since the order of inputs is already predefined for you, maybe you can just manually key in the inputs so like

int seed = sc.nextInt();
int numOfServers = sc.nextInt()
int qMax = sc.nextInt()
int numberOfCustomer = sc.nextInt()
double arrivalRate = sc.nextDouble()
double serviceRate = sc.nextDouble()

**Comment by chuashiqi** [comment]
@Clem-cpu but the order of inputs differ between lvl 3 and lvl 4. so qMax in lvl 4 will end up being numOfCustomer in lvl3, which is wrong.

**Comment by SkullPirateTK** [comment]
Use String[] args in Main.java, all the arguments given when invoking `java Main` will be in the array.

**Comment by dtse2401** [comment]
Store all inputs in corresponding arrays of their types, and use a counter to determine which level the test is being done for. For example, if total elements within the arrays = X, then level 3, then assign accordingly as per level 3, and so on and so forth.

**Comment by lkldev** [comment]
yeap, as @SkullPirateTK mentioned, the `args` variable in `Main` will contain all the arguments, which you then can use it to determine the number of inputs provided. Do note that `Scanner` would not work here as it is not user input, but a command argument (i.e. the arguments are supplied right after `java Main` command). Hope this helps :)

**Comment by marcuspeh** [comment]
You can actually predefine the scanner but i believe the question passed the inputs in the same line as `java Main` so everything will be stored in `String[] args` in the declaration of your main. To parse those inputs, look at `Double.parseDouble()` and `Integer.parseInteger()`

**Comment by chuashiqi** [comment]
got it! thanks for the help guys!
