### ISSUE TITLE
Project 2 Lvl 4

### ISSUE THREAD

**Issue by Clem-cpu** [nus-cs2030/2021-s1#267]
Can anyone give a hint on how we are supposed to store the qMax for servers. I was thinking of storing a list of Customers in the Server Class but was wondering if this violates the pure function as the List<Customer> in the Server class changes on Event.execute(). 

Is it possible to keep track of the queue in Main.java itself

**Comment by marcuspeh** [comment]
What i did was replacing the hasQueue with a queueCount and storing the value of Qmax in server. Then my execute and stuff will work with the queueCount instead changing the hasQueue to false/true. For example, a customer can queue if queueCount < Qmax

**Comment by bwangpj** [comment]
> What i did was replacing the hasQueue with a queueCount and storing the value of Qmax in server. Then my execute and stuff will work with the queueCount instead changing the hasQueue to false/true. For example, a customer can queue if queueCount < Qmax

How would you know when to schedule the serve event for a customer after it starts waiting?

**Comment by marcuspeh** [comment]
> > What i did was replacing the hasQueue with a queueCount and storing the value of Qmax in server. Then my execute and stuff will work with the queueCount instead changing the hasQueue to false/true. For example, a customer can queue if queueCount < Qmax
> 
> How would you know when to schedule the serve event for a customer after it starts waiting?

So my priority queue sorts according to time then event then customerID. So if both customer are waiting for a server, i will execute the first one and then the time for the server will change. To prevent the second one from being executed at the same time, i checked the time too

**Comment by charoi** [comment]
Hi @marcuspeh do u mean that u used execute within ur compare method? Does that not violate side-effects lol I'm just wondering... cos I'm worried bout the impact on future levels

**Comment by marcuspeh** [comment]
> Hi @marcuspeh do u mean that u used execute within ur compare method? Does that not violate side-effects lol I'm just wondering... cos I'm worried bout the impact on future levels

Nope. My event and server stores the time and a new event/shop will be returned everytime i call execute in the `while(!pq.isEmpty())`. So my comparator just got the time from them

**Comment by SkyBlaise99** [comment]
For me, I did almost the same as @marcuspeh. When 2 `ServeEvent` clash, the lower `Customer ID` gets served, which will update the `Shop`. The 2nd `ServeEvent` will execute but it will fail the if condition inside it, returning a new `ServeEvent` with a later time.

**Comment by chuashiqi** [comment]
hi @SkyBlaise99 when you say "The 2nd ServeEvent will execute but it will fail the if condition inside it, returning a new ServeEvent with a later time.", do you mean that the 2nd ServeEvent will fail the if condition in the EventComparator? and if so, where is the new ServeEvent returned? in the EventComparator?

**Comment by SkyBlaise99** [comment]
I have a if condition inside `ServeEvent.execute()` to check for clash of 2 `ServeEvent`

**Comment by chuashiqi** [comment]
@SkyBlaise99 ah i see, thanks!

**Comment by Clem-cpu** [comment]
@SkyBlaise99 sry can i clarify how did u check for a clash of 2 serve events inside ServeEvent.execute(). Does this mean u stored a List<ServeEvent> inside the ServeEvent class?

**Comment by SkyBlaise99** [comment]
U just check if server is available

**Comment by Clem-cpu** [comment]
ok finally managed to get it thanks all for helping!

**Comment by chuashiqi** [comment]
@SkyBlaise99 @Clem-cpu
hi, sorry to comment after this issue has been closed but since the 2nd serveEvent is executed, how do you stop the event from being printed? bc right now i print the event directly after i poll from pq and the 2nd ServeEvent is also being printed, which we don't want because the customer is not yet served. 
and also, how would you increase the totalWaitingTime? because we would have to keep track of the totalWaitingTime in order to find the average waiting time in Main? would appreciate any help. thanks!

**Comment by SkyBlaise99** [comment]
U print the event inside execute and not after poll lol. And isn't total waiting time dependent on the done event? Nothing to do with serve event lol

**Comment by chuashiqi** [comment]
@SkyBlaise99 i thought total waiting time was time that the customer waits to be served? if its dependent on done event then wouldn't the service time be included as well?

**Comment by SkyBlaise99** [comment]
I mean, I check if the current event is a serve event and e.execute is a done event. Hope that helps

**Comment by chuashiqi** [comment]
@SkyBlaise99 i see. sorry one last probably stupid question, when you say that you print event inside execute, do you mean that you print the nextEvent? ie inside the code for ServeEvent execute you print DoneEvent? wouldn't the timings be out of order then? because i don't see how you can print the current event inside execute when this can't be called in the constructor. I also tried printing in Event's execute but the 2nd ServeEvent is also being printed.

**Comment by SkyBlaise99** [comment]
I print the current event when it is being executed. I dun see why u can't do that cuz I did it this way and it works.

**Comment by chuashiqi** [comment]
@SkyBlaise99 this is the error i see. 
![image](https://user-images.githubusercontent.com/70755428/98631196-e077b300-2357-11eb-9b82-a87a41e694a5.png)

**Comment by SkyBlaise99** [comment]
Ah I printed out the things, not using methods
