### ISSUE TITLE
Lab 4 Level 5 ( ArrayStoreException Check )

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#268]
I was able to do all the levels for Lab 4 except for this part. 
My toArray method's signature looks like this: `<U> U[] toArray(U[] listArg)`

I still don't know how to check if the type of U is different from type T.

**Comment by domlimm** [comment]
Hi, there is not an actual need to explicitly check it but rather use a `try { ... } catch (ArrayStoreException ase) { ... }` block

**Comment by roopaniedu** [comment]
@domsterthebot Thanks so much!

**Comment by domlimm** [comment]
You're most welcome! If I'm not mistaken, the exceptions will handle the checks for you!
