### ISSUE TITLE
Lab6 static method make

### ISSUE THREAD

**Issue by itmeruoxin** [nus-cs2030/2021-s1#272]
hello! i realise while writing the make method for Logger interface, that if my return type for make is LoggerImpl<T>, i will get this error when running the testcases: 
![Screenshot 2020-11-05 at 00 07 33](https://user-images.githubusercontent.com/73954596/98135570-eeae7500-1efa-11eb-8a27-a5adfef57394.png)
it runs correctly when i change the return type to Logger<T> instead though, anyone knows why this is so? As a class that implements Logger, why is LoggerImpl unable to see the make method? Thanks in advance!

**Comment by domlimm** [comment]
Hi, since the `make` method resides in the interface `Logger` and it's declared as `static`, you can only access the method explicitly through doing `Logger.make(...)`. 

`LoggerImpl` does not extend `Logger` (there is no connection between the class and the interface), hence, `LoggerImpl` is unable to access `make`. 

Hope it helps clarify!

**Comment by cliveong** [comment]
So if am I understanding this correctly, the static method is not inherited?

**Comment by kohkenneth** [comment]
Hi @beantoad i'm not sure if i understand your issue correctly because in my make method (Logger interface), my return type was LoggerImpl and i managed to run the test cases. But Im not sure if we can do Logger.make(5).make(7) because this would be static interface method call which im not sure is allowed.

**Comment by domlimm** [comment]
> So if am I understanding this correctly, the static method is not inherited?

Yes, you can say that!

When a class implements an interface, there is a necessity to implement the methods in the interface.

```java
public interface Test {
    public static void make(...) { ... }
    
    // Implement these methods in classes that implements Test
    public void other(...);
    public void another(...);
}
```

**Comment by kohkenneth** [comment]
Also, not sure if this is relevant but I think the lab itself stated that we had to code our 'make' method in such a way that it would not be misused and these 2 calls were given in the example. Hope it might help!

- Logger.make(Logger.make(5))

- Logger.make(5).make(7)

**Comment by ghost** [comment]
Even though you are returning a new LoggerImpl using make(), the actual return type of make() is Logger. Creds to my TA and hope this helps :)

**Comment by itmeruoxin** [comment]
> > So if am I understanding this correctly, the static method is not inherited?
> 
> Yes, you can say that!
> 
> When a class implements an interface, there is a necessity to implement the methods in the interface.
> 
> ```java
> public interface Test {
>     public static void make(...) { ... }
>     
>     // Implement these methods in classes that implements Test
>     public void other(...);
>     public void another(...);
> }
> ```

Does it mean that an implementing class of an interface is only able to see and call methods that it implements? so in this case because make is entirely defined in Logger and does not appear in LoggerImpl at all so "cannot find symbol" error is shown? Also may i clarify what you mean by LoggerImpl does not extend Logger as there is no connection, i thought a LoggerImpl still a Logger, so it still "extends" Logger? Thank you!

**Comment by itmeruoxin** [comment]
@kohkenneth @scottsusanto ah yes i managed to get "illegal static interface method call" when i changed my return type to Logger instead, thanks!

**Comment by Terence-Sim** [comment]
@beantoad : We separated Logger and LoggerImpl precisely to prevent Logger.make(5).make(7).

:-)

**Comment by domlimm** [comment]
Hi @beantoad , you may find this useful: [Implements vs extends: When to use? What's the difference?](https://stackoverflow.com/questions/10839131/implements-vs-extends-when-to-use-whats-the-difference)

**Comment by itmeruoxin** [comment]
okay thanks all for the explanations!

**Comment by jeffreytjs** [comment]
> @kohkenneth @scottsusanto ah yes i managed to get "illegal static interface method call" when i changed my return type to Logger instead, thanks!

How does this work? I am running into errors trying to get the return type to be Logger within Logger interface
![image](https://user-images.githubusercontent.com/19368296/99058599-66a22c80-25d8-11eb-8fc2-6b3d9dd88744.png)

**Comment by kohkenneth** [comment]
Hi @jeffreytjs I think you can try setting your return type to LoggerImpl instead of Logger!

**Comment by kohkenneth** [comment]
@jeffreytjs can refer to the comment by @domsterthebot i think his explanation is quite clear!

**Comment by jeffreytjs** [comment]
Hi @kohkenneth,

I started with this
![image](https://user-images.githubusercontent.com/19368296/99059133-18d9f400-25d9-11eb-924c-1c71e64be798.png)


But the error is as op has faced

Edit:
And I have been through the other issue and the solution seem to be the same. Changing the return type to Logger but I can't figure that part out

Edit 2:
Okay I got it. Thanks @kohkenneth
