### ISSUE TITLE
Lab 7 Level 6 indexOf(): extra "op called"

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#275]
The get() method in Level 6 is correct (I've tried it with many test cases, the number of "op called" printed is correct for get() method); however, the indexOf() has some problems that I can't tell.

Below is my code for indexOf() and the output. I cache all the values in a list. However, when I call indexOf(T v), I can get the correct result but the number of "op called" is wrong. For example shown in the second screenshot, list.indexOf(10) gives me the correct value of 10 but wrong number of "op called" from this, I think I save the cache values correctly in the cacheList). It should be 5 times instead of 10 times.

Can anyone help me check what is wrong with my indexOf() method?

<img width="497" alt="Screenshot 2020-11-05 at 10 48 53 AM" src="https://user-images.githubusercontent.com/71199647/98191622-90ae7b80-1f54-11eb-8bb7-20fc86d14e70.png">
<img width="377" alt="Screenshot 2020-11-05 at 10 49 10 AM" src="https://user-images.githubusercontent.com/71199647/98191623-91471200-1f54-11eb-8058-8113a007dbf3.png">

Thank you very much!

**Comment by kohkenneth** [comment]
i think maybe you might be able to get some insights from  #269 !

**Comment by lkldev** [comment]
Hi, recall that `List::indexOf` will make use of the `equals` method in the object. Since the list contains a list of Lazy object, is there a way to compare the Lazy objects in the list with `T v`? Hope this helps!

**Comment by weiyifei-evelyn** [comment]
> Hi, recall that `List::indexOf` will make use of the `equals` method in the object. Since the list contains a list of Lazy object, is there a way to compare the Lazy objects in the list with `T v`? Hope this helps!

Hi @lkldev thank you for your reply. In my case, I didn't construct a list of Lazy objects. I use Stream.iterate() to control the number of times where operation is applied to seeds. So do you mean that the wrong number of "op called" is due to the wrong  .equals()  method used?

**Comment by lkldev** [comment]
Hmmm may I ask whats in the `cacheList`?

**Comment by weiyifei-evelyn** [comment]
@lkldev All the computed values. Let say, I first call list.get(2), then 0,1,2 will be computed and saved in the cacheList. If now I call list.get(1), I will just take the value from cacheList instead of computing it again.
The similar idea applies to indexOf(). For example, I first call list.index(3), then 0,1,2,3 will be computed (the stopping condition is that the last value computed using the operation equals to the input v) and saved in the cacheList. Now if I call list.index(2), it will give me 2 directly from the cacheList. If I call list.index(5), it will compute 4,5 and add it to the existing cacheList. Then I get the index of v from cacheList.

**Comment by lkldev** [comment]
Oooo then what does your `generate` method do? 

Edit: based on your description of the cacheList, it seems like the `equals` method is the trigger point for the extra "ops called" since the `equals` method will call this.f.apply(v) to compare the values, which resulted in "ops called" being printed.

**Comment by weiyifei-evelyn** [comment]
> Oooo then what does your `generate` method do?
> 
> Edit: based on your description of the cacheList, it seems like the `equals` method is the trigger point for the extra "ops called" since the `equals` method will call this.f.apply(v) to compare the values, which resulted in "ops called" being printed.

My `generate` method only takes in the value of seed and add the seed to the cacheList.

**Comment by lkldev** [comment]
Hmmmm okay, you might want to try using the `limit` method, but I am not sure if that works in your case, or in your `generate` method you try to generate a List of Lazy objects instead. IMO generating a List of Lazy objects will be more straight forward here.

**Comment by weiyifei-evelyn** [comment]
> Hmmmm okay, you might want to try using the `limit` method, but I am not sure if that works in your case, or in your `generate` method you try to generate a List of Lazy objects instead. IMO generating a List of Lazy objects will be more straight forward here.

Okay than you! I'll try to create a List of Lazy Objects in `generate` instead. Thank you!!

**Comment by kohkenneth** [comment]
yeah i also created my List of Lazy Objects in my generate method as well. But actually i think your method should work too im just not sure why there's an extra op called printed.

**Comment by jiexilim** [comment]
my method is similar as yours, for the predicate part in Stream.iterate, u can try x -> x.compareTo(v) < 0, it works for me

**Comment by weiyifei-evelyn** [comment]
@jiexilim Thank you for your help!!! I changed the predicate. However, this time I got 6 "op called" rather than 5.

<img width="440" alt="Screenshot 2020-11-05 at 2 53 04 PM" src="https://user-images.githubusercontent.com/71199647/98207821-37a40f00-1f77-11eb-8ab2-0f0ed99e5b64.png">
<img width="466" alt="Screenshot 2020-11-05 at 2 53 09 PM" src="https://user-images.githubusercontent.com/71199647/98207826-3a066900-1f77-11eb-94ae-550ba0607a18.png">

I can't tell what is the problem here. Since the last element from the cacheList is 5 (after calling list.get(5)), then I iterate from 5, which will give me 5, f(5), f(f(5)), f(f(f(5))), f(f(f(f(5)))), f(f(f(f(f(5))))) i.e. 5, 6(with op called),  7(with op called),  8(with op called), 9(with op called),  10(with op called). So by right there should be 5 times "op called" but I get 6 here. I'm very confused about the reason.
Is there something wrong with my code?

**Comment by weiyifei-evelyn** [comment]
To add on, the values saved in the cacheList is shown by list.getit(), which is [0,1,2,3,4,5,6,7,8,9,10]. No additional values are saved.

**Comment by jiexilim** [comment]
try putting x.compareTo(v) < 0, instead of <= 0

**Comment by weiyifei-evelyn** [comment]
@jiexilim When I changed it to x.compareTo(v) < 0, I get the CORRECT number of "op called" but the result is -1 not 10. May I ask how do you solve this problem?

<img width="472" alt="Screenshot 2020-11-05 at 3 02 33 PM" src="https://user-images.githubusercontent.com/71199647/98208364-20b1ec80-1f78-11eb-95fc-4dedeec7ac8a.png">
<img width="474" alt="Screenshot 2020-11-05 at 3 02 43 PM" src="https://user-images.githubusercontent.com/71199647/98208372-227bb000-1f78-11eb-9cb1-54e14a677913.png">

Thank you so much!!

**Comment by lkldev** [comment]
> I can't tell what is the problem here. Since the last element from the cacheList is 5 (after calling list.get(5)), then I iterate from 5, which will give me 5, f(5), f(f(5)), f(f(f(5))), f(f(f(f(5)))), f(f(f(f(f(5))))) i.e. 5, 6(with op called), 7(with op called), 8(with op called), 9(with op called), 10(with op called). So by right there should be 5 times "op called" but I get 6 here. I'm very confused about the reason.
> Is there something wrong with my code?

the issue here would be that the stream will have to generate the next value in order to do the `x.compareTo(v)`, which resulted in the extra "op called". As to how to solve it I'm not sure, maybe @jiexilim could share more

**Comment by jiexilim** [comment]
yup i think @lkldev is right, I am not sure about ur code, but i added the seed in cachelist at the start (in generate) and for the index.of(), like urs, i took the last element from the cachelist, and while stram.iterating it, I map it with the function and add the computed value to the cachelist

**Comment by jiexilim** [comment]
I have tried ur code, when .get(10) is called, ur code will apply f and get 11, then only test 11 with the predicate, that's y when u put <=0, u get 10 in ur list but got extra one "op called", what i did was I add the computed value into the cachelist while .iterate the stream, so altho my 10 doesn't pass the predicate (< 0) but it is already being added into the cachelist
![image](https://user-images.githubusercontent.com/70773974/98211789-8ce31f00-1f7d-11eb-86e1-3bca4183ff30.png)

**Comment by weiyifei-evelyn** [comment]
@jiexilim Okay understand!! Really appreciate your help! I'll try it out.

**Comment by weiyifei-evelyn** [comment]
@jiexilim Hi, according to what you shared, you add the computed value into the cache list while .iterate. May I know how you did that. According to Java API `iterate​(T seed, Predicate<? super T> hasNext, UnaryOperator<T> next)`, .iterate can only take in UnaryOperator, so I cannot add the value in the cacheList when carrying out the operation on the seed values like below
`Stream.iterate(this.f.apply(this.cacheList.get(cSize-1)),
                            x -> x.compareTo(v) < 0,
                            x -> this.cacheList.add(this.f.apply(x)))`
How do you deal with adding the values while iterating to avoid additional "op called" printed?

**Comment by jiexilim** [comment]
oh i do something like `.iterate(seed, predicate, x -> {var value = ur computed value;
cache.add(value);
return value;})`

**Comment by weiyifei-evelyn** [comment]
@jiexilim Thank you very much! I think I know how to deal with the problem!
