### ISSUE TITLE
Lab 7 Level 6 How to use Lazy in LazyList

### ISSUE THREAD

**Issue by jiexilim** [nus-cs2030/2021-s1#276]
I never used Lazy in LazyList, I used f.apply(x) in my code instead and they passed the test cases. But I wonder how to use Lazy in LazyList.
At first, I tried Stream.iterate(Lazy.of(seed), x -> x.map(f))...., and then for my get(i), I iterate the Lazy instances in the list and do "x -> x.get()", but every time when get(i) is called, for instance, get(3), "op called" will appear 6 times. I couldn't figure out how to cache the computed element if I wrap them with Lazy.

**Comment by lkldev** [comment]
Hi, did you collect your stream as a list? if you did you can simply use the `list::get` method to get the item of the particular index. However this item will be wrap in a `Lazy` box, so you will need to get the item out of the `Lazy` box.

**Comment by jiexilim** [comment]
U mean "return this.lazylist.get(i).get()"? I did try this method, but when I called the get(i) again, it will start over and run from 0 to that particular index, like get(3) will print out "op called" 3 times, and then when get(7) is called, "op called" will be printed out 7 times. I guess I need to cache the computed value while calling get()? but i have no idea how

**Comment by lkldev** [comment]
Oooo interesting, the `Lazy` object should be the one providing the caching as well, your LazyList would just need to maintain a list of Lazy object. You are using the Lazy object from the previous levels right?

**Comment by jiexilim** [comment]
Yup, in case I did my Lazy wrong, my get() was something like this: if that value has not been computed, then update the this.value attribute with supplier.get() and update the boolean, and return this.value. I think should be correct?

**Comment by lkldev** [comment]
Yeap it sounds about right, when you say if that value has not been computed, you meant that you check if the boolean is true or false right?

**Comment by jiexilim** [comment]
yup

**Comment by lkldev** [comment]
> At first, I tried Stream.iterate(Lazy.of(seed), x -> x.map(f))...., and then for my get(i), I iterate the Lazy instances in the list and do "x -> x.get()", but every time when get(i) is called, for instance, get(3), "op called" will appear 6 times. I couldn't figure out how to cache the computed element if I wrap them with Lazy.

interesting, and your `generate` method is ` Stream.iterate(Lazy.of(seed), x -> x.map(f)).limit(...).collect(...)`, returning a new instance of LazyList?

**Comment by jiexilim** [comment]
yup
.limit(n).collect(Collectors.toList())

**Comment by lkldev** [comment]
Oooo then it should work fine cause that's all I did... What about your `map` method in `Lazy`? you wrap your the `f.apply` in a Supplier before passing it to the `Lazy` object as well right?

**Comment by jiexilim** [comment]
yess

**Comment by jiexilim** [comment]
but i tested my Lazy using print, based on it, after doing l2.get(), i expect to get one "op called" oni for l2.map(op), but turns out it runs starting from 7 to 8 to 9 again. I am not sure if this is normal
![image](https://user-images.githubusercontent.com/70773974/98215063-47752080-1f82-11eb-8bba-22aae52a4704.png)

**Comment by lkldev** [comment]
Okay, I have a feeling is either your `map` or `get`. Do you mind sharing your codes?

**Comment by jiexilim** [comment]
![image](https://user-images.githubusercontent.com/70773974/98215824-3d075680-1f83-11eb-8f03-e95dbbf6cd1e.png)
![image](https://user-images.githubusercontent.com/70773974/98215859-4690be80-1f83-11eb-82bd-1014f022c99f.png)

**Comment by lkldev** [comment]
Ahhh got it, your map is calling `this.box.get()`, which is calling the `Supplier` again. So if the value is cached, calling `this.box.get()` will trigger the `Supplier` to call the function again and not get the cached value. Instead, you should use the `get` method of the Lazy object, so `this.get()` will do.

**Comment by jiexilim** [comment]
omgggg thank you so muchh !!!
