### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by kahehe** [nus-cs2030/2021-s1#277]
# Description
Creating a RandomGenerator object does not seem to work, and subsequent methods from the RandomGenerator class do not render any output when applied. This is after importing the class RandomGenerator and placing it in cs2030/simulator folder. Does anyone know the issue here? Thanks!

## Topic: 
Java
Project 2

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/60306560/98212996-63c38e00-1f7f-11eb-9cb6-d76938db71a0.png)

**Comment by b-leong** [comment]
you could create another class, which is in the cs2030 package, to initialize the randomgenerator in and use that new class in main instead

**Comment by marcuspeh** [comment]
RandomGenerator's constructor is only accessible within the package.

**Comment by joelwongjy** [comment]
RandomGenerator class is declared private so you probably have to move your Main code into a Simulator class and package that under cs2030.package to access the generator.

**Comment by GnohChengYi** [comment]
You can try making another class that imports and uses RandomGenerator in the package, then import that package in Main
