### ISSUE TITLE
Stream - Normalized Mean

### ISSUE THREAD

**Issue by jedlwk** [nus-cs2030/2021-s1#278]
# Description 
I am currently facing an issue on one of the past Stream exercises that requires me to define a method that takes in a Stream of Integer elements and returns the normalized mean.

I searched up the API and I think I will need to use mapToInt but I am not sure how to.

API: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/package-summary.html

## Topic: 
Stream

## Screenshots (if any): 
![Stream](https://user-images.githubusercontent.com/65217862/98234502-8499dc80-1f9b-11eb-80c3-ba8c04e92662.JPG)

**Comment by fans2619** [comment]
Why do you need that method though?

**Comment by kohwenjie** [comment]
Hi @jedlwk, IntStream has a method called summaryStatistic() which you can call on the stream which gives you all you need to calculate the normalizedMean. Alternatively, you can make your own wrapper class and make use of reduce to get the results you need (similar to using summaryStatistic()). Hope it helps!

**Comment by xingaporean** [comment]
> Hi @jedlwk, IntStream has a method called summaryStatistic() which you can call on the stream which gives you all you need to calculate the normalizedMean. Alternatively, you can make your own wrapper class and make use of reduce to get the results you need (similar to using summaryStatistic()). Hope it helps!

Make a wrapper class, don't use summary statistic its probably not gnna b allowed
knowledge of tenary operator can b useful ( condition ? x : y )

**Comment by kohwenjie** [comment]
@xing221 oops didnt know about that sorry @jedlwk . But you wont go wrong with using the wrapper class.

**Comment by jedlwk** [comment]
@kohwenjie @xing221 Thanks so much! I'll try using a wrapper class!
