### ISSUE TITLE
How to use Piazza?

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#279]
I recently tried to access the module's Piazza so that I could ask additional questions instead of spamming GitHub, but I can't seem to find CS2030 in Piazza? Kindly help

**Comment by tanruiquan** [comment]
I don't think we are using Piazza this sem

**Comment by fans2619** [comment]
Yes, I think prof mentioned somewhere before that we use github instead of piazza!

**Comment by Terence-Sim** [comment]
We're not using Piazza this  time. I closed it down. Please use this Wiki page instead.

**Comment by roopaniedu** [comment]
Alright! Thanks for the clarifications
