### ISSUE TITLE
How do I configure PLAB E-links to allow mouse wheel scrolling?

### ISSUE THREAD

**Issue by Josephaedan** [nus-cs2030/2021-s1#280]
# Summary
When I SSH into my plab account for labs, I am unable to scroll with the mouse wheel to view the contents of the index.html file. The only way I can navigate the file is by pressing the up and down keys, which completely goes up and down an entire page. This is quite annoying, especially in a lab setting when the description of the Level is split into 2 pages and I am unable to read the entire description. Does anyone know if there is a way to enable this, or at least configure the navigation buttons?

## Description 
Describe the problem and how one can replicate this problem 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by leeleonard98** [comment]
Try using insert and delete to navigate, sorry for the late reply hahah

**Comment by jj-weng** [comment]
http://elinks.or.cz/documentation/html/manual.html-chunked/ch03s06.html#:~:text=In%20some%20terminals%2C%20it%20is,longer%20under%20the%20mouse%20pointer.
Hi, this is a link with elinks keys and actions. Even though we don't have any more PE, hope you will find this useful in the future too :)

**Comment by Josephaedan** [comment]
Hi @leeleonard98 @jj-weng thank you very much for the replies and guides. I'll definitely keep them in mind next time I have to use elinks.
