### ISSUE TITLE
Issue with PE#2 last level test cases

### ISSUE THREAD

**Issue by fans2619** [nus-cs2030/2021-s1#284]
# Description 
Hi does anyone encounter the same problem with the test cases for last level of PE#2 on CodeCrunch? I have been looking at the test cases for a long time but cannot figure out what is wrong. Thanks!

# Screenshots: 
![Last Level](https://user-images.githubusercontent.com/68739475/98395656-89dc5180-2097-11eb-9165-a1688cba9e88.png)

**Comment by egsclgns** [comment]
Hey, my last 3 lines of output for this test case are the same as yours. How did you manage to solve it?
