### ISSUE TITLE
PE2 test6_1

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2030/2021-s1#285]
![image](https://user-images.githubusercontent.com/50469557/98432478-9db89f80-20f9-11eb-8b9a-7dc51f34d4d0.png)
I saw this issue posted yesterday but was closed. However, I am still stuck on this. I ensured that if the user takes the sword and go to a new room, the old room will not have a sword. However, that did not solve this output. Is there something I am missing?

**Comment by raynerljm** [comment]
Same I am also struggling with test6_1. It's hard to understand the issue when we don't even know what and how test6_1 tests though

**Comment by raynerljm** [comment]
Okay nevermind I managed to fix mine. Did you ensure that when you back() from a room, that room will also not have a sword?

**Comment by gabrielloye** [comment]
I faced this problem too and fixed it by ensuring that when I am carrying a sword in the go() method from one room to another, I remove the sword from the original room and bring it over to the new room.

**Comment by SkyBlaise99** [comment]
Read the description in level 5
```
Notice that this new mystery room that we just entered looks like the same room before!
Not only that we can also bring an item that we picked into a new room.
```
Hint: for level 6, although im not sure if they did explicitly say this, you can bring the `sword` back with you...
