### ISSUE TITLE
jshell cannot find symbol

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#286]
# Description 
Hi, can I ask what's happening? It works in codecrunch but not in jshell.

## Screenshots (if any): 
<img width="507" alt="cs2030pe2" src="https://user-images.githubusercontent.com/71959340/98437430-fbaaae80-211c-11eb-919c-d9566e698b33.png">

**Comment by bwangpj** [comment]
Try `jshell -q`?

**Comment by marcuspeh** [comment]
Use `javac -q Candle.java Room.java < test1.java`

**Comment by jiehuixx** [comment]
It didn't work :/
<img width="535" alt="cs2030pe2" src="https://user-images.githubusercontent.com/71959340/98437605-76c09480-211e-11eb-952c-6f1e4df26c4b.png">

**Comment by gabrielloye** [comment]
Is the Candle class used in Room? If so, maybe you can try `jshell -q Room.java Candle.java < test.jsh` instead since the ordering of your file dependencies matters when calling it as such.

**Comment by jiehuixx** [comment]
Hi all, I managed to resolve it, thanks for your help!
