### ISSUE TITLE
PE2 test3_1

### ISSUE THREAD

**Issue by kaiyang96** [nus-cs2030/2021-s1#288]
Hi anyone else experience this issue? No idea how to go about it because there doesn't seem to be way for my Room to have things without explicitly calling add
![test 3_1](https://user-images.githubusercontent.com/71059104/98442410-640a8780-213f-11eb-8d6f-017f0fa3b1dd.png)

**Comment by SkyBlaise99** [comment]
The test case are in the form `Room f = smt`, which are somewhere above which you won't see.
Calling `f` only prints the content of `f`.

**Comment by darrenhoon** [comment]
if you used list to store the values, then every room must have a deep copy list

**Comment by qiaoningg** [comment]
Hi! I had this problem too and for me it was because I was returning the same room instead of a new room.

**Comment by kaiyang96** [comment]
> if you used list to store the values, then every room must have a deep copy list

Thanks all! this was the issue I found. Slipped my mind that java exclusively uses Reference types.
