### ISSUE TITLE
PE2 testcase 6_1

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#289]
# Description 
hello im facing a different issue from the others who had problem with this test case. basically for my back method, i used an arraylist to store the rooms for each "go" transition and when back() is called once, i used newroom.visitedrooms.addAll(this.visitedrooms) to make sure the new room has logs of the previous room visits. im facing an internal test case problem, wondering if any1 knows why because i can pass all the testcase given.

![image](https://user-images.githubusercontent.com/71011712/98457713-26e8d880-21c5-11eb-9b72-a945a7e039c7.png)

**Comment by rohit0718** [comment]
have u handled the initial case where your arraylist is empty?

**Comment by e0420658** [comment]
ohh i missed that out! thanks alot!
