### ISSUE TITLE
Confused with the sword output

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#290]
![image](https://user-images.githubusercontent.com/51086295/98458710-813a6700-21ce-11eb-8b41-121b5d4cd600.png)

For this testcase, why is "Sword is shimmering." output not included? My understanding is that the sword is present in the room but is not yet taken.

Because for the previous level
![image](https://user-images.githubusercontent.com/51086295/98458751-d1b1c480-21ce-11eb-9f31-a7c20b11637e.png)
The "Sword is shimmering."  output is present even though the sword is not taken.

Thank you in advance!

**Comment by gabrielloye** [comment]
You can only bring a 'taken' sword from 1 room to another (when you apply the go() method). In this case, the sword is not 'taken' in r2, and will not be brought into r3

**Comment by chongweil907** [comment]
@gabrielloye ahhh that make sense, Thank you !

**Comment by Josephaedan** [comment]
Just to add on, in the reverse scenario: if you are holding the sword, it must be in the room you are in. So if you take the sword from one room to another, the previous room should not have a sword.

**Comment by chongweil907** [comment]
@Josephaedan thanks for the tips ! I am doing level 6 now
