### ISSUE TITLE
[PE2] what is the expected behaviour when back() is called without go() prior?

### ISSUE THREAD

**Issue by jadenwjh** [nus-cs2030/2021-s1#291]
<img width="661" alt="Screenshot 2020-11-08 at 4 06 40 PM" src="https://user-images.githubusercontent.com/62279469/98460122-64a52b80-21dc-11eb-9af4-5805879f5cd7.png">

Currently facing this error and i suspect that it has something to do with back()

**Comment by kohwenjie** [comment]
Hi @jadenwjh , if Im not wrong, what I did was that I returned the current room if there is no room before it. I believe that is the idea to it

**Comment by marcuspeh** [comment]
I returned the same room if theres no previous room

**Comment by jadenwjh** [comment]
@marcuspeh @kohwenjie thanks! managed to solve this
