### ISSUE TITLE
Level 6 PE

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#296]
How do yall guys solve level 6 of PE?
For the back() function, do u store a List of previousRoom in Room class ?
Idk if this results in cyclic dependency.

Thanks in advance!

**Comment by marcuspeh** [comment]
U dont have to store a list of Room but just the previous room since when we call back, it only go back one rule

**Comment by chongweil907** [comment]
@marcuspeh Just to clarify if I wanna call tick(), does all room have to tick() applied to it ? And also if u store the previous room inside a room class, is it considered as cyclic dependency?

**Comment by jj-weng** [comment]
@chongweil907  You are talking about the tick() without the function right?

**Comment by chongweil907** [comment]
@jj-weng yep i am referring to that

**Comment by jj-weng** [comment]
What I did was to store the previous room inside a ArrayList<Room>, but what @marcuspeh said of just storing the previous Room can work too. You can choose the one that modifies your code the least haha

**Comment by chongweil907** [comment]
@jj-weng did u store all the previous room or just the intermediate prev room ?

**Comment by jj-weng** [comment]
Only the previous room. Cause the description says that once you leave a Room, that room vanishes. Hence even if we travel to many many rooms, we only care about the previous one

**Comment by marcuspeh** [comment]
> @marcuspeh Just to clarify if I wanna call tick(), does all room have to tick() applied to it ? And also if u store the previous room inside a room class, is it considered as cyclic dependency?

Nope. Only to the current room. And it doesn't since the calling of constructor for a room does not depends on the calling of constructor of another instance of the room

**Comment by chongweil907** [comment]
Can I assume that we can only bring back sword  to previous room ?
