### ISSUE TITLE
Project #2 codecrunch outputs

### ISSUE THREAD

**Issue by benluiwj** [nus-cs2030/2021-s1#297]
Codecrunch expected outputs seem to be different from the expected outputs given to us for the task. 

This is the code crunch output as seen below
![2020-11-09 21 40 35](https://user-images.githubusercontent.com/67570985/98548289-46225b80-22d4-11eb-8c55-d80c69d14b13.jpg)

This is the task output as seen below
![Screenshot 2020-11-09 at 9 41 44 PM](https://user-images.githubusercontent.com/67570985/98548478-8681d980-22d4-11eb-89c0-4cfd2d340bfd.png)

**Comment by taneshin** [comment]
Yeah I think have to include "Server" since we will be adding self-serve counters. There is a possibility of being served by either and we need to specify.
