### ISSUE TITLE
Project 2 Level 1 (design of Server)

### ISSUE THREAD

**Issue by bwangpj** [nus-cs2030/2021-s1#298]
While the main aim of level 1 is a constraint check on `Shop` (perfectly understandable), it also enforces a constructor for `Server` of the form `Server(int identifier, boolean isAvailable, boolean hasWaitingCustomer, double nextAvailableTime)`. 

However, with the introduction of self-checkout counters, this seems rather problematic to me. Since the self-checkout counters have a shared queue, updating `hasWaitingCustomer` from `false` to `true` (say) for one self-checkout entails updating it for _all_ the self-checkout counters in the `Shop`. This means either `Shop` or `Event` needs to have some knowledge of the difference between a human `Server` and a self-checkout `Server`, which to me seems to violate OOP principles. 

Am I missing something here, or is there a better workaround for this?

**Comment by taneshin** [comment]
There are a few approaches you can take.

1) you can have an overloaded constructor. Then adjust your logic such that you don't have to care what value hasWaitongCustomer is
2) when you update a self check out counter, you will iterate though all other self checkout counters and change them accordingly.
