### ISSUE TITLE
PE2 Lvl 6_1

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#299]
![image](https://user-images.githubusercontent.com/65516485/98553120-3c035b80-22da-11eb-8392-b17730489b9a.png)

What are these cases testing? I've seen #285 and tried removing the sword from the previous room if its taken.

**Comment by CWei88** [comment]
Did you bring the sword back when you call back()?

**Comment by chongweil907** [comment]
![image](https://user-images.githubusercontent.com/51086295/98561549-fea3cb80-22e3-11eb-9804-db8a5e46299e.png)

sorry to hijack this thread, 
What might be a reason for this ? I remembered to bring the sword back when i called back()

**Comment by colintkn** [comment]
@CWei88 Yes i did. I would bring back the sword if the sword was taken.

**Comment by simxl** [comment]
@chongweil907 when u bring the taken sword to another room after go(), did u remove the taken sword from the original room?

**Comment by zimmmz** [comment]
@chongweil907 agreed with @zeriw when you go() and the sword is taken you will need to drop the sword in your original room then take your sword to the next room. Have the same exact problem on cc as yours just now n I resolve it by dropping the sword.

**Comment by zimmmz** [comment]
@colintkn did you still have ur sword in the previous room if the sword is not taken? cuz it looks like you remove your sword somewhr when it should not be removed?

**Comment by chongweil907** [comment]
@zimmmz @zeriw U both are right. Finally done with this PE. Thanks you so much for the help!

**Comment by rcdl2222** [comment]
@colintkn when you run your testcases, it should not affect one another, i.e. when you takeSword in a test case (e.g. from room i), you have to make sure that the original Room object assigned (room i) still has the sword when you call it. If the sword is not found, means you have broken immutability somehow. Hope this helps.

**Comment by colintkn** [comment]
Thanks for your help @rcdl2222 and @zimmmz , @CWei88 👍. Problem solved
