### ISSUE TITLE
[Proj2] Cyclic dependencies

### ISSUE THREAD

**Issue by taneshin** [nus-cs2030/2021-s1#300]
> Cyclic dependencies detected within:
> ArriveEvent.class -> Event.class
> ArriveEvent.class -> LeaveEvent.class
> ArriveEvent.class -> ServeEvent.class
> ArriveEvent.class -> Server.class
> ArriveEvent.class -> Shop.class
> ArriveEvent.class -> WaitEvent.class
> Break.class -> Event.class
> Break.class -> ServeEvent.class
> Break.class -> Server.class
> Break.class -> Shop.class
> DoneEvent.class -> Break.class
> DoneEvent.class -> Event.class
> DoneEvent.class -> SelfService.class
> DoneEvent.class -> ServeEvent.class
> DoneEvent.class -> Server.class
> DoneEvent.class -> Shop.class
> Event.class -> Server.class
> Event.class -> Shop.class
> LeaveEvent.class -> Event.class
> LeaveEvent.class -> Server.class
> LeaveEvent.class -> Shop.class
> Main.class -> Break.class
> Main.class -> DoneEvent.class
> Main.class -> Event.class
> Main.class -> LeaveEvent.class
> Main.class -> Manager.class
> Main.class -> ServeEvent.class
> Main.class -> Shop.class
> Manager.class -> ArriveEvent.class
> Manager.class -> Event.class
> Manager.class -> SelfService.class
> Manager.class -> Server.class
> Manager.class -> Shop.class
> SelfService.class -> Server.class
> SelfService.class -> Shop.class
> ServeEvent.class -> DoneEvent.class
> ServeEvent.class -> Event.class
> ServeEvent.class -> Server.class
> ServeEvent.class -> Shop.class
> Server.class -> Shop.class
> Shop.class -> Server.class
> WaitEvent.class -> Event.class
> WaitEvent.class -> Server.class
> WaitEvent.class -> Shop.class
> Grading terminated.

Anyone has any tips on what constitutes a cyclic dependency and how to avoid them

**Comment by rezlite** [comment]
When your classes have no hierarchy, e.g. try checking if your Event class calls any of its subclass like creating a new ArriveEvent (if so this makes Event dependent on ArriveEvent)

**Comment by yuanxintaxon** [comment]
i think some parts of your design have problem. (probably u trigger some call back?)

you can fix this easily by avoiding call back function/method. You will have to check your code for any call back

**Comment by marcuspeh** [comment]
Im getting the same issue too. Even my TimeComparator got a dependency on Event even though there's nothing about TimeComparator in Event

**Comment by zzkzzzz** [comment]
same issue here. The subclass of Event cant use Shop and Event? I don't understand ...

**Comment by yuanxintaxon** [comment]
What do you have in your constructors (or rather the attributes) in each sub event classes?

**Comment by zzkzzzz** [comment]
I

> What do you have in your constructors (or rather the attributes) in each sub event classes?

They all have one super() , and use the methods in Shop and Server. Is that allowed?

**Comment by yuanxintaxon** [comment]
> It shud be fine. I guess u are using instanceof  inappropriately somewhere in your code (which result in cyclic dependencies)
> 
> > What do you have in your constructors (or rather the attributes) in each sub event classes?
> 
> They all have one super() , and use the methods in Shop and Server. Is that allowed?

**Comment by zzkzzzz** [comment]
> > It shud be fine. I guess u are using instanceof  inappropriately somewhere in your code (which result in cyclic dependencies)
> > > What do you have in your constructors (or rather the attributes) in each sub event classes?
> > 
> > 
> > They all have one super() , and use the methods in Shop and Server. Is that allowed?

But even the Shop have this issue with Server. Shop suppose to deal with Server, right?

**Comment by yuanxintaxon** [comment]
> > > It shud be fine. I guess u are using instanceof  inappropriately somewhere in your code (which result in cyclic dependencies)
> > > > What do you have in your constructors (or rather the attributes) in each sub event classes?
> > > 
> > > 
> > > They all have one super() , and use the methods in Shop and Server. Is that allowed?
> 
> But even the Shop have this issue with Server. Shop suppose to deal with Server, right?

Yes it is dealing with server. But if your hierarchical structure is wrong, then there will be a problem. do you have any code that compute the server first, and then the shop?

**Comment by zzkzzzz** [comment]
> > > > It shud be fine. I guess u are using instanceof  inappropriately somewhere in your code (which result in cyclic dependencies)
> > > > > What do you have in your constructors (or rather the attributes) in each sub event classes?
> > > > 
> > > > 
> > > > They all have one super() , and use the methods in Shop and Server. Is that allowed?
> > 
> > 
> > But even the Shop have this issue with Server. Shop suppose to deal with Server, right?
> 
> Yes it is dealing with server. But if your hierarchical structure is wrong, then there will be a problem. do you have any code that compute the server first, and then the shop?

Problem solved!  Thank you!
It's because my Shop -> Server, but my Server-> Event, then Event have Event-> Shop. 
 It's not Cyclic dependencies between two classes. It involved multi classes.

**Comment by yuanxin1997** [comment]
Nice !

**Comment by yuanxintaxon** [comment]
> > > > > It shud be fine. I guess u are using instanceof  inappropriately somewhere in your code (which result in cyclic dependencies)
> > > > > > What do you have in your constructors (or rather the attributes) in each sub event classes?
> > > > > 
> > > > > 
> > > > > They all have one super() , and use the methods in Shop and Server. Is that allowed?
> > > 
> > > 
> > > But even the Shop have this issue with Server. Shop suppose to deal with Server, right?
> > 
> > 
> > Yes it is dealing with server. But if your hierarchical structure is wrong, then there will be a problem. do you have any code that compute the server first, and then the shop?
> 
> Problem solved! Thank you!
> It's because my Shop -> Server, but my Server-> Event, then Event have Event-> Shop.
> It's not Cyclic dependencies between two classes. It involved multi classes.

nice

**Comment by TarciusW** [comment]
Cyclic dependencies occur when classes are dependant on each other to work that! that could be a parent/child class (i.e. parent -> child, child -> parent)  or in this case where you have it multiple-classes involved. do try to keep your code as simple as possible to avoid cyclic dependency! :)
