### ISSUE TITLE
Project2 Testcase 4_4

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#301]
# Description 
Hi was wondering if anyone had faced a similar issue with this test case? My implementation of ServeEvent is to mutate the server assigned to it for its nextAvailTime to be startTime of the serveEvent + serviceTime, then replacing it in shop when returning a doneEvent. Im not quite sure why it fails this testcase .. and the outputs get more haywire as the events progress for each customer.

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/71011712/98573667-15e9b580-22f2-11eb-8d05-f332ac64bf34.png)

**Comment by yuanxintaxon** [comment]
your done/serve event need to pull the latest server from the shop. Cuz there's possibility that it is overwritten.

**Comment by e0420658** [comment]
ohh so within those two, i wld have to do my checks to get the server again? but lets say for the test case given in codecrunch where 9 and 10 are both waiting to be served by 1, is there any change to the server assigned at the wait event?

**Comment by yuanxintaxon** [comment]
Only for Serve, done and serverback event you need to check the latest server again.  (these events are returned after some times, there could be something happening in between, that's why you need to get the latest server again)

Wait event do not need to check, cuz it is executed immediately.

**Comment by e0420658** [comment]
may i ask how did u manage to get the updated servers from shop? because the my event subclasses only has the current state of the shop when its passed in from ArriveEvent, and subsequently from arriveEvent, i get the server to serve/wait and this server get passed on all the way to done

**Comment by e0420658** [comment]
![image](https://user-images.githubusercontent.com/71011712/98633374-3c443b00-235c-11eb-9e53-eef7d0f78e1e.png)
i printed out the shop when serve and done is executed and it doesnt update well?

**Comment by yuanxintaxon** [comment]
Sorry for the late reply, You can try something similar to this. The shop always have the updated server, so we need to get the same server using server identifier.

![image](https://user-images.githubusercontent.com/22881271/98640875-cb098580-2365-11eb-92d8-dd520ec5f506.png)



> may i ask how did u manage to get the updated servers from shop? because the my event subclasses only has the current state of the shop when its passed in from ArriveEvent, and subsequently from arriveEvent, i get the server to serve/wait and this server get passed on all the way to done

**Comment by e0420658** [comment]
> Sorry for the late reply, You can try something similar to this. The shop always have the updated server, so we need to get the same server using server identifier.
> 
> ![image](https://user-images.githubusercontent.com/22881271/98640875-cb098580-2365-11eb-92d8-dd520ec5f506.png)
> 
> > may i ask how did u manage to get the updated servers from shop? because the my event subclasses only has the current state of the shop when its passed in from ArriveEvent, and subsequently from arriveEvent, i get the server to serve/wait and this server get passed on all the way to done

hi! thanks for the suggestion, ive tried it but mine stiil fails the testcase, i am able to account for the given testcase we see in codecrunch but in testcase 4.4, 8 gets served even though 7 is still being served, and the subsequent customers who are supposed to be waiting ends up getting served after arriving

**Comment by yuanxintaxon** [comment]
> > Sorry for the late reply, You can try something similar to this. The shop always have the updated server, so we need to get the same server using server identifier.
> > ![image](https://user-images.githubusercontent.com/22881271/98640875-cb098580-2365-11eb-92d8-dd520ec5f506.png)
> > > may i ask how did u manage to get the updated servers from shop? because the my event subclasses only has the current state of the shop when its passed in from ArriveEvent, and subsequently from arriveEvent, i get the server to serve/wait and this server get passed on all the way to done
> 
> hi! thanks for the suggestion, ive tried it but mine stiil fails the testcase, i am able to account for the given testcase we see in codecrunch but in testcase 4.4, 8 gets served even though 7 is still being served, and the subsequent customers who are supposed to be waiting ends up getting served after arriving

You need to check for clashes, and reschedule them accordingly.
So in your serve event class , there should be 2 possible outcome. 
1 -> Done event
2 -> serve event. (reschedule)

**Comment by e0420658** [comment]
thanks alot for your help!!! finally got it to work

**Comment by colintkn** [comment]
![image](https://user-images.githubusercontent.com/65516485/98973954-54c87700-254f-11eb-8cf5-939c620fb875.png)


Did you encounter this problem in test 4-4?

**Comment by e0420658** [comment]
hi! i wasnt able to see if i had this problem as my testcase for 4.4 was haywire from the start but i think you havent updated the shop properly yet so u have to get the latest shop in the serve event. Also for me, i got my latest shop in my wait event as well because of my implementation, so maybe u can try that

**Comment by colintkn** [comment]
Currently, I'm getting the latest server at every event (Wait, serve, done). Still facing this problem. But thanks for your input.

**Comment by e0420658** [comment]
hmm it seems as though the queue is not updated properly , maybe u could check your attributes in your server to make sure that when a customer is waiting, u added 1 to the queue and only when its served then u minus 1

**Comment by colintkn** [comment]
Oh yes. Found it. Thanks :)
