### ISSUE TITLE
Project 2 - hidden level 8

### ISSUE THREAD

**Issue by yuanxintaxon** [nus-cs2030/2021-s1#303]
Does anyone has the same issue? I don't think i have access to this "random generator" java file.

![image](https://user-images.githubusercontent.com/22881271/98608159-9544ac80-2325-11eb-8026-5c9c71ca42ec.png)

**Comment by yhtMinceraft1010X** [comment]
This RandomGenerator file is the one that was compiled and given to us. 

The Checkstyle for RandomGenerator failed but there's nothing we can do since source code is not released to us.

Have to wait for this to be addressed. But you should be on the right track.

**Comment by bwangpj** [comment]
I believe this issue has been resolved on CodeCrunch.

**Comment by yuanxintaxon** [comment]
Ya , it has been resolved. just went to check. Thanks for notifying.
