### ISSUE TITLE
Proj 2 ArriveEvent cannot be found

### ISSUE THREAD

**Issue by markuz5116** [nus-cs2030/2021-s1#304]
![image](https://user-images.githubusercontent.com/50469557/98620147-aac6d000-233f-11eb-9b8f-70d431d97f23.png)
Code crunch cannot find my ArriveEvent, though when I pass in the same argument into my main class, the correct output is given. Does anyone have any idea how to rectify this? Thanks!
![image](https://user-images.githubusercontent.com/50469557/98620242-dfd32280-233f-11eb-8bc3-84c5c862073b.png)

**Comment by Jcheez** [comment]
You can try inserting the following statement:
 import cs2030.simulator.ArriveEvent
