### ISSUE TITLE
PE2 Level 6 test6

### ISSUE THREAD

**Issue by changziming** [nus-cs2030/2021-s1#305]
# Description 
I am running into an error where "Sword is shimmering" is printed before "Candle is getting shorter" after going back to the previous room. However, as stated in level 5, the printing of "Sword is shimmering" should appear before other messages when bringing sword into a room. Im not sure if there is something wrong with my logic. Any help is much appreciated!

## Topic: 
PE2 level 6
testcase: `r3.tick(takeSword).back().tick(killTroll).back()`

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/57001713/98661166-1aa97a80-2381-11eb-9c16-cef370dbc054.png)

**Comment by SkullPirateTK** [comment]
You can add the sword to the end of the object list instead of the front.
