### ISSUE TITLE
PE 6_1 Extra Sword Outputs

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#306]
Hi, I am almost done with my PE but am left with solving these errors. I can't seem to pinpoint where exactly my code has gone wrong. Any ideas?

![image](https://user-images.githubusercontent.com/66832279/98672288-8e06b880-2390-11eb-8eb0-109a2d1eec21.png)

**Comment by fans2619** [comment]
Consider this test case:
Now I have 4 rooms, r1, r2, r3, and r4. Among them, r2 and r4 have swords inside. I take the sword in r2 and bring it to r3, then bring it to r4, then drop the sword in r4. After this, I come back to r3 or r2. As a consequence, Now there should be no sword in r3 or r2.

**Comment by fans2619** [comment]
You can always create the 4 rooms by yourself and test it!

**Comment by fans2619** [comment]
This is only one possible scenario that might cause problems to the output. Actually, it means you might want to reconsider and modify some part of your code to make it satisfy all the possible scenarios (i.e. make your code always give output that can make sense in real lives).

**Comment by fans2619** [comment]
By the way, there are also some similar issues posted before. There might be some useful suggestions!

**Comment by rcdl2222** [comment]
I have the test case for this problem:
![image](https://user-images.githubusercontent.com/71259013/98673664-a4157880-2392-11eb-9b4b-3ea82c693a73.png)
The problem arises when you bring a Sword around the rooms.  Try to play around with the back() using the above to debug. Room k = j.back() and room l = k.back()

Hope this helps.

**Comment by marcuspeh** [comment]
So if u go from room1 to room2 carrying a sword, should your sword be remove from room1? You didnt renove it and when u go back, you brought back the sword and there's 2 sword now in room1

**Comment by Chen-Yiyang** [comment]
> So if u go from room1 to room2 carrying a sword, should your sword be remove from room1? You didnt renove it and when u go back, you brought back the sword and there's 2 sword now in room1

Technically yes, there should no longer be a sword in room1, but due to functional programming you cant really implement that and change the original room1. However, you can by-pass the issue by checking and removing the old sword before going back to room1 from room2.

**Comment by changziming** [comment]
Just make sure to check if you have taken a sword every time you change rooms. If you have taken a sword, then remember to remove from that room before moving on to the next.

**Comment by roopaniedu** [comment]
I managed to fix the outputs for j, k and l but i'm not too sure what the test cases are for the below ones

![image](https://user-images.githubusercontent.com/66832279/98690452-ebf2ca80-23a7-11eb-9bfb-60f2aaf274aa.png)

**Comment by rajobasu** [comment]
Basically, you are not dropping the sword. so when you pick it up and go to another room, you have to remove it from previous room. Also, if you re-enter a room already carrying a sword, then erase the sword in the old room. this worked for me.

**Comment by georgepwhuang** [comment]
You can only have one sword that you can bring around, and you can only acknowledge one sword in the room, so I just delete the other swords.

**Comment by jiayi-lim** [comment]
Did the same thing as @georgepwhuang! Just remove all the swords first using instanceof and check whether you took a sword with you! If you took the sword with you, then add a sword back into the items in the room.

**Comment by roopaniedu** [comment]
Nice! Thanks everyone. I managed to finish it all :)

**Comment by marcuspeh** [comment]
> > So if u go from room1 to room2 carrying a sword, should your sword be remove from room1? You didnt renove it and when u go back, you brought back the sword and there's 2 sword now in room1
> 
> Technically yes, there should no longer be a sword in room1, but due to functional programming you cant really implement that and change the original room1. However, you can by-pass the issue by checking and removing the old sword before going back to room1 from room2.

Im not saying that he need to change original room1 but more of how he should store a updated room1 in room2 to use as back instead of original.

**Comment by enqiilim** [comment]
Hi I got the same problem too but I'm not sure how to solve it, it seems like i have really way too many swords in the room.
![image](https://user-images.githubusercontent.com/65434451/99037178-2d5cc300-25be-11eb-811e-23b1d32e39e6.png)

**Comment by jiehuixx** [comment]
@enqiilim Hi, I had similar issues too, as what the previous comments have said, you have to modify your go function to remove the sword in the original room.

**Comment by enqiilim** [comment]
@jiehuixx ohh I think i got it, thanks!
