### ISSUE TITLE
Project 2 Level 3 Create package

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#307]
Hi guys! I don't understand how I can create a package and use it, as well as how I should put the .java files under the folders.

For now, my working directory is called `PART 2 copy` and I created a sub-directory in this folder called `cs2030/simulator`. Then I moved RandomGenerator.class into this `cs2030/simulator` folder. My Main.java, as well as the rest of Event, Customer, Shop classes, is still in the `PART 2 copy` folder. Also, I imported RandomGenerator by stating `import cs2030.simulator.RandomGenerator;`. (seen in the screenshot below)
<img width="257" alt="Screenshot 2020-11-10 at 8 13 43 PM" src="https://user-images.githubusercontent.com/71199647/98673585-847e5000-2392-11eb-80e6-2caf9da62b54.png">

However, when I try to compile the classes and run Main. It shows `cannot find symbol`. 
Can someone help me with this problem? Thanks a lot!

**Comment by waynetee** [comment]
try these
```
javac -d . *.java
java Main
```

**Comment by weiyifei-evelyn** [comment]
> try these
> 
> ```
> javac -d . *.java
> java Main
> ```

@waynetee Thank you for your response. I tried but it still gave me "package cs2030.simulator does not exist".
Attached the screenshot for your reference.
<img width="699" alt="Screenshot 2020-11-10 at 9 18 35 PM" src="https://user-images.githubusercontent.com/71199647/98679074-6c123380-239a-11eb-8d70-eacfb9558c3b.png">
Is it something else going wrong?

**Comment by marcuspeh** [comment]
Maybe put all your package files into the `cs2030/simulator` folder, with the Main outside. And then call `javac Main`. But note you have to delete the class files within the simulator each time you call that since the java files within the package will only compile if class file is not present

**Comment by waynetee** [comment]
See #252 

You are only able to call RandomGenerator from classes inside the package. Note that you don't need to import it in those classes. Hope this helps :)

**Comment by weiyifei-evelyn** [comment]
@waynetee Thank you for your reply. After reading through those replies in #252, I am still confused about how to make it work. To explain it more explicitly, I need to 
1) move all the Customer, Shop, Event (including ArriveEvent etc) java files into this `cs2030/simulator` folder; leave Main.java outside
2)  include the line package cs2030.simulator in every java file in the `cs2030/simulator` folder

Is this correct?

From some posts in #252, some mentioned that there is a need to create a "Manager" class within the package. This "Manager" class will be called in Main to do the simulation, to solve the issue of private constructor of RandomGenerator.
Does it mean that in addition to the two steps mentioned above, I need to create a "Manager" class in the package?

**Comment by weiyifei-evelyn** [comment]
@waynetee @marcuspeh Thank you for your help. I successfully resolved the problem!!

**Comment by limyapkai** [comment]
@weiyifei-evelyn Hi! Could you share a solution to this? I still can't figure out how to resolve getting this .class to work :( 

Did exactly the same as this:
1. move all the Customer, Shop, Event (including ArriveEvent etc) java files into this cs2030/simulator folder; leave Main.java outside
2. include the line package cs2030.simulator in every java file in the cs2030/simulator folder

Created a Simulator.java in the cs2030/simulator folder and tried calling

RandomGenerator rng = new RandomGenerator(.......)

But got the error flag arggghhhhhh :<
