### ISSUE TITLE
PE2 Final Testcase

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#309]
# Description 
Hello did anyone else get this error? Or anyone has any idea why?

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/61898858/98697420-ded9d980-23af-11eb-8e52-0bc8e84b18b4.png)

**Comment by waynetee** [comment]
try checking the back() method of a new room (room without parent)

**Comment by fans2619** [comment]
I remember this test case is that suppose you are at first room and you want to go back, then there is NO tick needed. Basically just return the current room will be fine I think.

**Comment by fans2619** [comment]
But yours seems like missing the Candle? I don't know where your candle has gone to.

**Comment by ghost** [comment]
@waynetee Hmm I don't quite follow. How does back() influence whether the candle is there or not?

**Comment by SkyBlaise99** [comment]
What `waynetee` means is that when u create a new `Room` with no previous `Room` and attempt to call `back()`, it should return current `Room` with nothing touched.

**Comment by ghost** [comment]
I have an if statement in which

if (previous == this) {
return this;
}

but I'm not sure whether it will influence the candle

**Comment by SkyBlaise99** [comment]
Don't use `==` for non integer comparison.
And did you overwrite the default `equals` method to say how 2 `Room`s are equal?

**Comment by ghost** [comment]
== can be used to compare addresses right? So if 2 objects have the same address theoretically it might still work?
2 rooms should be equal if they have the same name, which is a String comparison, in which == is not recommended but should work fine as long as the Strings are not changed to my knowledge.
Anyway, I changed it to if (prev.name.equals(this.name)) and I still get the same output :( do you think I need to consider the items inside the rooms as well?

**Comment by SkyBlaise99** [comment]
then i suggest u print out the content of the current and previous `Room`s to debug? maybe you forgot to copy stuff over or smt

**Comment by ghost** [comment]
Oh wait a second!!! Turns out its a very stupid thing that I did. I said I returned this in a previous comment, but I actually returned previous!!! Daaaaaaaaang wasted couple of hours on this but thanks for all the help! @waynetee @weitsang @SkyBlaise99
