### ISSUE TITLE
PE2 Level 6_1

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#310]
Hi, I really need help understanding what's wrong. Please advice thanks!

## Screenshots (if any): 
<img width="346" alt="cs2030pe2" src="https://user-images.githubusercontent.com/71959340/98753693-df9a5c00-23ff-11eb-8668-ad5ce72b470c.png">

**Comment by SkyBlaise99** [comment]
You are inheriting the previous `Room`'s name

**Comment by jiehuixx** [comment]
It has been resolved, thank you!
