### ISSUE TITLE
PE2 test6_1

### ISSUE THREAD

**Issue by NaokiShum** [nus-cs2030/2021-s1#313]
Hi, I have 2 extra troll outputs in the final test case and I cant figure out why. Has anyone else encountered this problem?

![image](https://user-images.githubusercontent.com/66548350/98760769-eed4d600-240e-11eb-88aa-73da1bbf9213.png)

**Comment by ghost** [comment]
Maybe you forgot to remove the troll when you killed him?

**Comment by Josephaedan** [comment]
Since Level 6 is regarding the back() method, Test6_1 should be testing all the edge cases for the back() method. It probably has something to do with the way you handle returning to the previous room after executing the go() method? Maybe testing a test case where you go to a room, kill the troll in that room, go to another room and then go back to the room with the killed troll would help?

**Comment by changziming** [comment]
Make sure to remove the troll after killing it. Maybe something wrong in your killTroll function

**Comment by NaokiShum** [comment]
> Since Level 6 is regarding the back() method, Test6_1 should be testing all the edge cases for the back() method. It probably has something to do with the way you handle returning to the previous room after executing the go() method? Maybe testing a test case where you go to a room, kill the troll in that room, go to another room and then go back to the room with the killed troll would help?

I tried doing the test case you mentioned and the output looks fine. Do you have any idea what other test cases might have caused the incorrect output?

![image](https://user-images.githubusercontent.com/66548350/98801026-2ca41f80-244c-11eb-8640-0159ab7d01a3.png)

**Comment by NaokiShum** [comment]
For my killTroll function, I returned a new Room with the troll removed after killing it. Is there anything else that I missed out doing?

**Comment by raynerljm** [comment]
It is unlikely that it is to do with your killTroll function as it is just removing the troll. Is there something somewhere within your go or back function that creates a new room with a new copy of the items? That's the only thing I could think of that could make the troll reppear

**Comment by NaokiShum** [comment]
> It is unlikely that it is to do with your killTroll function as it is just removing the troll. Is there something somewhere within your go or back function that creates a new room with a new copy of the items? That's the only thing I could think of that could make the troll reppear

Thanks a lot, it was something to do with the copy of items that I returned in my go function.
