### ISSUE TITLE
Project 2 Test case 4_4

### ISSUE THREAD

**Issue by chuashiqi** [nus-cs2030/2021-s1#315]
# Description 
Hi, did anybody encounter this error? Not sure what is wrong and not sure what to debug. 
![image](https://user-images.githubusercontent.com/70755428/98770512-63167600-241d-11eb-8e59-69c86dcb8b4a.png)

**Comment by zzkzzzz** [comment]
I think the problem is the sequence you call `genServiceTime()`. The nth customer to arrive might not be the nth customer to be served. 
You should make the service time lazy like `()->genServiceTime()` then you get the result when the customer is being served.

**Comment by chuashiqi** [comment]
will test out thanks!

**Comment by tlylt** [comment]
> will test out thanks!

Hi @shhiiiqqqqiiiii ! 
Got the exact same issue as you...Did you manage to solve it and what was the culprit??
