### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#316]
My code passes all the test cases shown on the question page of level 3. However, when I uploaded my code to code crunch, it fails test 3_2. However, it didn't show the full test cases that I didn't pass. I attached a screenshot of the test output shown on code crunch. I imply that the test outputs are 5 customers coming and leaving immediately, and none of them were served. However, based on my interpretation of the question, this is impossible because when the first customer comes in, he must be served since there is always an available first server.
<img width="301" alt="Screenshot 2020-11-11 at 2 58 47 PM" src="https://user-images.githubusercontent.com/71199647/98779192-74b44980-242e-11eb-9e59-bd8b272fcc74.png">

Could someone help me find what's the problem leading to errors?

Appreciate your help!

**Comment by weiyifei-evelyn** [comment]
To add on, my Main class create a new Shop containing the specified number of available servers. Then, these available servers serve the customers accordingly and events (i.e. ArriveEvent, ServeEvent, WaitEvent, DoneEvent, LeaveEvent(when there is someone waiting)) are printed out

**Comment by JedrekLoo** [comment]
Hi I believe this test case is when there are 0 servers in the Shop.

**Comment by weiyifei-evelyn** [comment]
@JedrekLoo Ohhhh Thank you!!!
