### ISSUE TITLE
Project 2 lvl 5

### ISSUE THREAD

**Issue by Clem-cpu** [nus-cs2030/2021-s1#317]
I'm having abit of trouble figuring out how to do the Server_Rest event. Can i check if i have to create a new ServerRest and ServerBack Event which extends Event?

Also, since ServerRest happens after the Done event, how do i know which customer to be Served after the ServerBack event.
Or am I wrong in saying that ServerRest happens after Done event

**Comment by SkyBlaise99** [comment]
You are right that ServerRest is after DoneEvent. Whether or not if you want to create the 2 new Event is entirely up to you to implement.
The next Customer in the queue will get served when the Server comes back from rest.

**Comment by LiuYanJulia** [comment]
The question said that ServerRest and ServerBack should be scheduled in the simulator, but I did not see any print out messages for the 2 events in the public test cases. So we do not need to print these 2 events out?

**Comment by Clem-cpu** [comment]
@LiuYanJulia yeah i think you're not supposed to print these 2 events.

@SkyBlaise99 actually, for the genRandomRest, where do u carry this out. Cause for now I pass the RNG object to my Server Class and carry out the genRandomRest from there. Is the logic flawed if I do that.

**Comment by tien87chun** [comment]
@Clem-cpu similar to genServiceTime(), you could pass it lazily into Arrive -> Wait -> Serve -> Done
another alternative is to pass it lazily into Shop, which is what I did (because it seemed like less of a hassle since I don't have to pass it through so many classes)

**Comment by SkyBlaise99** [comment]
@Clem-cpu `genRandomRest` is carried out after `DoneEvent`. After the `Server` is done serving, `genRandomRest` determines whether the `Server` go to rest or continue serving the next `Customer`.

**Comment by colintkn** [comment]
Just to check, when the Server is resting, is it allowed to continue to take people in its queue? (within the max queue limits)

e.g. Given the max limit of 5 people in queue. 
Server 1 is put to rest, and currently has 2 people in queue.
During the time it is resting, can other people join the queue?

**Comment by SkyBlaise99** [comment]
Can
