### ISSUE TITLE
Project 2 Level 4: Failure to pass previous level test cases, so overload constructors?

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#319]
Hi, in level 4 of project 2, we need to take in one more input called "maximum queue length". Thus, I have modify the constructor of ArriveEvent from new ArriveEvent(Customer) to  ArriveEvent(Customer, qMax). Also, I change the "hasWaitingCustomers" property of Server to an int field which counting the number of customers in the queue However, this will change the original constructor of ArriveEvent, thus I failed the test cases at Level 2.

So how do you solve this issue? Do you overload constructors for every Event class?

**Comment by bwangpj** [comment]
You can keep `hasWaitingCustomers`. Since you've already added an int field counting the number of customers in the queue in `Server`, you can add `qMax` in `Server` as well instead of `ArriveEvent`.

**Comment by weiyifei-evelyn** [comment]
@bryanwangpengjun Okay, I get it. Thanks for your help!

**Comment by chongweil907** [comment]
@weiyifei-evelyn hi in the end did u use a overloaded constructor for the server class? I am quite confused about how to set the qmax for the server.

**Comment by weiyifei-evelyn** [comment]
> @weiyifei-evelyn hi in the end did u use a overloaded constructor for the server class? I am quite confused about how to set the qmax for the server.

Yes, before @bryanwangpengjun gave his suggestion, I use an overloaded constructor for the server class as well as for ArriveEvent class. It works but I think the design is not very good.
