### ISSUE TITLE
PE2 Test 6

### ISSUE THREAD

**Issue by enqiilim** [nus-cs2030/2021-s1#320]
Hello! I've been I've been trying to debug my code but I can't seem to find what's wrong, I cant get the correct output

![photo_2020-11-12_11-02-18](https://user-images.githubusercontent.com/65434451/98890302-a1bc3700-24d6-11eb-829d-dfe0b812818e.jpg)
![photo_2020-11-12_11-02-11](https://user-images.githubusercontent.com/65434451/98890305-a2ed6400-24d6-11eb-89d0-46885778532f.jpg)

**Comment by domlimm** [comment]
Hi, I have had the same problems as you.

Print out your `back` before you return the previous room and see what is in the contents of your previous room. Try to work backwards.

Also, check if you've successfully brought the sword back to the previous room if you've had the sword in the current room.

**Comment by marcuspeh** [comment]
You `back()` has issue. Perhaps you change the previous roon somehow when u are use `tick()` and instead of just `go()`. Try printing out your previous room to debug where u did that

**Comment by kaiyang96** [comment]
Easiest way to debug would be to print out the details of both the room you enter and leave when u initiate go/back, to see if they have the correct items, names etc. Good luck!

**Comment by enqiilim** [comment]
![image](https://user-images.githubusercontent.com/65434451/98935906-2f237980-251f-11eb-9ab9-4f2dc18e6b3e.png)
![image](https://user-images.githubusercontent.com/65434451/98935927-35b1f100-251f-11eb-8dfa-73f91231446c.png)
Now I'm getting extra swords in my output and I can't tell if the problem is with my dropSword or is my back(), I'm now just confused at the items

**Comment by enqiilim** [comment]
```
public Function<Room,Room> dropSword = x -> {
    System.out.println(x.getitems());
    ArrayList<Thing> newlist = new ArrayList<>();
    for (Thing thing: x.getitems()) {
        newlist.add(thing);
        if (thing instanceof Sword) {
            newlist.remove(thing);
            //newlist.add(new Sword());
            System.out.println("--> You have dropped sword.");
        }
    }
    System.out.println(newlist);
    return new Room(x.getRoom(), newlist);
}
```

My dropSword looks like this (will delete the code afterwards)

**Comment by jerimiglo** [comment]
Did you remember to remove the sword before leaving the old room? (if sword is taken). You can try printing the room returned by back() to check if the contents returned are correct.

**Comment by enqiilim** [comment]
@jerimiglo 
I tried to remove the sword from from the old room but not sure why it wasn't possible in the loop, they gave me an error saying concurrent modification exception
```
       for (Thing thing: this.items) {
            if (thing instanceof Sword && ((Sword)thing).isTaken()) {
                //this.items.remove(thing);
                newroom.items.add(0, thing); 
            }
        }
```

**Comment by aaron-ljx** [comment]
> 
> 
> @jerimiglo
> I tried to remove the sword from from the old room but not sure why it wasn't possible in the loop, they gave me an error saying concurrent modification exception
> 
> ```
>        for (Thing thing: this.items) {
>             if (thing instanceof Sword && ((Sword)thing).isTaken()) {
>                 //this.items.remove(thing);
>                 newroom.items.add(0, thing); 
>             }
>         }
> ```

One way to prevent the error is that you can create a copy of your old room, then loop through the original copy of your old room and remove the sword from the created copy of your old room then continue to use the created copy in your code.

**Comment by jerimiglo** [comment]
yes, this is because you can't modify the list while iterating through it! You can try the method stated above^ it should work! Good luck!

**Comment by dtse2401** [comment]
> @jerimiglo
> I tried to remove the sword from from the old room but not sure why it wasn't possible in the loop, they gave me an error saying concurrent modification exception
> 
> ```
>        for (Thing thing: this.items) {
>             if (thing instanceof Sword && ((Sword)thing).isTaken()) {
>                 //this.items.remove(thing);
>                 newroom.items.add(0, thing); 
>             }
>         }
> ```

@enqiilim I've had this issue as well. It stems from removing any objects from a list while iterating through it. I simply created a new arraylist and iterated through the current list and added the sword to the new arraylist. After that, you can call arraylist.removeAll method, which takes in a list as the parameter.

**Comment by ErnestCYW** [comment]
Alternatively, if you wanna save some lines of code and not use the for loop so you don't modify as much, you can try using the list constructor passing in the old list:

List<Thing> newList = new ArrayList<>(oldList);

Also, I remember that using add and remove functions on the newList would fail some hidden test case (Or at least I did). If you encounter that try using set instead. Hope this helps :)
