### ISSUE TITLE
jar command Lab08

### ISSUE THREAD

**Issue by banchiang** [nus-cs2030/2021-s1#322]
![image](https://user-images.githubusercontent.com/72375578/98946586-086d3f00-252f-11eb-9d4c-cc2a204af780.png)

Hi sorry newbie here I'm simply following the commands from lab08  but I'm getting an error of jar not recognized as external or internal command. Looked up the web and couldn't find any satisfactory solution. Anyone knows how to solve this easily?

**Comment by SkyBlaise99** [comment]
Try [this](https://stackoverflow.com/questions/29180639/java-jar-is-not-recognized-as-an-internal-or-external-command#:~:text=Five%20steps%20to%20solve%20this,exe%20is%20availbale%20or%20not&text=now%20check%20for%20jar%20it,the%20command%20jar%20xf%20filename.)?
