### ISSUE TITLE
PE2 Test Case 6

### ISSUE THREAD

**Issue by kaushikkrdy** [nus-cs2030/2021-s1#323]
Hi does anyone know what's happening here? This seems to be a hidden test case so I don't know what the issue is. Anyone else face the same issue? Thanks!

<img width="575" alt="Screenshot 2020-11-12 at 9 49 45 PM" src="https://user-images.githubusercontent.com/70100131/98948203-1c19a500-2531-11eb-890f-b8234cf27c25.png">

**Comment by jerimiglo** [comment]
Remember to remove the sword from the original room (if the sword is taken) when you call go()!

**Comment by kaushikkrdy** [comment]
> Remember to remove the sword from the original room (if the sword is taken) when you call go()!

Yep that was the issue, thanks for the help!
