### ISSUE TITLE
PE test6.1

### ISSUE THREAD

**Issue by adelineT-jy** [nus-cs2030/2021-s1#326]
Hi, does anyone know what might have been the issue? 
Could it be because the candle has been moved from a room to another?

![image](https://user-images.githubusercontent.com/72067023/98976732-ade5da00-2552-11eb-9d09-5f7a101d7860.png)

**Comment by jiayi-lim** [comment]
Nope, I don't think the candle can be moved from a room to another! The problem should be in your back method. When there is no previous room, you should return the current room (this).

**Comment by hhhhanz** [comment]
Yea, seems like a back() issue. Might want to check that your back() method is working correctly

**Comment by charoi** [comment]
Did you make a `new ArrayList` when you used your back/go methods? You might have modified and brought along the list of items by accident.

**Comment by adelineT-jy** [comment]
@charoi No i didnt but I used a new supplier. I will recheck my back() again. Thanks @jiayi-lim @hhhhanz @charoi for your suggestion!
