### ISSUE TITLE
Project 2 test JSH files

### ISSUE THREAD

**Issue by TarciusW** [nus-cs2030/2021-s1#328]
Hello, anybody have Project 2 jsh test files? if not I'll make them n upload them over the weekend!

**Comment by SkyBlaise99** [comment]
Only got level 1 to 2
[File.zip](https://github.com/nus-cs2030/2021-s1/files/5537780/File.zip)

**Comment by amandalim857** [comment]
> Hello, anybody have Project 2 jsh test files? if not I'll make them n upload them over the weekend!

Just curious if u have uploaded it yet?
Cant find it anywhere lol

**Comment by SkyBlaise99** [comment]
@amandalim857 click the file.zip link

**Comment by TarciusW** [comment]
> > Hello, anybody have Project 2 jsh test files? if not I'll make them n upload them over the weekend!
> 
> Just curious if u have uploaded it yet?
> Cant find it anywhere lol

One guy responded with the zip file! But i havent got around to opening it yet

**Comment by TarciusW** [comment]
> Only got level 1 to 2
> [File.zip](https://github.com/nus-cs2030/2021-s1/files/5537780/File.zip)

thanks for this! will be closing now.
