### ISSUE TITLE
Is is possible to import packages in .jsh file to use ArrayList?

### ISSUE THREAD

**Issue by LapisRaider** [nus-cs2030/2021-s1#33]
I was just wondering if it's possible to use import packages into .jsh files to use certain things like ArrayList. I've tried to put in ArrayList and even put in 'import java.util.ArrayList' into the file, however when I try to run it, I got errors about how the variables aren't declared and the .Add() function from ArrayList is not declared.

Thus, I'm wondering if it is possible to import packages like ArrayList and use them in .jsh files.

**Comment by pchunky** [comment]
Everything is "already imported" in jshell. You can just create a new ArrayList in jshell without imports. Every java package is available there.

**Comment by LapisRaider** [comment]
> Everything is "already imported" in jshell. You can just create a new ArrayList in jshell without imports. Every java package is available there.

Ah okay, that's cool, I didn't know that, thank you! 

I also managed to get my code working, turns out there were some syntax errors that I didn't notice, one tiny spelling error xd. I ended up removing the import line too in my .jsh file after reading your advice and everything runs fine! Thank you so much!
