### ISSUE TITLE
Pe2 6_1 errors

### ISSUE THREAD

**Issue by enqiilim** [nus-cs2030/2021-s1#333]
Getting this error for the last part of the PE, not very sure why 
![image](https://user-images.githubusercontent.com/65434451/99037316-71e85e80-25be-11eb-955a-c1f5ba35b0ad.png)

**Comment by srj31** [comment]
Room q initially has no previous rooms, so if you try to back by using ArrayList make sure the index does not become -1.

**Comment by enqiilim** [comment]
ohhh ok i see, thank you!
