### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#334]
# Description 
Hi, I am having some issues with the output but I'm too sure which part of my code is wrong. Does the following output suggest that my Function<Shop, Pair<Shop, Event>> in the various event classes are wrong? Thanks in advance!

## Screenshots (if any): 
<img width="525" alt="cs2030p2 #3" src="https://user-images.githubusercontent.com/71959340/99040327-e7a2f900-25c3-11eb-8ad5-fd99d2266925.png">

**Comment by bwangpj** [comment]
You should probably check that you are getting the right service time for each customer and that every time a new event is produced, its event time is calculated correctly.
Also, your event outputs are not ordered by time!

**Comment by weiyifei-evelyn** [comment]
Please include the EventComparator that you have done for Project Part 1.
Also, please consider whether the time saved in each Event is correctly computed.

**Comment by SkyBlaise99** [comment]
I'm more interested in the `-0.000` you output... Might wanna check on that

**Comment by YuFeng0930** [comment]
Hi, 
I think the first thing you need to do is to make sure that your PriortyQueue functions correctly so that your event time will be in order. Consider the code below (copy from CodeCrunch). 
```
while (!pq.isEmpty()) {
	Event e;
	e = pq.poll();
	System.out.println(e);
	Event nextEvent = e.execute();
	if (nextEvent.isValidEvent()) {
		pq.add(nextEvent);
	} 
}
```
With this while loop and a correct event comparator for the PriortyQueue, your event time will in order.

**Comment by jiehuixx** [comment]
Hi i'm abit confuse, how do we exactly pass the random generator to the serve event? is the only way through the constructor? because based on level 2, it seems like arrive event should only take in a customer

**Comment by SkyBlaise99** [comment]
That will work, but may not be the only way

**Comment by YuFeng0930** [comment]
Try to think Lazy, like Supplier or sth. And you can always have multiple overloaded constructors.

**Comment by Jcheez** [comment]
Hi, since every customer is tied to a particular event, u can try passing the RandomGenerator(rng) into the customer. So when you are initializing customers in Main, u can pass in the rng from there. However, random service time should be lazy, therefore, try to use lambda functions.

Hope this helps

**Comment by cnlinh** [comment]
You should have a Supplier<Double> inside your Customer class. When you create a new Customer, you can simply parse in `() -> rg.genServiceTime()` and make sure you call `get()` only once before each of them is served.
