### ISSUE TITLE
Project 2 Level 4

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#336]
Hi, im currently facing the issue that when i reschedule the WaitEvent, it gets printed out once more in my priorityqueue and i have been stuck here for awhile. Can someone help me understand how i can overcome this repeat? (see last 5 lines where 10 waits to be served gets printed again)

Also, how do i take in 5 args for level 3 and 6 for level 4? Im having trouble getting the values needed to be initialized in my main to test both levels.

![image](https://user-images.githubusercontent.com/70895902/99058283-f398b600-25d7-11eb-9c70-a43cff252181.png) ![image](https://user-images.githubusercontent.com/70895902/99058316-fe534b00-25d7-11eb-8c77-1208c3d026cd.png)

**Comment by bryanwee023** [comment]
To avoid rescheduling WaitEvents, I have a MoveUpEvent that prints nothing. MoveUpEvent will keep track of the customer's position in the queue.

To deal with varying argument lengths, I created a new class ArgumentHandler that takes in the string[ ] args and depending on the length of the argument array, parses it into the correct variables

**Comment by kohwenjie** [comment]
@bryanwee023 sorry but could you explain a little more on the ArgumentHandler class, would it be used to simulate the events as well? im abit confused as to how i can implement it well.

**Comment by kohwenjie** [comment]
@bryanwee023 actually i figured it out thx dude!
