### ISSUE TITLE
Project 2 Test 4_2

### ISSUE THREAD

**Issue by kaiyang96** [nus-cs2030/2021-s1#338]
Anyone have any idea how this could have happened? The red rectangle shows that the events were flipped in the priorityqueue, possibly hinting to some error in the comparator. But the blue rectangle shows that its working properly, just for different Customer IDs. I have no idea where to start looking :( 
![image](https://user-images.githubusercontent.com/71059104/99060324-cef20d80-25da-11eb-8402-4fa70ab3a9f0.png)

**Comment by marcuspeh** [comment]
Probs cuz of precision error or your comparator never sort according to event in case of same time

**Comment by bryanwee023** [comment]
If I'm not wrong, PriorityQueue sorts in a way where if 2 objects are equivalent, the order is untouched (i.e. the order is the order the events were added into the queue). If you want to correctly order the events, maybe in compareTo, if timing is equal, compare the customer ids?
