### ISSUE TITLE
Project 2 Test 5_10

### ISSUE THREAD

**Issue by CWei88** [nus-cs2030/2021-s1#339]
# Description 
Hi, I need help passing test 5_10 for Project 10. I understand that for some reason after customer 3 starts being served, Server 1 still remains as available despite it being available should be false when Customer 15 comes. I had checked my ServeEvent to ensure that the Server is already set to unavailable when it is served and the Server will be updated in the Shop.

However, no matter how I try to look at my code or test different values for my test runs, I am unable to replicate this error. Can somebody help me clue in on why this error occurs? Thanks.

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![Code](https://user-images.githubusercontent.com/64974354/99061256-3f4d5e80-25dc-11eb-9158-bc7786a09b16.PNG)

**Comment by bryanwee023** [comment]
Level 5 tests for resting servers. The discrepancy could be because your Server is not properly resting. Maybe have a look at your ServerRestEvent again?

**Comment by tanruiquan** [comment]
Also, take a look at your eventComparator, maybe your serverRest and serverBack is not executed before serveEvent?

**Comment by colintkn** [comment]
I fixed mine by ranking serverRest and serverBacks as higher priority than any other events in the PQ.

**Comment by CWei88** [comment]
@bryanwee023 it was indeed the ServerRest event. Thanks!
