### ISSUE TITLE
Lab 6 Level 5

### ISSUE THREAD

**Issue by roopaniedu** [nus-cs2030/2021-s1#344]
I managed to get the sum() functions working with the correct output, but my f() does not have the correct output when I printlog for f(16)

![image](https://user-images.githubusercontent.com/66832279/99083021-e42d6300-25ff-11eb-8983-5f990e227ee7.png)

My code for the elseif :

`return f(newLogger.map(x -> x/2 ).getValue());`

**Comment by domlimm** [comment]
Hi, for function `f` you've to make use of your `flatMap` method to retrieve all the changes/unchanged statements.

Hint: Chain your `map & flatMap` in a way whereby `map` performs the operation, `flatMap` completes and sums the entire operation.

**Comment by jiayi-lim** [comment]
I personally didn't use flatmap! I modified the given code by changing all operations to be done using map. I think the problem you have is storing all the logs in between. How I solved that problem is by initialising a variable to be `Logger<Integer> `and I constantly re-initialize this variable when I perform map. At the end of the day, I will return this variable. 

For example: 
`ans = ans.map(x -> x/2); ` 

Hope this helps!

**Comment by hengyiqun** [comment]
I used map instead of flatmap too. 

I remember encountering this issue too, as I returned Logger.make(1) during my recursion. 
Returning the current Logger resolved the issue for me.

**Comment by hengyiqun** [comment]
Also, remember that the Logger needs to keep a record after each operation. So each multiplication and addition needs to be recorded too instead of lumping them together.

**Comment by frisciliasultan** [comment]
Hi, just to offer another perspective, I chained map and flatMap together so that the logs are handled by the map and flatMap. Just like what @domsterthebot says. So you might want to consider making a new Logger, map it accordingly and flatMap the result of the recursion. 
Hope this helps!

**Comment by cnlinh** [comment]
For me, after performing each step of the function, I compare the list of logs of the two Logger and add any log that is different (except the initialization).

**Comment by limyingying2000** [comment]
Hello! I used a combination of chained flatmap and map, and recursion to get it working!! For me, I followed the logic and structure of the given f() code in the qn but changed the return method such that it returned a new Logger with the help of map and flatmap!

**Comment by descentbw** [comment]
For me, I made up of a while loop, with if or else conditions in them, both of which will call a map function.

**Comment by jeremybrett4869** [comment]
Hi, for f(), I use a while loop and I call map function to update the output value for each step until it reaches 1. 
(Also, 3 * n + 1 should be separated into two parts 3 * n and + 1.)
