### ISSUE TITLE
PE 2 Level 5

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#347]
I'm getting this weird error where I get a lot of "You have taken sword." outputs.

<img width="948" alt="2020-11-14 (3)" src="https://user-images.githubusercontent.com/72072042/99107313-98d77c80-2620-11eb-9913-9cffe765c67c.png">

I managed to pass all test cases with takeSword up until this last part of the level 5 public test case. I'm completely stumped as to why this is the case. My takeSword method essentially checks for whether Sword is taken and prints the output accordingly. But since takeSword is only called once here, why should it be printing 5 times? 

-Oh, I also edited the final test case line to make it one whole line in an attempt to help myself understand, but either way still couldn't figure it out

**Comment by domlimm** [comment]
Hello! The only way `--> You have taken sword.` comes out is from your `takeSword` method. Hmmm... May I ask how you declared your `takeSword`? 

I suppose it returns a `Room`?

Have you taken into account the updating of whether a Sword has been taken too?

**Comment by dljw98** [comment]
> Hello! The only way `--> You have taken sword.` comes out is from your `takeSword` method. Hmmm... May I ask how you declared your `takeSword`?
> 
> I suppose it returns a `Room`?
> 
> Have you taken into account the updating of whether a Sword has been taken too?

Yes, my takeSword is a Function<Room, Room>
Basically my takeSword checks if my Sword has been taken, and if it hasn't been taken yet, then it prints out "You have taken Sword." followed by returning a new Room with a Sword that is now set to taken

**Comment by jiayi-lim** [comment]
It seems like after you run takeSword(), every time you chain a method, it prints out once more! It got printed out 5 times likely cause of the tick(takeSword), go, add, add, tick methods.

**Comment by jiayi-lim** [comment]
I am not sure why chaining will run it again though, how did you do the printing?

**Comment by dljw98** [comment]
> I am not sure why chaining will run it again though, how did you do the printing?

I finally figured it out. The problem was in my return statement, where I was using "return new Room(f.apply(this).getCandle(), f.apply(this).get ............);"
Since f.apply(this) will print out the takeSword string each time it is called, my return statement was actually the one repeatedly printing out the strings. Thank you all for your help!

**Comment by weiyifei-evelyn** [comment]
> > I am not sure why chaining will run it again though, how did you do the printing?
> 
> I finally figured it out. The problem was in my return statement, where I was using "return new Room(f.apply(this).getCandle(), f.apply(this).get ............);"
> Since f.apply(this) will print out the takeSword string each time it is called, my return statement was actually the one repeatedly printing out the strings. Thank you all for your help!

Hi, sorry for asking about it after you have closed the question. I have a similar issue as you. How do you solve it in the end?
