### ISSUE TITLE
How to call or check methods from .jsh file?

### ISSUE THREAD

**Issue by jeffreytjs** [nus-cs2030/2021-s1#349]
# Description 
If I wrote some methods in a .jsh file, how can I call it from a .java file? I can't seem to import the file in or even even check if the method exist.

Edit:
Specifically, I am trying to write method taking in lambda expressions, how to call the method I wrote in .jsh file?

## Topic: 
General

**Comment by CheongYeeMing** [comment]
I assume you're trying to test your code in jshell? Make sure both the .jsh and .java files are in the same directory. Open both files in jshell to test! You cannot /open the .jsh file alone if it is dependent on other classes. Eg if your method A in .jsh file depends on the class B, then you need to /open B.java before /open A.jsh. Not too sure if you're referring to this...

**Comment by jeffreytjs** [comment]
Hi @CheongYeeMing, thanks for the response.

I am trying to write a method that takes in lambda expression in a .java file, and that method is somehow suppose to call a method that is written in .jsh file. In this case I'm trying to call methods from actions.jsh of PE2.

**Comment by tien87chun** [comment]
@jeffreytjs

**Comment by tien87chun** [comment]
@jeffreytjs 
If you are calling methods from a .java file I assume that it should be a method under a particular class? In that case your method in actions.jsh should take in the class e.g. take in a `Room` as the argument before you can call `Room :: method`. If you do not put it in as an argument the function in actions.jsh will not be able to "see" the class and its methods in the .java file. Not sure if this is what you mean! If not you may wanna take a snapshot of the issue you are facing and put it up here?

**Comment by jeffreytjs** [comment]
Hi @tien87chun, let me try to get the screenshots.

Your explanation makes sense but I can't seem to figure how the method in action.jsh can take in `Room` class.
Let's say I have written methods in a .jsh file (probably incorrect since I did not take in `Room`)
![image](https://user-images.githubusercontent.com/19368296/99142017-f6ed7980-268b-11eb-9ce5-b3a9db114ac1.png)

But now I want to check and then call upon the `takeSword` method that is written in .jsh file.
![image](https://user-images.githubusercontent.com/19368296/99142069-754a1b80-268c-11eb-9cba-016d7970806a.png)

I might be getting the whole concept wrong so do let me know if these don't make any sense at all.

**Comment by cnlinh** [comment]
You should declare takeSword as a Function<Room, Room> instead of as a public method. From the test cases, they use it as someRoom.tick(takeSword) so imagine takeSword as a variable.

**Comment by Jcheez** [comment]
Hi, you might want to try replacing takesword as a variable instead. you can do this by writing the following in the .jsh file 

Example:
UnaryOperator< Room > takeSword = x -> {}

you can then write your logic in the curly braces. Hope this helps!

**Comment by joannecya** [comment]
Hi! I'm not sure if this is related but I'm also facing some errors in the jsh file for takeSword. 
In my case, I keep getting this error and I'm not sure how to solve it:
![image](https://user-images.githubusercontent.com/69726697/99142778-471c0a00-2693-11eb-9023-c481035a98ca.png)

below is a part of my code for takeSword, just to check if the format is correct!
![image](https://user-images.githubusercontent.com/69726697/99142859-fbb62b80-2693-11eb-9c2a-7ac863d7e9c5.png)

oh ps i found the error! the 's' in stream is supposed lowercase :").
@CheongYeeMing thks for your reply!

**Comment by CheongYeeMing** [comment]
Take into consideration what should be the return value for your functions in actions.jsh.

**Comment by tien87chun** [comment]
@jeffreytjs 
What @cnlinh and @Jcheez said are right. Your `takeSword` should not be a method in `Room`, it can but is not limited to being an independent Function<Room, Room> in actions.jsh

**Comment by jeffreytjs** [comment]
I've somehow got the .jsh component to compile without error, but I don't get how is the overloaded method suppose to call upon the variable `takeSword`? It's probably a small tweak to the overloaded method but 

![image](https://user-images.githubusercontent.com/19368296/99144725-3bd0da80-26a3-11eb-9b7a-a5ddd8930faa.png)

Edit:
Is it by using .apply()?
This works even though I get an error saying unchecked cast.
![image](https://user-images.githubusercontent.com/19368296/99145266-5063a180-26a8-11eb-8f65-192f3e602ed3.png)

**Comment by joannecya** [comment]
takeSword is an input taken inside actions.jsh so i don't think it should be inside the overloaded tick method in Room. 
The apply method should be correct. For me, I used apply then use forEach() to update the list of items in a new list then return a new Room with the updated items like the first tick() mtd

I'm not sure abt your mtd but mine is quite similar to the first tick() just that there is an additional apply()

hope this helps you!

**Comment by jeffreytjs** [comment]
Hmmmm... If i make the `action` return like a list, can I use like `List<> newElementList = action.apply(whatever arguments I take in for action)` in the `tick` method?

**Comment by ErnestCYW** [comment]
TakeSword is a function so it depends on what you want takeSword to return you. It can be a unary operator/ function that takes in a room/list and returns you a list (like you described) or even a whole room. You then need to return this in your tick method. Also is it necessary for your current implementation to use T since you already know that you are going to pass in a List to action? So maybe you can avoid the unchecked cast thing.

> Hmmmm... If i make the `action` return like a list, can I use like `List<> newElementList = action.apply(whatever arguments I take in for action)` in the `tick` method?

I think this is possible, then you can use your tick method to return you a room. But I purposely tied to avoid using generics since we already know what we going to pass in. something like UnarayOperator\<List> or Function<List, List>.

JY finish it by tmr :)

**Comment by ErnestCYW** [comment]
Oh btw I think in one of the hidden test cases they will check if you modify the previous rooms stuff when creating a new room. So if your tick method now takes in the current rooms list and modifies that for use in the new room then its wrong. If you encounter that like me (like level 3 or smth) all you need to do is just create an exact copy of the current list List\<X> newLIst = new ArrayLIst<>(oldList); and apply action on that.

If you don't encounter this then ignore my comment hahahahaha.

**Comment by jeffreytjs** [comment]
Thank you @cnlinh and @Jcheez for being explicit in your examples, they really helped as I was trying to get the .jsh file to work. And @joannecya, your comment helped and it's good to have some confirmation that I'm working in the right direction!

Last but not least, thank you so much @ErnestCYW. After reading through your explanation everything that the others shared just clicked. I've been stuck at level 3 for the longest time and really thankful for all of you that take time to answer our many question marks. Hahaha trying hard to finish, doubt I can do it without you guys helping with the concepts. It's hard to find specific examples online to cross-apply. Thanks again!
