### ISSUE TITLE
Project 2 Cyclic Dependencies

### ISSUE THREAD

**Issue by charoi** [nus-cs2030/2021-s1#354]
# Description 
Cyclic Dependency encountered on CodeCrunch

Hi there,
I was wondering why my classes have cyclic dependency on codecrunch? I don't think my ServeEvent and ArriveEvent referenced each other... 
![1](https://user-images.githubusercontent.com/41200981/99145870-5314c580-26ad-11eb-81ba-698c98c4e78e.png)

**Comment by JedrekLoo** [comment]
I believe your ServeEvent and ServeLater events are causing this cyclic dependency, this could be due to your serveEvent returning a serveLater event and serveLater event returning a serveEvent as well.

**Comment by charoi** [comment]
oop ok i just realised that... thanks!
