### ISSUE TITLE
PE2 Level 6

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#356]
Hi guys, for level 6 of the PE, i cant seem to go back after i called tick() on the rooms anyone faced the same issue and might have an explanation? Thanks in advance!

![image](https://user-images.githubusercontent.com/62513460/99146726-a428b780-26b5-11eb-81f5-c3c4c683eaba.png)

**Comment by marcusleejw** [comment]
hi! for levels 5 and 6, I had to add extra Room constructors to store the prev room. Maybe you could look into a similar implementation if you havent done so!

**Comment by kohkenneth** [comment]
@marcusleejw ohhhh thanks for your help! I forgot to update the constructor used in the tick function. Thanks!!
