### ISSUE TITLE
Project test case 3_1

### ISSUE THREAD

**Issue by limeugene** [nus-cs2030/2021-s1#358]
Hi, does anyone know why this error is being thrown in the hidden test case 3_1?
![image](https://user-images.githubusercontent.com/4206908/99147989-228a5700-26c0-11eb-8a11-be2367f70efa.png)

**Comment by bryanwee023** [comment]
Gonna need more information to debug man. Maybe share your Main's line 39? Seems like this error is thrown because a Scanner called `next()` without checking for `hasNext()`. Level 3 onwards, the inputs have varying lengths, so gotta accommodate for that.

**Comment by rezlite** [comment]
Try using String [] args and parsing the values.

**Comment by b-leong** [comment]
Those will be `Integer.parseInt()` and `Double.parseDouble() ` where you could pass the index of args into the brackets and also you need to account for varied number of inputs that changes the index for later levels

**Comment by limeugene** [comment]
Thanks all! Did not notice that the number of command-line inputs changes in subsequent levels. Parsed the values according to the number of inputs and it worked.

**Comment by limyapkai** [comment]
> Thanks all! Did not notice that the number of command-line inputs changes in subsequent levels. Parsed the values according to the number of inputs and it worked.

hi ! Can i ask how u implemented it? Thank you :) I don't quite catch the hasNext(). But I know other levels have more inputs. how does it affect testcase 3_1 hmm

![image](https://user-images.githubusercontent.com/27536739/99624273-f3ca0300-2a68-11eb-9295-304586f8576c.png)
