### ISSUE TITLE
Do computation before super() in the constructor (BigCruise)

### ISSUE THREAD

**Issue by HolmesJJ** [nus-cs2030/2021-s1#36]
May I please know what should I do if I want to do some calculations or conditional judgments on a and b before I call super? Thank you!

```
class A extends B {
    public A(int a, int b) {
        // do some calculations or conditional judgments
        super(a, b);
    }
}

class B {
    public B(int a, int b) {

    }
}
```

**Comment by pchunky** [comment]
Either use a factory method, or do the actual calculations in the super expression itself (if it will be evaluated and parsed to the super constructor).

**Comment by HolmesJJ** [comment]
> Either use a factory method, or do the actual calculations in the super expression itself (if it will be evaluated and parsed to the super constructor).

Hi, Phillmont Muktar,
I really appreciate that you can reply me.
For the factory method, could you please share a simple example?
Thank you!

**Comment by HolmesJJ** [comment]
I have found the solutions for this issue.

Solution 1:
```
public class A {

    private int x;
    private int y;

    public A(int x, int y) {
        this.x = x;
        this.y = y;
    }
}

class B extends A {

    public B(int x, int y) {
        super(x + 1, y + 1);
    }
}
```

Solution 2:
```
public class A {

    private int x;
    private int y;

    public A(int x, int y) {
        this.x = x;
        this.y = y;
    }
}

class B extends A {

    public B(int x, int y) {
        super(calculateX(x), calculateY(y));
    }

    private static int calculateX(int x) {
        return x + 1;
    }

    private static int calculateY(int y) {
        return y + 1;
    }
}
```
