### ISSUE TITLE
Project 2 Level 5

### ISSUE THREAD

**Issue by KaushikR1999** [nus-cs2030/2021-s1#360]
# Description
Hi, so currently I'm stuck in working out Level 5 of Project 2. My implementation of the genRandomRest() to check if a server should rest is to store the method in a supplier [ rngRestProb = () -> rng.genRandomRest() ] which will then be called in my DoneEvent after a server is done serving. I realised that my output isn't what it's supposed to be because the servers go to rest at the wrong timings, and that's because my supplier output to compare against the probability of resting isn't right. I’ve printed out the random value (supplier output) and the times at which the servers are going to rest/coming back (ServerRest & ServerBack events). Could anyone help me figure out why my supplier output may not be right? Anyone else facing the same issue? Thanks in advance!
<img width="514" alt="Project 2 Level 5 Output" src="https://user-images.githubusercontent.com/58514719/99150253-1dcc9f80-26ce-11eb-898a-61977b1cbd6e.png">

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by YuFeng0930** [comment]
These are the first ten value of resting probability.
0.73, 0.07, 0.07, 0.77, 0.23, 0.66, 0.81, 0.03, 0.81, 0.95
It seems that your output of probability of resting are correct.

These are the first ten value of resting period.
3.14, 0.85, 0.85, 3.86, 25.46, 36.96, 3.58, 2.17, 18.89, 0.78 
Your output for this part seems wrong. The value of resting period is generated only after the server are to rest (the resting probability < the resting criteria). Other than that, you cannot get from the Supplier.

**Comment by KaushikR1999** [comment]
Hi, thanks for the quick reply! So will it make a difference if I calculate the restPeriod before calling my ServerRest Event? Because my current implementation is to change the nextAvailableTime of the server who's resting by calculating the restPeriod in the DoneEvent itself. (I do only calculate the restingPeriod by calling on the Supplier IF the resting probability < resting criteria) Then I change the time of the event itself only when I call my ServerBack event from my ServerRest event. Thanks :)

**Comment by YuFeng0930** [comment]
It's fine to get the restPeriod in the DoneEvent, and I did that also. But your resting period in the screenshot above is 3.56, 2.76, 4.99 (in order). These three numbers cannot be found in the list of first ten resting period in my last comment. Maybe you can try to print out the first ten value of resting period somewhere else to check that your RandomGenerator functions correctly.

**Comment by KaushikR1999** [comment]
Hey @YuFeng0930 thanks man, hahaha I printed out my restPeriods and found out that they were in fact correct and the problem instead was that i was double counting them by adding it once in the Event itself and once while updating my server hahaha. Thanks a lot for your help in helping me figure things out and solve Level 5 👍
