### ISSUE TITLE
PE 2 test4_1

### ISSUE THREAD

**Issue by sdas04** [nus-cs2030/2021-s1#361]
Hi, am able to pass the public test cases but can't figure out the reason behind this error. Is the issue with my "--> Troll is killed." instance in killTroll? Thanks!
<img width="448" alt="Screenshot 2020-11-14 at 11 13 27 PM" src="https://user-images.githubusercontent.com/57550598/99150486-e7901f80-26cf-11eb-91d2-e7dc2a93cb49.png">

**Comment by YuFeng0930** [comment]
Hi, 
Do you change the order of item list in killTroll? killTroll should only delete the Troll (if killed), instead of changing the order of Sword.

**Comment by wongzw** [comment]
Hi!

Make sure you check on whether the order of your list items are being changed when you remove the Troll. You should also take note of immutability so make sure you ensure immutability is maintained :)

**Comment by sdas04** [comment]
Hi, I'm currently looping through the list of items in the existing room and adding them to the list of items in the new room as long as !(item instanceof Troll). I don't think that should affect the order of the items? :(

**Comment by limyingying2000** [comment]
Not too sure if it is the same issue, but it might be the order in which you add ur sword into the list. You can try to use (list of items in the new room).add(0, new Sword(..)) with the index for your go method. It works for me, hope it helps you too!!

**Comment by glennljs** [comment]
Since this is test case 4_1, I don't think it covers the `go()` method yet right. Could it be something to do with the way you check for a Sword to determine if you can kill the Troll?

**Comment by jiayi-lim** [comment]
Make sure you are adding the item that is !(item instanceof Troll) to the back of your list! Problem is likely from killTroll or takeSword so maybe you want to check through the parts where you did add() in the 2 methods.

**Comment by sdas04** [comment]
I finally realised that the issue was that I wasn't adding my updated sword at the correct index in my takeSword! Thank you all for your input :)
