### ISSUE TITLE
Test 4_4

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#364]
# Description 
Anyone found out the edge case for this one? Thanks in advance!
P.S., I only get() the supplier () -> rng.genServiceTime() when ServeEvent is called, so that shouldn't be a problem

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/61898858/99152646-f978bf00-26dd-11eb-8ab7-49cfbcdfe114.png)

**Comment by cnlinh** [comment]
It looks like the queue of server 1 is full? Maybe the queue limit is set wrongly?

**Comment by ghost** [comment]
Ahh made a minor mistake gotcha
