### ISSUE TITLE
Possible to write this in one line of code?

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#368]
Let say here is a method called change():

<img width="183" alt="Screenshot 2020-11-15 at 10 07 25 AM" src="https://user-images.githubusercontent.com/71199647/99161180-61ed8d80-272a-11eb-91c9-25e2d2742b95.png">

Is it possible to write this chunk of code into one line?

**Comment by glennljs** [comment]
It's possible to reduce but I don't really understand the function of your code, you don't seem to actually use/reference any of the objects in listOfA. Am I missing something?

**Comment by rohit0718** [comment]
`!listOfA.stream().noneMatch(pred)`

**Comment by weiyifei-evelyn** [comment]
> It's possible to reduce but I don't really understand the function of your code, you don't seem to actually use/reference any of the objects in listOfA. Am I missing something?

Sorry for the ambiguity. listOfA is just a list of Class A objects. So I'm trying to loop through the list to find whether there is any A object passing the predicate

**Comment by glennljs** [comment]
yup then @rohit0718's stream answer is good. 

Alternatively you can use `listOfA.stream().anyMatch(pred);`

**Comment by weiyifei-evelyn** [comment]
@rohit0718 @glennljs Thank you!
