### ISSUE TITLE
Project 2 Level 6

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#369]
For level 6, is there a need to redesign Server class in order to fit the self checkout? I've been trying this for awhile now and cant seem to get it to work. I tried to make self checkout extend my Server class so that the self checkout counters can be included in the shop's list of servers, but that only broke my WaitEvent class. Can someone point me in the right direction on how to implement for level 6?

**Comment by glennljs** [comment]
For good OOP design you should have an additional abstract class/interface which both Server and SelfCheckout extends.

Majority of the properties are identical except for Server having an ability to rest and SelfCheckout's utilizing the same queue. 

Hope this helps!

**Comment by Clem-cpu** [comment]
@glennljs when u say that selfcheckout utilises the same queue, does this mean that the queue of customers is stored in selfcheckout?

As of now I keep track of the queue length by using a static property, just wondering if this is feasible

**Comment by cnlinh** [comment]
@Clem-cpu yep I'm using the same implementation and it works also

**Comment by glennljs** [comment]
@Clem-cpu Yup. There are several ways to do it, namely using a static queue in the SelfCheckout class that all instances of it refer to or passing in the same queue you've initialized outside the class to all instances of it.

That's how I did it at least. Hope this helps!

**Comment by SkyBlaise99** [comment]
Yup, i had boolean `isSelfService` to decide whether the `Server` uses `int qCurrent` or `static int qCurrentShared`

**Comment by kohwenjie** [comment]
@SkyBlaise99 so it is possible to not have to include a whole new class for the selfcheckout servers. Thanks!

**Comment by merylseow** [comment]
Hi I am leaving this comment here because I face some problem with this too. So we don't have to create a new self checkout class but just need to create a queue object and add the self checkout in? So like mentioned above, self checkout shares the same queue as the other servers?

**Comment by chongweil907** [comment]
I had the same issue too :(

**Comment by kohwenjie** [comment]
@merylseow i managed to do it without creating a new class, so ye should be doable haha. the self checkout shares the same queue as the other self checkouts, not with the humans

**Comment by chongweil907** [comment]
@kohwenjie do u like increment the number of waiting customer in a shared queue for SSC ? As it is a static final variable, I am wondering how i could do that. Thanks in advance!

**Comment by kohwenjie** [comment]
@chongweil907 i didnt make it final, but i seem to have run into some cyclic dependency problem with my level 6 rn so i think might need a second opinion from someone who finished the whole project just in case its not suppose to be not final

**Comment by chongweil907** [comment]
@kohwenjie Thanks for the quick reply ! I am wondering if static member should be final ? 
Anyway all the best for the proj ! Been stuck at level 6 for quite sometime now :(

**Comment by kohwenjie** [comment]
@chongweil907 let me reopen this so maybe someone can hop in and help out. Yea i stuck here too
