### ISSUE TITLE
Setting alias for checkstyle

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#37]
Based on the checkstyle provided in the guides, we have to run the following command to check: 

java -jar ./checkstyle-8.2-all.jar -c ./cs2030_checks.xml [YOUR_JAVA_FILES]

Has anyone successfully set up an alias for checkstyle so that we only need to run the following:

checkstyle Point.java

**Comment by HolmesJJ** [comment]
Hi colintkn, May I know what is your OS? I am using MacBook. So my solution is:

1. Turn on Terminal
```
vim ~/.bash_profile
```

2. Add the command (You can modify the command base on your style)
```
alias checkstyle="java -jar /Users/YOUR_FILEPATH/checkstyle-8.2-all.jar -c /Users/YOUR_FILEPATH/cs2030_checks.xml *.java"
```

3. Activate your change
```
source ~/.bash_profile
```

4. Try the command
```
checkstyle
```

**Comment by colintkn** [comment]
Hi Jia Jun, thank you!  I'm using Catalina. I tried your approach. The command seems to be working... only that when I try to checkstyle for Cruise.java, it checks for Loader.java. Seems abit odd. Did u encounter this problem?

![image](https://user-images.githubusercontent.com/65516485/92307348-65e18e80-efc8-11ea-9c46-61c37b9d3e0e.png)

**Comment by pchunky** [comment]
You are invoking `checkstyle Cruise`. Try `checkstyle Cruise.java` instead.

**Comment by colintkn** [comment]
> You are invoking `checkstyle Cruise`. Try `checkstyle Cruise.java` instead.

**Comment by colintkn** [comment]
> You are invoking `checkstyle Cruise`. Try `checkstyle Cruise.java` instead.

Same problem.

**Comment by pchunky** [comment]
Ah, of course. I just checked the code snippet @HolmesJJ shared above. He shared in number 2:
```bash
alias checkstyle="java -jar /Users/YOUR_FILEPATH/checkstyle-8.2-all.jar -c /Users/YOUR_FILEPATH/cs2030_checks.xml *.java"
```
Notice the `*.java` at the end of the command? That is why if you set this as your `checkstyle` alias, every time you invoke `checkstyle` it is going to check for every single java file in cwd.

Change to this instead:
```bash
alias checkstyle="java -jar /Users/YOUR_FILEPATH/checkstyle-8.2-all.jar -c /Users/YOUR_FILEPATH/cs2030_checks.xml"
```
Then try running `checkstyle Cruise.java`.

**Comment by colintkn** [comment]
Great, now it works. thank you!
