### ISSUE TITLE
Project 2 Cyclic Dependencies 

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#370]
My current implementation of Event's execute checks the instanceof class calling it, and then redirects to the correct execute for the class, the 'correct' execute will return the next correct class, and this overall execute will return a Pair<Shop,? extends Event>. 

Obviously this will lead to some cyclic dependency between Event and all the other Events, but how else do you solve it?  

![image](https://user-images.githubusercontent.com/10182564/99162409-7f295880-2738-11eb-92d8-1f3e7b10fb84.png)

**Comment by marcuspeh** [comment]
You could use a enum to store the type of event instead of using instanceOf

**Comment by glennljs** [comment]
It seems that you are not using the constrained method of execute?

It was listed in the project specifications that the Event execute function should be defined as:

`final Pair<Shop, Event> execute(Shop shop) {
    return this.func.apply(shop); 
}`

In this way, your Event class's execute should just run the Function<Shop, Pair<Shop, Event>> that is passed into your constructor. Then, in each respective Event subclass, you define in the constructor a lambda/anonymous class that should be executed when u run the execute method. This lambda/anonymous class should be the one handling the logic behind each stage and then returning the subsequent Event.

Hope this helps!

**Comment by FergusMok** [comment]
Thanks alot @glennljs @marcuspeh , I missed out on that line, everything should work now.
