### ISSUE TITLE
PE2 test6_1

### ISSUE THREAD

**Issue by merylseow** [nus-cs2030/2021-s1#373]
Does anybody know what this ConcurrentModificationException error is about?
![Screenshot 2020-11-15 at 3 35 29 PM](https://user-images.githubusercontent.com/71954278/99179956-1ef8dd80-275d-11eb-8467-11537c5ee2e1.png)

**Comment by SkullPirateTK** [comment]
You cannot modify the list you are iterating through (using the list's iterator) except by using the iterator's provided methods.

**Comment by marcusleejw** [comment]
if you used enhanced for loop, you can look at this stackoverflow post for some info as to how to avoid the error

https://stackoverflow.com/questions/8104692/how-to-avoid-java-util-concurrentmodificationexception-when-iterating-through-an

**Comment by jiayi-lim** [comment]
I think u did something like this 
```
for (Item i: roomitems) {
    if (...) {
         roomitems.remove(i);
    }
} 
```

The error arises because you want to loop through the list but at the same time you are editing the list, so it cannot loop through it properly since it is changing!

**Comment by jiayi-lim** [comment]
If that is the problem, you can solve it by making a copy of that list! So you loop through one of them and you edit the other. 
```
List<Item> copy= new ArrayList<Item>(roomitems);
for (Item i: roomitems) {
    if (...) {
          copy.add(i);
    }
}
```

**Comment by limeugene** [comment]
Alternatively, if you only want to modify one particular element in the list, to save a few keystrokes, you can consider iterating through the list as per normal, then doing a "break" after you have modified it. For instance:
`for (Item i : roomitems) {
         if (...) {
                 roomitems.remove(i);
                 break;
        }
}`

Sorry not sure what's wrong with the formatting of the code

**Comment by merylseow** [comment]
Ok, I found out where my error is. Thanks everyone!
