### ISSUE TITLE
Adjust Brightness on Fedora

### ISSUE THREAD

**Issue by georgepwhuang** [nus-cs2030/2021-s1#375]
Does anyone know how to adjust the brightness of the LCD display when using Fedora, or have the same issue? I'm using a MacBook Pro, the brightness adjustment keys are unusable in Fedora, and the brightness seems to be locked on maximum. I'll probably blind myself with the Java API page during the exam.

**Comment by georgepwhuang** [comment]
BTW I tried accessing the LCD display through `xrandr` but the display can't be found.

**Comment by bentanjunrong** [comment]
Same for my windows laptop, I guess the drivers are just not installed. Don't think there's anything we can do about it 🤷

**Comment by eric-vader** [comment]
Unfortunately, some of the machine's brightness adjustments are driven by drivers. You can try to adjust using your keyboard in the browser. If it works, it works. If it doesn't then perhaps you can try using an external monitor or another machine if u have one!

**Comment by limeugene** [comment]
> Unfortunately, some of the machine's brightness adjustments are driven by drivers. You can try to adjust using your keyboard in the browser. If it works, it works. If it doesn't then perhaps you can try using an external monitor or another machine if u have one!

Hi, can I check if Fedora is supposed to work when we connect our laptop to an external monitor? I use a Macbook pro, and the browser doesn't seem to work for me when I use an external monitor. I have tried to adjust the font size but doesn't seem to work either.

![IMG_2410](https://user-images.githubusercontent.com/4206908/99670372-66f46900-2aab-11eb-837a-a16df5635a8f.jpg)

![IMG_2409](https://user-images.githubusercontent.com/4206908/99670356-6065f180-2aab-11eb-8d68-683ddbe798b8.jpg)
