### ISSUE TITLE
proj 2 level 2

### ISSUE THREAD

**Issue by jiexilim** [nus-cs2030/2021-s1#379]
Hi, would anyone be kind enough to give me some hints on how to write the `function` for `DoneEvent` for proj 2?
For my project 1, my `DoneEvent` and `LeaveEvent` don't have to `execute()` since I straight away update the `serverList` for ArrivalEvent. But for proj 2, `Shop` should not be updated when `ArriveEvent` is executed right, `Shop` can only be updated when `ServeEvent` is executed (if I am not mistaken), which means `DoneEvent` has to be executed in order to update the `Shop` (that server has done serving) right? But i have no idea what type of event should the `function` of `DoneEvent` return, like I cant make `function` to return `Pair.of(updatedShop, this)`, cuz `this` can't be called before 'super'.

**Comment by merylseow** [comment]
For me I returned `new Pair<Shop, Event>(updatedShop, null)`.

**Comment by ghost** [comment]
I have a new class called TerminationEvent(). The toString() method returns null, which I'll check for in the main class.
