### ISSUE TITLE
Proj level 6

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#381]
Just asking, does static member needs to be private final ? For my SSC, since it is a shared queue, 
I have a static member: numOfWaitingCustomer, so basically i increment it when a new customer arrives.
Just wondering if codecrunch will fail me.
Thanks in advance!

**Comment by rohit0718** [comment]
nope shdnt be an issue

**Comment by kohwenjie** [comment]
@chongweil907 yea dont need be final, i finally resolved my issue and code crunch seems to let me through using static so it should be fine

**Comment by chongweil907** [comment]
This means that I can have static method too right?
