### ISSUE TITLE
[Project 2] After Level 2, integrating into Project 1

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#382]
Hi, I'm facing an issue whereby my Shop isn't updated. Thus, only the `ArriveEvent, ServeEvent & DoneEvent` are being invoked, and not the other 2 Events.

I have used `Shop.replace(...)` in ServeEvent, WaitEvent and DoneEvent where I update the specific Server to the Customer accordingly. `replace(...)` returns a new Shop.

![image](https://user-images.githubusercontent.com/46486515/99193776-26000a00-27b6-11eb-8558-5b079fdd6f72.png)

Rightfully, everything should still work fine from Project 1 with this new implementation.

My flow for the Simulator is:

`Main` -> Initialises a Simulator object `new Simulator(numOfServers(for Shop to auto generate List of Servers), customers)`.
Also, `Main` starts the `Queue` by adding an `ArriveEvent` into the `Queue` with the very first `Customer` from the List of Customers.

Subsequently, `Simulator.simulateNextEvent()` pops the head of the `Queue` and then runs `execute` on it, and not adding the `Event` into the `Queue` if it's `Done` or `Leave`. This method returns an `Event` to be printed in `Main`.

As for the rest of the customers, I've made a method that adds an ArriveEvent with the Customer into the Queue.

```java
Event simulateNextEvent() { 
    eventHeadOfQueue.execute,
    addCustomer(...),
    addNewlyExecutedEventHead into Queue 
    returns NewlyExecutedEventHead to Main for printing the event;
}
```

That's roughly the flow.

Appreciate if anyone could help please... Been stuck on it for a day...

**Comment by CWei88** [comment]
You should look at the Shop that is passed through when 2 comes. Since 1 is being served when 2 arrives, the shop that should be passed through should be `[1 is busy, available at 1.500]` instead of `[1 is available]`. Take a look at why your shop isn't updated when both 2 arrives and 3 arrives, as you may not be passing the updated shop through them instead.

**Comment by e0420658** [comment]
always look for the updated server in the shop by using server identifier to retrieve it and then pass this updated server your necessary events

**Comment by domlimm** [comment]
Thanks guys! It has been resolved.
