### ISSUE TITLE
Lab 8 Level 1

### ISSUE THREAD

**Issue by merylseow** [nus-cs2030/2021-s1#383]
I tried running level 1 on jshell but I keep getting prompted with these errors. My code can pass on codecrunch though, so I'm not sure why I cannot run it locally on my computer. Does anybody know what to do?
![Screenshot 2020-11-16 at 11 38 47 AM](https://user-images.githubusercontent.com/71954278/99210413-b19e8880-2800-11eb-8f42-a04b6c539f70.png)

**Comment by rohit0718** [comment]
not sure why its not working but u can jus ignore it haha. as long as u passed the codecrunch 1/4 for the first part it shd be working

**Comment by bryanwee023** [comment]
Oh I had the same problem. I re-downloaded the jar file and it worked fine. Does anyone know why?

**Comment by descentbw** [comment]
Are your return types of all your methods in the BUS API CompletableFuture\<String\>?

**Comment by rohit0718** [comment]
> Are your return types of all your methods in the BUS API CompletableFuture\<String\>?
> 
> 

Yup

**Comment by waynetee** [comment]
the jar uf  command will update the class files in the jar, I suspect you have a lot of class files in the directory, so when you jar uf *.class, all the class files in the jar got updated. Try redownloading the jar file and using xxx.class instead of *.class
