### ISSUE TITLE
Project 2 Test5_10

### ISSUE THREAD

**Issue by jiehuixx** [nus-cs2030/2021-s1#384]
# Description 
Hi, I'm not too sure why the server didn't go to rest. Currently, I did not make any new events (ServerRest & ServerBack), I simply updated the server next available time if it decides to rest. Is this the problem? like do I actually have to make new events? Thanks!

## Screenshots (if any): 
<img width="401" alt="cs2030p2" src="https://user-images.githubusercontent.com/71959340/99215394-af8ef680-280d-11eb-8561-9513b3fa2a7f.png">

**Comment by CWei88** [comment]
Looking at the output, it seems like it's because of Server 1 not resting when it is supposed to rest. It may be due to your Server's availability. Did you ensure that the Server is unavailable when it rests and change it back to available once it finishes resting?

**Comment by Jcheez** [comment]
There might be some error with the new Server in your done event, which resulted in Server 1 serving Customer 4 when it is not supposed to. You should create the 2 new events so that your done event will not be so crowded with code.

**Comment by jiehuixx** [comment]
@CWei88 @Jcheez Hi, thanks for your suggestions but I still can't seem to solve it. Can I ask, do we update that the server is unavailable within serverRest itself?

**Comment by e0420658** [comment]
@jiehuixx yes update it to available = false, i did it in my done event and passed the new server along  to the serverRest event

**Comment by bryanwee023** [comment]
Another possible source of error is that even though you've correctly updated your Server's rest event, the queued ServeEvent is unaware of the change. Make sure to have ServeEvent get the updated Server's status before deciding whether it should `execute()` to return another ServeEvent at a later time or a DoneEvent.

**Comment by jiehuixx** [comment]
Hi, may I enquire, how should the priority queue be sorted given that we have serverback and serverrest now? I made these 2 new classes and I'm still getting the same error hahah..

**Comment by e0420658** [comment]
hmm there shouldnt be a need to change the current implementation of priority queue.. for your serverRest and back did u retrieve the updated server from the shop as well?

**Comment by jiehuixx** [comment]
@e0420658 yes I did :( but does that mean in your case, serverRest and back were not mentioned at all in your pq?

**Comment by e0420658** [comment]
you have to add these two events to the queue but there shouldnt be a need to change your priority queue comparator! sorry my previous comment could have been abit misleading!

**Comment by sharleneq** [comment]
Hey jiehuixx, I did not make any changes to the priority queue comparator too. The comparator for mine remains with comparing with the event timings and then customer ID. Perhaps you can check your serverback and severrest event timing are correct by printing them out? Or checking if your event sequence that you designed is the correct sequence.
