### ISSUE TITLE
Project 2 Level 6

### ISSUE THREAD

**Issue by Clem-cpu** [nus-cs2030/2021-s1#386]
Hi I am facing some problems of Cyclic dependency when i submit my code to codecrunch. Currently, I have a static List<Customer> queue in my SelfCheckout Class. Whenever there is a Done event served by the selfcheckout queue and the selfcheckout queue has customers, i return Pair.of(x, new Serve(nextCustomer......)). 

Is it possible to return a Serve Event from the Done Event, or does this introduce cyclic dependency and is not allowed.

Really can't think of any other way to make sure that the selfcheckout serves the correct next Customer. Any hints pls!

**Comment by chongweil907** [comment]
@Clem-cpu I dont think u can return a ServeEvent after DoneEvent if ur ServeEvent class return a DoneEvent.
I cant really offer u much help as I am stuck at level 6 too.

**Comment by Clem-cpu** [comment]
@chongweil907 was thinking if maybe from a Done Event u return a Wait event again but not sure if this causes cyclic dependency as well

**Comment by glennljs** [comment]
Hi @Clem-cpu I answered this question in a previous issue #363 you can check it out there hope it helps!

**Comment by Clem-cpu** [comment]
@glennljs ah omg thanks so much! Got it!
