### ISSUE TITLE
[Project 2] Level 3 - Accessing RandomGenerator

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#388]
Hi, I've taken a look at all the issues with regard to accessing the RG class.

I've seen 2 ways of doing it, i took the latter. The 1st way was to create another class to call `RG`.

```
Hierarchy:
Main
    - Simulator
    - Event, Event subclasses, etc
```
Here is what I've tried:
1. Remove all the `*.class` in `cs2030/simulator/` and add in the `RG.class` into `cs2030/simulator/`
2. All my `*.java` files have `package cs2030.simulator` at the top EXCEPT `Main.java`
3. Ran `javac -d . *.java`
4. `Main.java` has `import cs2030.simulator.RandomGenerator`

Issue: I tried to access RG from `Simulator.java` but it just cannot be found.

Appreciate any help, thanks guys!

**Comment by glennljs** [comment]
For me once I did steps 1 & 2 I simply ran `javac Main.java` in the Main directory. Compiling Main.java would compile its dependencies (Simulator.java) which then compiles their dependencies (Event, Event subclasses...). I then didn't have the compile issue.

I wrote the code into one line which you may use to quickly run test cases. First put RandomGenerator.class in your main directory then run:

`rm cs2030/simulator/*.class && cp RandomGenerator.class cs2030/simulator && javac Main.java`

Hope this helps!

**Comment by Jcheez** [comment]
Hi, did you input the following statement in Main.java. Since you are using SImulator.java to access RandomGenerator.class, you should insert: 

import cs2030.simulator.Simulator

Hope this helps!

**Comment by glennljs** [comment]
Yup @domsterthebot I think I forgot to mention previously. Since the methods in RandomGenerator are protected (only accessible within its package), all calls to RandomGenerator should be done in classes within cs2030.simulator (e.g. Simulator, Shop, Event etc).

Your Main class should ideally only be handling input/output (i.e. Parsing input and passing it to Simulator).

Thus your Main class should only depend on and `import cs2030.simulator.Simulator;`.

**Comment by domlimm** [comment]
Hello @glennljs & @Jcheez , apparently I was doing it correctly! Was using VScode and it was just showing that `RG cannot be resolved to a type`. My compiling worked from the start. Anyway, all fixed! Thank you both! 😄
