### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#390]
This isn't an explicit code debugging question, rather I am a bit confused as to whether I even understood the transition from level 2 - level 3 correctly. From what I understand, each call of execute(Shop shop) on ArriveEvent **in Level 2** does not change or update the Shop or any of the Server in the Shop, but just returns the same Shop with an updated Event as a Pair<Shop, Event> - is this correct? Which means that in Level 3, we are just repeatedly calling execute without ever changing the Shop or the true/false properties of each Server within the Shop, and instead just transitioning from one Event to another?

**Comment by eman-kom** [comment]
The Shop in the Pair is used to replace the old Shop kinda like "updating it"

**Comment by dljw98** [comment]
> The Shop in the Pair is used to replace the old Shop kinda like "updating it"

I see, so in the return for Pair<Shop, Event> , the Shop is being updated there? So for instance if I call execute(Shop shop) on an ArriveEvent, and the return is WaitEvent, then in the Shop it would reflect that the Server in the shop assigned to this WaitEvent is now (serverID, false, true, nextavailtime)?

**Comment by b-leong** [comment]
you would have to update the shop before returning a new pair in each execute, there is a method in Shop to help you do that
you can also retrieve the updated shop by using the `first()` method to store in a variable which u can subsequently use

**Comment by eman-kom** [comment]
yea kinda
uh i am assuming you are calling the execute in ur main. So it returns a Pair<Shop, Event> which pair.first() is used to update the main shop while pair.second() is used to transition to the next event

**Comment by dljw98** [comment]
Got it guys, thanks for all your help!
