### ISSUE TITLE
Lab8: BusRoutes not "combining"

### ISSUE THREAD

**Issue by jadenwjh** [nus-cs2030/2021-s1#391]
# Description 
Is there something wrong with my thenCombine? describeService return something, but not appended into result.
If I print the output of describeService (line 26), I can actually get the test case's desired output.

I suspect it has to do with line 31.

## Screenshots: 
![Screenshot 2020-11-16 at 8 35 03 PM](https://user-images.githubusercontent.com/62279469/99253143-36ae8f80-284b-11eb-9dbc-d21bccd4f9eb.png)

**Comment by rohit0718** [comment]
u need to remember to update ur `result` if not line 31 is lost as no variable references the new `CompletableFuture<String>` after the `thenCombine` finishes executing. here ur result u are returning is the original val from line 20.

**Comment by jadenwjh** [comment]
@rohit0718 i see... i did so by reassigning the variable and now it works. Was that what you meant? Thanks!

**Comment by rohit0718** [comment]
yup! `thenCombine` returns a new `CompletableFuture`

**Comment by jiexilim** [comment]
@jadenwjh hi may I know how u reassign `result` to update it? I tried `result = result....` I get an error saying `local variables referenced from a lambda expression must be final or effectively final`
`
