### ISSUE TITLE
[Project 2] Clarification of Customer Queues

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#392]
Hi, as for the implementation of Customer Queues, I would like if anyone could let me know if I'm in the right direction.

Similar to a realistic queue system, each counter = 1 queue, similar to 1 server = 1 queue?

The specified max length of the queue refers to the number of customer/s that are allowed in the server's queue to wait for the respective server?

We will still have the main priority queue or should it be scrapped off? I guess things have to be dynamic to pass the previous test cases, hence, we need to keep the main queue, or will it be used for this level too?

Thank you!

**Comment by lkldev** [comment]
Hi, yes, each server will have its own queue. This should not affect your main priority queue as it has nothing to do with your main priority queue. The customer queue is only used for the server to serve the next customer. The max queue length will be the maximum number of customer that can queue for each server. Do note that the customer being served is not considered to be in the queue. Hope this helps :)
