### ISSUE TITLE
Project 2 Level 5 Queue Design

### ISSUE THREAD

**Issue by Terrence-F** [nus-cs2030/2021-s1#394]
My code has been designed in such a way that upon an ArriveEvent, it detects if it will go into WaitEvent. If it does, the Serve and Done event will also be added to the event queue. 

However, this is may be an issue in level 5 as a SERVER_REST event will render the serve and done that has been added into the queue invalid (where it needs to be postponed). 

Will be good to hear some inputs as to what is the most efficient course of action from here on. 
1. Redesign queue for only WaitEvent to be generated (and not Serve and Done)
2. Find some way to postpone the Serve and Done Events

**Comment by Terrence-F** [comment]
Attempted to postpone the WaitEvent within the queue. Got myself into an infinite loop 
![Annotation 2020-11-17 014306](https://user-images.githubusercontent.com/65442533/99288267-4db6a700-2876-11eb-838e-7e1b45cad588.png)

**Comment by pikasean** [comment]
Personally, I would recommend you to use option one.

This is because once we ask a customer to wait, we are not sure when he will be served. This is due to server rest events and variable queue length in Project 2. Maybe you can think of another way to generate Serve events? :)

**Comment by bryanwee023** [comment]
I actually implemented a new subclass of Event that acts as the 'postponed version' of the WaitEvent. When generated in the Main loop, it should be designed not to print anything.

This new event can also act as the intermediary between Arrive and Serve. So it can check whether the Server is available (i.e. not resting) before generating a new Serve Event. So with this, there isn't a need to postpone ServeEvents.

**Comment by jerimiglo** [comment]
hey! i have the same implementation as you now (arrive ->wait->serve->done) and it works okay for level 5! what i did was to input a new serverRest event after done event to delay the start of serveEvent when the server is resting! Maybe you could consider this too!

**Comment by Terrence-F** [comment]
Thanks for all the feedback! :) Managed to complete level 5 using option 1.

Have tried option 2 also, but it makes the priorityqueue management rather messy.
Did not manage to complete using option 2. Though it definitely seems possible with some workaround as mentioned by @bryanwee023
