### ISSUE TITLE
Project 2 Level 3 Output

### ISSUE THREAD

**Issue by dljw98** [nus-cs2030/2021-s1#396]
I have this output error when I run Level 3: Whenever the event transitions from `ArriveEvent` -> `WaitEvent` -> `ServeEvent` -> `DoneEvent`, the time reflected in the `DoneEvent` is incorrect. However, when the event transitions from `ArriveEvent` -> `ServeEvent` -> `DoneEvent`, the time reflected is accurate. Despite this, my final calculation `[x y z]` is always correct. I store the rng in each customer, and use memoization to for the customer `serviceTime` values so its probably not an issue of me calling `genServiceTime` wrongly or repeatedly when I shouldn't have. I've taken a look at my `EventComparator` and I doubt the issue is arising from there since the events are output in the correct order (although I could be wrong). All I can think of is that my `WaitEvent `is causing some issue somehow (although it only directly affects `ServeEvent`, and `ServeEvent` outputs  `DoneEvent` correctly if a `WaitEvent` didn't come before it...).

For additional info, when I execute `WaitEvent`, my `ServeEvent` start time is when the `WaitEvent` 's server is next available to serve, and the `ServeEvent` end time is at the start time + customer `serviceTime`.

<img width="228" alt="2020-11-17 (2)" src="https://user-images.githubusercontent.com/72072042/99311958-5324e900-2898-11eb-9167-7d1f18588dac.png">
<img width="202" alt="2020-11-17 (4)" src="https://user-images.githubusercontent.com/72072042/99311981-59b36080-2898-11eb-9bfe-08b615a12481.png">

in the above, the issue only arises for customers 9 and 10, who have to go through a `WaitEvent`. Something that I noticed is that the time taken to serve customer 9 on my incorrect output is the same time taken to serve customer 10 on the correct output. But that would mean that I must have missed a call of `serviceTime` above customer 9, which would imply that my customer 8 and above should be wrong but the output seems correct...

below is from the codecrunch test case: as you can see, my `[x y z]` values are somehow still correct despite the incorrect `DoneEvent` time output for customers 3 and 4 (who are the ones who have to go through a `WaitEvent`).

![image](https://user-images.githubusercontent.com/72072042/99312391-f0801d00-2898-11eb-8259-cfa9390916d8.png)

Again, the time taken to serve customer 4 in codecrunch is exactly equal to the time taken to serve customer 3 in my own code. Does this mean that I must have missed a call of `serviceTime` somewhere in order to push my customer 3 `serviceTime` down to customer 4?

**Comment by waynetee** [comment]
are you calling genservicetime only when the customer is starting to be served?

**Comment by descentbw** [comment]
Have you passed ```genServiceTime()``` into the events lazily?

**Comment by dljw98** [comment]
> are you calling genservicetime only when the customer is starting to be served?

Yes, the only time I call it is in my serveevent, in order to calculate when the end time of the serveevent. Then I pass this end time into the serveevent function, so it will update the server when i call execute again

**Comment by dljw98** [comment]
> Have you passed `genServiceTime()` into the events lazily?

Yes. But I pass the rng into my customer (not the event itself) at the start, and only call the `genServicetime()` on the customer when the customer reaches serveevent. Should i instead update the customer with the rng when the customer reaches serveevent instead of passing the rng with the customer right the at the start? However I don't call the rng.genServiceTime() until reaching serveevent even when passing the rng object with each customer

**Comment by waynetee** [comment]
genservicetime should only be called when your serveevent is executed i believe

**Comment by dljw98** [comment]
> genservicetime should only be called when your serveevent is executed i believe

I see, meaning I should only call `customer.getServiceTime()` in the function that I pass into `ServeEvent`? Currently I am calling it in the `ServeEvent` constructor outside of the function that I pass into `ServeEvent`

**Comment by descentbw** [comment]
Hmmmm... your implementation seems a bit different from mine, since I pass my _Lazy(service time)_ through the event, but you pass it through the customers.  If you're calling ```customer.getServiceTime()``` outside the function in the ```ServeEvent``` constructor, when ```ServeEvent``` is executed, how does ```DoneEvent``` get it's start time? Based on a customer property that stores the service time after the _Lazy(service time)_ is evaluated for the first time??

**Comment by dljw98** [comment]
> Hmmmm... your implementation seems a bit different from mine, since I pass my _Lazy(service time)_ through the event, but you pass it through the customers. If you're calling `customer.getServiceTime()` outside the function in the `ServeEvent` constructor, when `ServeEvent` is executed, how does `DoneEvent` get it's start time? Based on a customer property that stores the service time after the _Lazy(service time)_ is evaluated for the first time??

Yup! So I call getServiceTime() outside the function, which then memoizes the value in the customer object (Lazy), and assign the value to a variable. Then after defining that variable, I start defining the function underneath it and call on the variable when needed through the function in ServeEvent

**Comment by waynetee** [comment]
> > genservicetime should only be called when your serveevent is executed i believe
> 
> I see, meaning I should only call `customer.getServiceTime()` in the function that I pass into `ServeEvent`? Currently I am calling it in the `ServeEvent` constructor outside of the function that I pass into `ServeEvent`

I mean it depends on your implementation but I would say yes that's how I think its supposed to be done
