### ISSUE TITLE
Project 2 Level 5 Design Rest and Back Events

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#397]
Hi, I'm stuck at how to design the Server_Rest and Server_Back events. Should I include the two events in the Main class or create them separately as child class of Event class? 

Please give me some advice. Thank you!

**Comment by fans2619** [comment]
I think you can simply add the two events to extend Event. To be honest, I think just using the DoneEvent can also achieve the goal. Basically, ServerRest and ServerBack is just to indicate a period that the server won't take in customers and postpone to serve other waiting customers.

**Comment by fans2619** [comment]
I believe there are a lot of other ways to implement the two events so this is just my idea.

**Comment by benluiwj** [comment]
What i did was that i included it after the done event and the two events are sub class of event.  So in my case, the server status of the done event will be not available. Then it will go into the server rest event. If the server probability satisfies the criteria then it goes to rest. Then once it rests, i update the times of the other customers to the time the server is back. After the server has rested, then it will go to the server back which is similar to the current done event

**Comment by zzkzzzz** [comment]
You can make `ServerRest Event` and `ServerBack Event` extend `Event`. What I do is that every server will have`ServerRest Event` after `DoneEvent`. The difference is the resting time. If the server no need to rest, I just set the resting time to zero. Then after `ServerBack Event` it should be `Leave Event`. The whole process will be `Arrive->Serve->Done->Rest->Back->Leave`

**Comment by Josephaedan** [comment]
I did the same as the rest and made both events extend Event. Theoretically if your final sequence ends at DoneEvent, you don't even need the 2 events like what @fans2619 mentioned. But the question explicitly states to "Include two events SERVER_REST and SERVER_BACK, to simulating taking a break, and returning. These events should be generated and scheduled in the simulator when the server decides to rest." so I assume you have to add them as events into the simulator.

**Comment by descentbw** [comment]
Make two subclasses of events ```ServerRest``` and ```ServerBack``` as mentioned in the question. Depending on your implementation, ```ServerRest``` can be returned as the event in the Pair<Shop, Event> upon execution of ```DoneEvent```, and ```ServerBack``` can be returned as the event in the Pair<Shop, Event> upon execution of ```ServerRest```.

**Comment by weiyifei-evelyn** [comment]
Thank you for your advice! I'll ty them out :)

**Comment by weiyifei-evelyn** [comment]
@zzkzzzz Thank you for elaborating your approach. May I ask why after ServerBack Event it should be Leave Event? I thought after ServerBack Event, the server will go back to Serve Event and continue serving the next waiting customer (if any)?

**Comment by weiyifei-evelyn** [comment]
> Make two subclasses of events `ServerRest` and `ServerBack` as mentioned in the question. Depending on your implementation, `ServerRest` can be returned as the event in the Pair<Shop, Event> upon execution of `DoneEvent`, and `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerBack`.

@descentbw Hi, thank you for your reply! My current execution is like `Arrive -> Wait -> Serve -> Done` or `Arrive -> Serve -> Done` or `Arrive -> Leave`. Based on your suggestion as well as what @zzkzzzz suggests, I should extend the execution to be `Arrive -> Wait -> Serve -> Done -> Server Rest -> Server Back` or `Arrive -> Serve -> Done -> Server Rest -> Server Back`. However, I'm not so sure what should be returned after executing ServerBack?
You have suggested that upon execution of `ServerBack`, `ServerBack` is returned as the event in the Pair<Shop, Event>. Why is that so?

**Comment by descentbw** [comment]
> > Make two subclasses of events `ServerRest` and `ServerBack` as mentioned in the question. Depending on your implementation, `ServerRest` can be returned as the event in the Pair<Shop, Event> upon execution of `DoneEvent`, and `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerBack`.
> 
> @descentbw Hi, thank you for your reply! My current execution is like `Arrive -> Wait -> Serve -> Done` or `Arrive -> Serve -> Done` or `Arrive -> Leave`. Based on your suggestion as well as what @zzkzzzz suggests, I should extend the execution to be `Arrive -> Wait -> Serve -> Done -> Server Rest -> Server Back` or `Arrive -> Serve -> Done -> Server Rest -> Server Back`. However, I'm not so sure what should be returned after executing ServerBack?
> You have suggested that upon execution of `ServerBack`, `ServerBack` is returned as the event in the Pair<Shop, Event>. Why is that so?

Oh sorry, that was a typo, in my last line, I meant to say ```ServerBack``` can be returned as the event in the Pair<Shop, Event> upon execution of ```ServerRest```.

**Comment by weiyifei-evelyn** [comment]
> > > Make two subclasses of events `ServerRest` and `ServerBack` as mentioned in the question. Depending on your implementation, `ServerRest` can be returned as the event in the Pair<Shop, Event> upon execution of `DoneEvent`, and `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerBack`.
> > 
> > 
> > @descentbw Hi, thank you for your reply! My current execution is like `Arrive -> Wait -> Serve -> Done` or `Arrive -> Serve -> Done` or `Arrive -> Leave`. Based on your suggestion as well as what @zzkzzzz suggests, I should extend the execution to be `Arrive -> Wait -> Serve -> Done -> Server Rest -> Server Back` or `Arrive -> Serve -> Done -> Server Rest -> Server Back`. However, I'm not so sure what should be returned after executing ServerBack?
> > You have suggested that upon execution of `ServerBack`, `ServerBack` is returned as the event in the Pair<Shop, Event>. Why is that so?
> 
> Oh sorry, that was a typo, in my last line, I meant to say `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerRest`.
Ohh I see, then for ServerBack, what should be returned if I execute ServerBack? Just add the resting server back to the list of servers in the shop?

**Comment by fans2619** [comment]
> > > > Make two subclasses of events `ServerRest` and `ServerBack` as mentioned in the question. Depending on your implementation, `ServerRest` can be returned as the event in the Pair<Shop, Event> upon execution of `DoneEvent`, and `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerBack`.
> > > 
> > > 
> > > @descentbw Hi, thank you for your reply! My current execution is like `Arrive -> Wait -> Serve -> Done` or `Arrive -> Serve -> Done` or `Arrive -> Leave`. Based on your suggestion as well as what @zzkzzzz suggests, I should extend the execution to be `Arrive -> Wait -> Serve -> Done -> Server Rest -> Server Back` or `Arrive -> Serve -> Done -> Server Rest -> Server Back`. However, I'm not so sure what should be returned after executing ServerBack?
> > > You have suggested that upon execution of `ServerBack`, `ServerBack` is returned as the event in the Pair<Shop, Event>. Why is that so?
> > 
> > 
> > Oh sorry, that was a typo, in my last line, I meant to say `ServerBack` can be returned as the event in the Pair<Shop, Event> upon execution of `ServerRest`.
> > Ohh I see, then for ServerBack, what should be returned if I execute ServerBack? Just add the resting server back to the list of servers in the shop?

I think you have solved the level maybe. I don't think ServerBack needs to return something valuable. It is just like the original DoneEvent, when the event finishes, there is no next events. So you can make it return anything you like to be honest. From my implementation, my ServerBack just needs to update the server status.

**Comment by weiyifei-evelyn** [comment]
@fans2619 Thank you for your suggestion. I understand how to design ServerRest and ServerBack events.
