### ISSUE TITLE
Project 2 Level 5 How to add in restPeriod

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#402]
According to the information given in project 2 level 5: "as soon as the server rests, a random rest period is generated using the RandomGenerator method genRestPeriod().", I understand that we need to create a RandomGenerator in Main class and use it to generate restPeriod when Server_Rest event takes place. Thus, the value of restPeriod for a particular Server_Rest event should be generated in the Main class. Then, how can I pass this value of restDuration to Server_Rest event and update the status of server in the shop?

Please offer me some suggestions. Thank you!

**Comment by Hzxin** [comment]
my approach s in Main class, when iterating through all events, whenever DoneEvent is  encountered, I manually create a Restevent.
With that I can pass my restperiod directly into restevent

**Comment by thmtiffany** [comment]
I passed it in lazily instead through the Server class (similar to how they suggested to generate service time), not sure if this is the best idea though.

**Comment by descentbw** [comment]
Depends on your implementation. I passed my _Lazy(genRandomRest())_ and _Lazy(genRestPeriod())_ from Main to my event classes. When it reaches DoneEvent, I evaluated the item(s) in the lazy.

**Comment by weiyifei-evelyn** [comment]
@thmtiffany Thank you for your suggestion! I think if pass genRandomRest() and genRestPeriod() lazily through Server class will be less of a hassle. However, how do you gain access to server? Is it done through your shop class?

**Comment by jeremybrett4869** [comment]
Hi, I think my solution for this one is the same as in level 3 and 4 (generate the service time when the ServeEvent is executed). My approach is that in Main, if the current event is server rest, I update the state of the server (by replace), then add the new server back event to the priority queue. Hope this will help you! :)

**Comment by qiaoningg** [comment]
Hi! My approach for this was that I generated the server rest time in Main and then created a new server with the updated nextAvailableTime and replace it in the shop.

**Comment by weiyifei-evelyn** [comment]
> Hi, I think my solution for this one is the same as in level 3 and 4 (generate the service time when the ServeEvent is executed). My approach is that in Main, if the current event is server rest, I update the state of the server (by replace), then add the new server back event to the priority queue. Hope this will help you! :)

@jeremybrett4869 Thank you for your suggestion. May I clarify with you that you update the state of server (by replace) in the Main class, not in ServerRest and ServerBack right? I'm trying to update in ServerRest and ServerBack, but exceptions were thrown because when I try to execute a ServeEvent and the server goes to rest (that server is no longer in the list of serves of Shop), thus there is no available server to serve him.

**Comment by weiyifei-evelyn** [comment]
@jeremybrett4869 I figured it out already. Thank everyone for his help!!!
