### ISSUE TITLE
Project2 level3 NoSuchElementException in CodeCrunch

### ISSUE THREAD

**Issue by tlylt** [nus-cs2030/2021-s1#403]
# Description 
Hi, I'm getting this exception on codecrunch(See attached, Fail Test Case: test3_1). 
My line at Main.java:23 is `int seed = sc.nextInt();`,  the first value that I read in.
Which I don't think will trigger `NoSuchElementException`? Does anyone know what's testcase3_1 or what might be the issue here? 

Thanks in advance.
## Topic: 
Specific Topics this question is related to (If Any) 
Project2 test3_1
## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/41845017/99380817-69b55980-2905-11eb-9282-39fa054649be.png)

**Comment by Hzxin** [comment]
Pass in the command lines args instead. Don't use scanner, so you may wanna have int seed = Integer.parseInt(args[0])

**Comment by kennethkks** [comment]
You must remember to account for the different input lengths for level 3 onwards

**Comment by descentbw** [comment]
Use Integer.parseInt(args[index]) and Double.parseDouble(args[index]) to take in integer and double inputs from command line arguments.

**Comment by a1if5** [comment]
Hi! I still have the NoSuchElementException error despite using the parseInt and parseDouble. Am I doing it correctly?

int seed = Integer.parseInt(args[0]);
int numServer = Integer.parseInt(args[1]);
int customerCount = Integer.parseInt(args[2]);
double arrivalRate = Double.parseDouble(args[3]);
double serviceRate = Double.parseDouble(args[4]);

Thank you

**Comment by azr124** [comment]
Hi i still got the NoSuchElementException Error. 
Am I doing it correctly?

        Integer seed = Integer.parseInt(args[0]);
        Integer numServer = Integer.parseInt(args[1]);
        Integer customerCount = Integer.parseInt(args[2]);
        Double arrivalRate = Double.parseDouble(args[3]);
        Double serviceRate = Double.parseDouble(args[4]);

Thank you!

**Comment by tlylt** [comment]
> Hi i still got the NoSuchElementException Error.
> Am I doing it correctly?
> 
> ```
>     Integer seed = Integer.parseInt(args[0]);
>     Integer numServer = Integer.parseInt(args[1]);
>     Integer customerCount = Integer.parseInt(args[2]);
>     Double arrivalRate = Double.parseDouble(args[3]);
>     Double serviceRate = Double.parseDouble(args[4]);
> ```
> 
> Thank you!

Looks ok to me, did you check for different length of arguments? e.g. level 3 is 5 and level 4 is 6 iirc

**Comment by azr124** [comment]
i am doing it for level 3. So its 5 arguments right?

**Comment by tlylt** [comment]
What's the exact error message and stack trace? Maybe can tell from there which line is causing the issue...
Or is yours exactly the same as my screenshot above?

**Comment by azr124** [comment]
yes it is exactly the same thing as yours, even to the exact Scanner.java line number haha
Just to double check it is just public static void main(String[] args) { before receiving the inputs right?

**Comment by tlylt** [comment]
Yea mine look something like this:
```

class Main {
    public static void main(String[] args) {
        
        int seed = Integer.parseInt(args[0]);

        int numOfServers = Integer.parseInt(args[1]);
...
```
Check if you have submitted the correct/updated files? idk whats wrong haha..
Hello,
I will just do java Main 1 1 5 1.0 1.0, then press enter

**Comment by azr124** [comment]
do you have to press cmd / control D after pasting java Main 1 1 5 1.0 1.0 into the terminal / cmd or the thing auto run upon pasting?
