### ISSUE TITLE
Project 2 Level 6

### ISSUE THREAD

**Issue by Terrence-F** [nus-cs2030/2021-s1#409]
Is this likely due to error in the execution of SERVER_REST event that slipped past level5?
Or have I neglected some considerations for the SelfCheckOut?

This is from Level 6 public testcase 2:
java Main 1 2 1 2 20 1.0 1.0 0.1 0.5
![image](https://user-images.githubusercontent.com/65442533/99411524-ab0e2f00-292e-11eb-8a21-0905d306325b.png)

Failed codecrunch testcase 6_5
![image](https://user-images.githubusercontent.com/65442533/99412173-63d46e00-292f-11eb-8271-b5aede5c7e1e.png)

**Comment by Terrence-F** [comment]
Is there a possibility that the self check will still genRandomRest() but the possibility of resting = 0?

Currently self check does not cause genRandomRest()

**Comment by fans2619** [comment]
> Is there a possibility that the self check will still genRandomRest() but the possibility of resting = 0?
> 
> Currently self check does not cause genRandomRest()

No self-checkout will not call genRandomRest().

**Comment by SkyBlaise99** [comment]
Your `self check queue` does not seem to be shared. All `Customers` should queue at one `self check counter` i.e. 1. You shouldnt even be printing `4 waits to be served by self-check 2`. Even if it is printed, it should be `4 waits to be served by self-check 1`.

**Comment by CWei88** [comment]
Is it because of your implementation of the shared queue? It seems like the Customer should see the queue being full in your test case but doesn't

**Comment by Terrence-F** [comment]
Thanks for all your help! :) Managed to pass this test case.
The first issue is due to unnecessary execution of genRandomRest()
The second issue is failure to update queue status for shared queue

**Comment by jadenwjh** [comment]
@Terrence-F Hi sorry for commenting on a closed issue. I'm facing the same problem now and I suspect I didn't update the shared queue properly. May I know how did u update the queue?
