### ISSUE TITLE
Lab2 Level 6 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#41]
It seems that the lab in codecrunch has an additional level (level 6: Recycled Loaders). Where do we get the test files related to this? 

Also,  do we create a new class RecycledLoaders.java ?

**Comment by HolmesJJ** [comment]
Hi, @colintkn. Yes we need to create a new class RecycledLoader.java. Just need to follow the question requirements to create level6.jsh. Dont have any test files.

**Comment by tlylt** [comment]
If you need the test file, can get from [here](https://gist.github.com/tlylt/bbe27b619c0bd8f9a21bd327f185ca1c). Just a simple jsh based on the description.

**Comment by colintkn** [comment]
Ok thank you!
