### ISSUE TITLE
How to keep track of number of customers in queue? Project Test case 4_4 

### ISSUE THREAD

**Issue by limeugene** [nus-cs2030/2021-s1#415]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/4206908/99454983-23421800-2962-11eb-9fe4-cca92fea723b.png">

<img width="977" alt="image" src="https://user-images.githubusercontent.com/4206908/99455067-466cc780-2962-11eb-8a42-833702c0f824.png">

Hi, any tips on how to keep track of the number of customers waiting in the queue for each Server? Right now, I'm updating them within each event (during their execution), but I can't seem to figure it out... The first picture is when I print out the number of customers in the first server after polling each event from my priority queue. Would appreciate any advice thanks :((

**Comment by merylseow** [comment]
For me I stored a list of Queues in my Shop that represents every server's queues. Then I have a method in Shop to obtain the queue of any specific server. As for updating, I only add waiting customers in my WaitEvent. Then anywhere else I need the number of customers in the queue I just find the size of the queue.

**Comment by SkyBlaise99** [comment]
you can have a `int qCount` and `int qMax` to do it in your `Server`

**Comment by myangat0343** [comment]
The qCount and qMax in the Server will be useful.

**Comment by kah0210** [comment]
Each Server can have its queue count. This queue count will only be updated in WaitEvent (+1) and ServeEvent (-1)

qMax can just be passed into ArriveEvent (when u instantiate this in Main.java) as you only need qMax in ArriveEvent conditions.

Hope this helps!

**Comment by descentbw** [comment]
I implemented a queue variable into each server, and then included methods such as addToQueue and RemoveFromQueue.

**Comment by limeugene** [comment]
Thank you all for your help! :)
