### ISSUE TITLE
Project 2 Level 6 Clarification of Queue Length of Self-checkout Counter

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#416]
At project 2 Level 6, the question states that "All self-checkout counters share the same queue.". May I clarify that this shared queue should have the same maximum queue length as a normal server? Or the maximum queue length of the shared queue for all self-checkout counters is number of self-checkout counters * maximum queue length of a normal server?

**Comment by b-leong** [comment]
The self checkout queue has the same length as a normal server

**Comment by merylseow** [comment]
Shared queue has same maximum queue length as normal server

**Comment by weiyifei-evelyn** [comment]
@b-leong @merylseow I see, thank you!
