### ISSUE TITLE
Project 2 Level 6 Design of self-checkout counter and the shared queue

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#419]
Hi, for project level 6, I'm thinking about the design of self-checkout counter and the shared queue of all self-checkout counters.

For now I have a few ideas, please offer me some advice on which are feasible/better designs:

Design 1. Create a parent class called `Service counter` and a child class `self-checkout counter`. Let `self-checkout counter` and `Server` extend this parent class `Service counter`. The main difference between them is that `self-checkout counter`does not contain properties related to `Rest`. After these, I don't know how can I create a shared queue for these self-checkout servers. Should I save the shared queue as a property in the `self-checkout counter` class? If so, how should I pass the queue in the Main class to `self-checkout counter` class?

Design 2. Don't create `self-checkout counter` class. Create the shared queue of self-checkout counters in Main class. Then, when an event is paired with a self-checkout counter, it will be added to the shared queue. However, I'm not so sure of how to continue the design? Should I save the shared queue for all self-checkout servers? If so, how can I know which self-checkout counter will serve the customers in the queue?

Please correct me if I'm wrong. Thank everyone in advance for your advice on the design of self-checkout counter and the shared queue!

**Comment by charoi** [comment]
Hi @weiyifei-evelyn ,
I think if you stuck to Design 1 that adheres better to the abstraction principle. I think for the class wise can I if you are planning to store queues in Server? Maybe you can abstract away queues as a separate class that is called from `Shop`? Thats not my design but if you're asking about sharing queues maybe its best to keep that in a class like Shop.

**Comment by SkyBlaise99** [comment]
you can use `static qShared` in your self service

**Comment by kah0210** [comment]
You can implement design 2 by storing the shared list of waiting customers in the FIRST self checkout counter. Subsequently, all self checkout servers can refer to this queue by finding the first self checkout counter in shop, and update this queue accordingly. Hope this helps!

**Comment by weiyifei-evelyn** [comment]
> You can implement design 2 by storing the shared list of waiting customers in the FIRST self checkout counter. Subsequently, all self checkout servers can refer to this queue by finding the first self checkout counter in shop, and update this queue accordingly. Hope this helps!

Thank you for you suggestion. May I clarify that do you create `self-checkout counter` class and a parent class `Service counter` and let `Server` and `self-checkout counter` class extend from `Service counter`? I'm working on developing the two new classes for the past few hours. I found that I indeed have to change all the code. So I doubt whether this is a good way to do.

**Comment by weiyifei-evelyn** [comment]
@SkyBlaise99 Thank you for your reply! Do you mean that I need to create `self-checkout counter` class and include a property called `static qShared`? I'm quite confused.

As mentioned in #369, you suggested not making a new class `self-checkout counter` but using a boolean `isSelfService` to decide whether the Server uses int `qCurrent` or static int `qCurrentShared`. So are you suggesting that I should have `isSelfService` in the Main to determine which queue I should be using?

I'm creating new classes but it seems that I have to change all the classes, even including all my Event classes. Could you offer me some advice? Thank you in advance!

**Comment by qiaoningg** [comment]
Hi, I think you can try using design 1 so you'll have a self-checkout counter as well as a normal human server. The self-checkout counter will then contain a `static sharedQ`. For me, I had a getQ() method in my self-checkout class which returns the sharedQ so that I can add customers into it in my Main . Hope this helps! :)

**Comment by kah0210** [comment]
> > You can implement design 2 by storing the shared list of waiting customers in the FIRST self checkout counter. Subsequently, all self checkout servers can refer to this queue by finding the first self checkout counter in shop, and update this queue accordingly. Hope this helps!
> 
> Thank you for you suggestion. May I clarify that do you create `self-checkout counter` class and a parent class `Service counter` and let `Server` and `self-checkout counter` class extend from `Service counter`? I'm working on developing the two new classes for the past few hours. I found that I indeed have to change all the code. So I doubt whether this is a good way to do.

Nope i didnt! Design 2 doesnt require a self checkout class. I have a boolean attribute in Server class denoting whether the server is a self checkout counter or not. My self checkout counters are normal servers!

**Comment by SkyBlaise99** [comment]
@weiyifei-evelyn what i mean is to add a `boolean isSelfService` and a `static qShared` in `Server.java`. So you will initialize a Self Service Counter just like a normal Server, but with a boolean flag to indicate that it is a Self Service Server. Subsequent calling of methods in `Server` will become
```
public ... some_method_in_server( ... ) {
    if (isSelfService) {
        ...
    } else {
        ...
    }
}
```

Of cuz, you can ignore the `if else` if the normal Server behaves the same as a Self Service Server

**Comment by weiyifei-evelyn** [comment]
@SkyBlaise99 @kahehe I see! Thank you for your kind help :))

**Comment by weiyifei-evelyn** [comment]
> Hi, I think you can try using design 1 so you'll have a self-checkout counter as well as a normal human server. The self-checkout counter will then contain a `static sharedQ`. For me, I had a getQ() method in my self-checkout class which returns the sharedQ so that I can add customers into it in my Main . Hope this helps! :)

Thank you for your suggestion!
