### ISSUE TITLE
Project 2: Level 2 Cyclic Dependency Issue

### ISSUE THREAD

**Issue by limyapkai** [nus-cs2030/2021-s1#424]
Would any kind soul be able to help advise on this matter? Ran into Cyclic Dependency problem. :( 
Cyclic Dependency at Level 2. All the requirements such as **final Pair<Shop, Event> execute(Shop shop)** are already implemented. 

![image](https://user-images.githubusercontent.com/27536739/99499237-8b6d1a00-29b3-11eb-9ee3-d7adf08ce358.png)

**Comment by merylseow** [comment]
Hm maybe you want to check Event -> EventStatus and EventStatus -> Event?

**Comment by kah0210** [comment]
May reconsider having an event status class! Perhaps you could share more about the implemented event status class?

**Comment by Jcheez** [comment]
You might want to check if methods declared in Events are used in Events Status and vice versa. If they are, u might have to find another method to pass the information around. Maybe you might want to share what is the purpose of having Events Status?

**Comment by limyapkai** [comment]
@merylseow @kahehe @Jcheez Thank you all for the inputs! Yea so Apparently Event Status contains the enums of all the Events that is stored in Event Class. All I had to do was to seperate it and have an enum class on its own! :)
