### ISSUE TITLE
Project 2 NullPointerException

### ISSUE THREAD

**Issue by just-trying-plz** [nus-cs2030/2021-s1#425]
# Description 
Describe the question  
Project 2:
While running my tests, it seems that my Shop.java is returning a NullPointerException even though I am using Optional class to catch cases when there are nulls. I have no idea how this is possible and why. Does anyone know how this null is not captured by the Optional class. Any idea how to fix this? 

I am narrowing down the problems and I think it may have to do with my find(). I have included screenshots regarding my find() :"D. Can anyone let me know if I have any misconceptions about how I should be using streams or optional class?

## Topic: 
Specific Topics this question is related to (If Any) 
Immutability Optional Exceptions
## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/71790053/99512995-199dcc00-29c5-11eb-9475-959b20184503.png)
This is the error that I am dealing with

![image](https://user-images.githubusercontent.com/71790053/99514707-012eb100-29c7-11eb-9b94-96f333557d23.png)
Here is my find method in my Shop.java. Over here,I am returning a Optional<Server> type.

Would be great if anyone can help! Thank you!! :")

**Comment by hari-dharan** [comment]
Your newL.stream().filter(server).findFirst() already returns you your desired Optional<Server> return type.

**Comment by merylseow** [comment]
Remove `List<Server> newL = new ArrayList<>(s)` and just try `s.stream().filter(server).findFirst()`. See if it works? Also, don't need collect since findFirst() is a terminal operation and collect returns a list instead of `Optional<Server>`.

**Comment by SkyBlaise99** [comment]
you are returning `Optional<Server>` but `collect()` will turn it into a `List`.

**Comment by descentbw** [comment]
The ```Shop::find``` method returns an ```Optional<Server>```, which ```Stream::findFirst``` already does. Thus, you do not need to go the extra step to collect it into a list.

**Comment by just-trying-plz** [comment]
omg you guys are right! Thank you so much!
