### ISSUE TITLE
Project 2: Level 4 queueing customers cannot fetch next available time form servers

### ISSUE THREAD

**Issue by jadenwjh** [nus-cs2030/2021-s1#426]
<img width="496" alt="Screenshot 2020-11-18 at 7 51 50 PM" src="https://user-images.githubusercontent.com/62279469/99527393-b49fa180-29d7-11eb-9b6d-b1ed0286389a.png">

been trying to fix this issue for q awhile. the waiting customers are unable to fetch the nextAvailableTime from their servers for test 4. How did yall go by solving it?

**Comment by SkyBlaise99** [comment]
Use `shop.find()` to get the most updated server state everytime at the start of event execute method

**Comment by jadenwjh** [comment]
@SkyBlaise99 yup i did the following for both Serve and Wait events, but to no avail.

Optional<Server> server = oldShop.find(currServer -> currServer.getID() == customer.isServedBy());

**Comment by kah0210** [comment]
The code for Optional server looks right.
Perhaps in Main.java you can try printing customer.isServedBy() and shop, or provide more information so that we can better identify the problem?

**Comment by Jcheez** [comment]
In your serveEvent, you might want to get the latest server. After that, compare the latestserver's next available time with the eventStart Time.

If the eventStartTime is earlier then the latestServer's nextavailabletime, then you should reschedule the event by making another serve event.

**Comment by qiaoningg** [comment]
Another method you could consider trying would be generating the serve time/serveEvent for a waiting customer only when the server has finished serving the previous customer since the previous customer done time would be the serve time of the waiting customer.

**Comment by jadenwjh** [comment]
@kahehe @Jcheez @qiaoningg thanks for your responses! what variables did u give for rescheduling to avoid endless loop?

**Comment by Jcheez** [comment]
For me, I have a currentServer parameter that is passed in all events. As such, I will update the next available time of my currentServer to the latestServer's one, and then ill return a pair consisting of another serveEvent.

**Comment by kah0210** [comment]
To avoid endless loops, i do checking in Main.java using instanceof! eg if polledevent is instanceof EventX and nextevent is instanceof EventY, then i will just print polledevent and not add nextevent into priorityqueue! Not too sure if this answers your question but hope it helps! :)

**Comment by jadenwjh** [comment]
i see thanks alot! I managed to solve it by passing the chosen servers nextAvailableTime and using String buffer in Main to prevent the wrong event from printing
