### ISSUE TITLE
Proj 2 Testcase 6_8

### ISSUE THREAD

**Issue by jiayi-lim** [nus-cs2030/2021-s1#428]
# Description 
Hii, anyone encountered something similar?

My current implementation: 
Adding 1 to the queue in Wait Event 
Removing 1 in the Serve Event upon checking that it came from Wait Event 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/65161176/99534969-334e0c00-29e3-11eb-892e-a2bc74ce8db0.png)

**Comment by b-leong** [comment]
It seems like all the servers should have full queues by this point and your self checkout common queue length might be wrong

**Comment by Jcheez** [comment]
This might be the case of the current queue in the self checks not being updated properly, you might want to print it in every event and see if there are any discrepancies.

**Comment by kah0210** [comment]
Perhaps you can check if the updating of shop in each event is done properly too! Especially if there are changes to more than 1 server in the function

**Comment by jeremybrett4869** [comment]
You may print out and check the queue size of the self-checkouts and see whether you have updated the queue for all self-checkouts correctly.

**Comment by jiayi-lim** [comment]
I think the queue size is correct though... like from the looks of the public test case. Do yall have any test case for me to try and check my self checkout queue?

**Comment by b-leong** [comment]
java Main 1 0 3 5 40 5 .3 .1 .5

stats: [3.190 19 21]

**Comment by jiayi-lim** [comment]
@kahehe oh ya I think my serve event had to update the server twice but it looks right.
I am updating the k+1th Server's queue number and the next available time of the actual Self Checkout. 

```

if (isSelfCheckout) {
    Server firstSelfServer = ...
    Server updatedServer = ...
    return Pair.of(shop.replace(firstSelfServer).replace(updatedServer), ...)
}
```

**Comment by kah0210** [comment]
> @kahehe oh ya I think my serve event had to update the server twice but it looks right.
> I am updating the k+1th Server's queue number and the next available time of the actual Self Checkout.
> 
> ```
> 
> if (isSelfCheckout) {
>     Server firstSelfServer = ...
>     Server updatedServer = ...
>     return Pair.of(shop.replace(firstSelfServer).replace(updatedServer), ...)
> }
> ```

Did u account for the case whereby firstSelfServer and updatedServer refers to the same server?

**Comment by jiayi-lim** [comment]
![image](https://user-images.githubusercontent.com/65161176/99539615-68f5f380-29e9-11eb-8035-c2baa31be0ad.png)
oh ya you guys are right i think my updating is wrong...

**Comment by jiayi-lim** [comment]
@kahehe Nope! Omg is that why... Do I make an if-else loop to check if they are the same server?

**Comment by b-leong** [comment]
yea they have to be updated separately

**Comment by jiayi-lim** [comment]
I got it!!!!! Thanks guys :))
