### ISSUE TITLE
Project 2 Level 6 Implement Shared Queue

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#429]
Hi, I'm stuck at the implementation of the `static` shared queue of self-checkout counters. So far, my design is to have two queues in the Main class: one is the normal priority queue storing all the events (regardless of whether the event is executed by human workers or self-checkout counters), the other is a shared priority queue storing all the WaitEvent of self-checkout counters. Events stored in the normal priority queue are executed in order. Once there is a WaitEvent of  self-checkout counters, I will add the WaitEvent to the shared queue. Once the WaitEvent in shared queue is executed, it will be removed from the shared queue. However, when I run the test case, I realise that 
"10.148 12 waits to be served by self-check 2" but at that time, because self-check 3 is available, "12.074 12 served by self-check 3". So my implementation of the shared queue failed i.e my implementation will still make customer 12 served by the appointed self-check 2.

Could anyone offer me some advice on how you implemented the `static` shared queue and the normal priority queue storing all the events? I feel that my implementation is quite problematic.

Thank everyone in advance!

**Comment by Jcheez** [comment]
Hi, I used a static variable to store the queue for the self checkout. Maybe when you are at the waitEvent, you have to find the selfcheckout with the earliest next available time (call this server x). After that, you need to find the position of the customer in the static queue. Update his current Server to server x. If he is the first one, reschedule him to a serve Event, if he isnt, then u need to reschedule him to another wait event since it is not his turn to be served. 

Hope this helps

**Comment by SkyBlaise99** [comment]
What you have is
```
1. The Customer is waiting @ Self Service Server(SSS) 12
2. The Customer get served by SSS12
```
What i suggest is
```
1. The Customer is actually waiting @ Self Service Server(SSS) 13, but you print SSS 12 in your println().
   This could easily be done by using shop.find(SSS with smallest id)
2. The Customer get served by SSS13
```

**Comment by yuanxintaxon** [comment]
Do you really need a queue?probably u can just add 1-2 properties and extra helper method in the shop class

**Comment by chongweil907** [comment]
@yuanxin1997 how do u do this ?

**Comment by weiyifei-evelyn** [comment]
@SkyBlaise99 okay, I get what you mean. May I clarify that for level 6, as long as a customer is waiting for a self-checkout counter, he will always wait for the self-checkout counter with smallest ID? But which self-checkout counter actually serves him depends on the state of self-checkout counter at that moment. 
Please correct me if I'm wrong. Thank you!!!

**Comment by weiyifei-evelyn** [comment]
> Do you really need a queue?probably u can just add 1-2 properties and extra helper method in the shop class

I'm curious how you achieve this. I'm using a `static` qShared for Self-checkout counters, based on what others suggested.

**Comment by jeremybrett4869** [comment]
In level 6, the waiting behaviour of the customer is the same as the previous levels, but yes, which self-checkout counter to serve the waiting customer depends on the state of all self-checkout counters (probably not the one he is waiting for).

**Comment by weiyifei-evelyn** [comment]
@jeremybrett4869 Thank you for your reply! So if the status of all counters now is `human server 1 busy and available
at time 7, self-checkout 2 busy and available at time 5, self-checkout 3 busy and available at time 2`, when I generate a WaitEvent, should `customer wait for self-checkout 2` and `customer served by self-checkout 3` be printed?

**Comment by jeremybrett4869** [comment]
In this case, I think if the server 1 has no waiting customer, the customer should wait for server 1?

**Comment by weiyifei-evelyn** [comment]
@jeremybrett4869 sorry my bad, server 1 has a queue reaching the maximum queue length already, so it will queue for `self-checkout 2` not `self-checkout 3` right? even though `self-checkout 3` will be available earlier than `self-checkout 2`.

**Comment by kheekheekhee** [comment]
What I did was at each loop of the priority queue, I check if there is a self checkout available at the current time and push the next most recent ServeEvent for Customers at the self checkout queue forward to the current time and since this is done every loop, it'll take care of every self checkout thereafter

**Comment by jeremybrett4869** [comment]
> @jeremybrett4869 sorry my bad, server 1 has a queue reaching the maximum queue length already, so it will queue for `self-checkout 2` not `self-checkout 3` right? even though `self-checkout 3` will be available earlier than `self-checkout 2`.

yes :)

**Comment by weiyifei-evelyn** [comment]
> What I did was at each loop of the priority queue, I check if there is a self checkout available at the current time and push the next most recent ServeEvent for Customers at the self checkout queue forward to the current time and since this is done every loop, it'll take care of every self checkout thereafter

@kheekheekhee Thank you for your suggestion. I don't understand this part: "push the next most recent ServeEvent for Customers at the self checkout queue forward to the current time". Do you mean that:
1. I need to use the available self checkout to generate a new ServeEvent
2. add this new ServeEvent to the `static` shared queue for self-checkout and execute it first?
If this is the case, how should I deal with the chosen ServeEvent in the event priority queue containing all the events. Sorry, could you explain further?

**Comment by yuanxin1997** [comment]
A shop can have 1..* counter served by human(aka human server) and also have a "self check area" with a cluster of self-check counters 1...* (not served by human). This self-check area has a shared queue.

But it is not necessary to create a new class to represent this self check area. (it just for explanation and visualisation).

Translating this concept to code.

It will be a shop class with these information
(1) - a ```list of servers``` human server (each has a N queue size) and non-human server (each has 1 queue size))
(2) - ```max queue size``` at the "self check area - the sum of the queue size of all non-human server (aka self-check counters)
(3) - ```slot left``` at the "self check area" - ....

you can create an extra helper method to choose a counter for the customer using the information available above.

ps: There are some times where you will need to reschedule a serve event for your customers if there are no counter available.

**Comment by ClementNgZiQian** [comment]
You can try scheduling a Serve Event for every customer waiting at the selfcheckout, with the server allocated being the one that has the earliest next available time.

**Comment by weiyifei-evelyn** [comment]
Appreciate everyone's help. I solved the problem with your suggestion :)))
