### ISSUE TITLE
[Project 2] Level 1-4

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#433]
Hi, upon submission for Level 4, i failed Level 2. May i ask how did you guys cater for the previous levels? I know the issue lies in the `ArriveEvent` actually but im not too sure how to go about solving it...

Thanks!

**Comment by xingaporean** [comment]
need more info to help lmao

**Comment by domlimm** [comment]
Sorry,

![image](https://user-images.githubusercontent.com/46486515/99563587-5f2db980-2a04-11eb-9340-0246d6bb4e7a.png)

Rather how was your program designed to cater for the previous test cases?
