### ISSUE TITLE
Priority Queue: How to find an item in the Priority Queue matching a given condition

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#435]
Hi, 

I have a problem when attempting project 2 level 6. In a priority queue, I want to find the index of element that match a given condition. How can I achieve it? I attach an example for easier understanding of the question.

For example, I have a priority queue of `Event`. Event has property of `Customer` and `Event` can gain access to `CustomerID`. Now I am given a particular `Customer` (call it Customer A). I want to find the index of this `Customer` (Customer A) in this priority queue of `Event` i.e. The `CustomerID` of this given `Customer` (Customer A) matches the `CustomerID` of a `Customer` in one of the `Event` item in the priority queue.

Thank you for your kind help in advance!

**Comment by SkyBlaise99** [comment]
1. Create a copy of your pq
2. for loop and poll one by one to check if you found the Event with the matching Customer given Customer ID, return the current index of for loop

Not sure why you need this lol

**Comment by yuanxin1997** [comment]
You can convert Pq to array, and then arr.indexOf(obj).

The time complexity is expensive. Why do you need to design it this way?

**Comment by weiyifei-evelyn** [comment]
> 1. Create a copy of your pq
> 2. for loop and poll one by one to check if you found the Event with the matching Customer given Customer ID, return the current index of for loop
> 
> Not sure why you need this lol

#429 I'm working on the idea @Jcheez suggested. I'm trying to find the position of the customer in the static queue. However, I realise that there is a better way of implementing the shared queue.

**Comment by bryanwee023** [comment]
@SkyBlaise99 Yo, actually PriorityQueue is an Iterable. So 
`for (Event e: pq) {
//check if Customer in e fits predicate
}`
is more elegant.

**Comment by SkyBlaise99** [comment]
He wants the index though, and extra step is needed if iterator is used

**Comment by weiyifei-evelyn** [comment]
Thanks to everyone's help. I figured it out :)
