### ISSUE TITLE
Project 2: Shop is not updating properly 

### ISSUE THREAD

**Issue by JoelTannnnnn** [nus-cs2030/2021-s1#437]
Hi im not sure why I get this output? it seems to me that my priority queue or my shop is not updating properly but I cannot pinpoint where exactly the problem is 

![image](https://user-images.githubusercontent.com/70709228/99622673-98e2dc80-2a65-11eb-968c-385e55584150.png)

**Comment by kah0210** [comment]
Did u update your shop in Main.java ?
For example:
Pair<Shop, Event> pair = polledevent.execute(mainshop);
mainshop = pair.first();

**Comment by JoelTannnnnn** [comment]
![image](https://user-images.githubusercontent.com/70709228/99628421-1bbd6480-2a71-11eb-85d7-0b4666c0cae0.png)
yea i did!

**Comment by Josephaedan** [comment]
Assuming your eventComparator is working properly, this should be a problem with your priority queue not having the customer arrive events beforehand. Can you check that you add the customer arrive events to the priority queue first before cycling through it?

**Comment by JoelTannnnnn** [comment]
@Josephaedan yup I have done it too. so its my event comparator's issue? 

![image](https://user-images.githubusercontent.com/70709228/99629252-a3f03980-2a72-11eb-9745-4d62586a0bed.png)

**Comment by Josephaedan** [comment]
Yeah I think it’s an issue with your eventComparator prioritising polling out DoneEvents before ArriveEvents. Events should be prioritised firstly by their timings, then if they’re the same time, by the type of event. Can you check that your comparator returns the priority  according to the event timings first?

**Comment by JoelTannnnnn** [comment]
@Josephaedan will comparing timings and then comparing customer id work? cos thats what i did for proj1

**Comment by kaiyang96** [comment]
> @Josephaedan will comparing timings and then comparing customer id work? cos thats what i did for proj1

Yes that should be sufficient for the rest of the project. It seems like your event comparator from your initial screenshot is the problem because its sorting based on customer ID first before time!

**Comment by marcuspeh** [comment]
Check your comparator. It looks like its not comparing based on time but based on customer id

**Comment by JoelTannnnnn** [comment]
@marcuspeh @kaiyang96 doesnt seem like the issue? i tried sys out and it looks like its comparing the timings 
![image](https://user-images.githubusercontent.com/70709228/99637542-fa17a980-2a7f-11eb-80be-74d61da1f277.png)
![image](https://user-images.githubusercontent.com/70709228/99637572-0439a800-2a80-11eb-8f38-50751114d5b5.png)

**Comment by marcuspeh** [comment]
Your output time seems to be correct now. It was wrong before.

> ![image](https://user-images.githubusercontent.com/70709228/99628421-1bbd6480-2a71-11eb-85d7-0b4666c0cae0.png)

Btw is the shop your execute return updated? Seem not like it.

**Comment by JoelTannnnnn** [comment]
@marcuspeh yes for every event, i update the server accordingly using shop.replace and then return Pair.of (updated server, new event)

**Comment by marcuspeh** [comment]
Maybe its because you executed it twice in that one loop. So it was suppose to be from arrive -> serve but u called it twice so the server might have gotton updated twice and end up being free

**Comment by JoelTannnnnn** [comment]
@Josephaedan @marcuspeh @kahehe @kaiyang96 thank you for your help!
