### ISSUE TITLE
Project 2 Level 4 

### ISSUE THREAD

**Issue by sharleneq** [nus-cs2030/2021-s1#438]
Hey guys, I've rescheduled the ServeEvent for customer 10 to the correct timing **"10.781 10 served by server 1"**, but I'm not sure how to print only the correct event. As seen from the screenshot, I want to get rid of the output **"10.484 10 served by server 1"**. 

Any tips on how I should proceed? Any help is welcomed!

My output:
<img width="309" alt="Screenshot 2020-11-19 at 2 04 20 PM" src="https://user-images.githubusercontent.com/65596820/99627904-1f9cb700-2a70-11eb-96e1-f9c2407b46c1.png">

Desired output:
<img width="289" alt="Screenshot 2020-11-19 at 2 05 06 PM" src="https://user-images.githubusercontent.com/65596820/99627979-3c38ef00-2a70-11eb-8b85-4797057fe3b3.png">

**Comment by benluiwj** [comment]
seems like you dint remove number 10 from the queue when it is being served.

**Comment by Josephaedan** [comment]
Because level 4 now allows more than 1 customer in the queue, you need to check that the customer being served is currently first in the queue before polling it and printing it. In this case you need to ensure your customers are first in the queue before executing a serve Event and printing it.

**Comment by srj31** [comment]
You will now need to check whether the server has been updated before serving the next customer, to make sure you do not serve another customer while the server is busy.

**Comment by ClementNgZiQian** [comment]
You can check if the event is a rescheduled event, in that case u do not print out the old one, but just send the new one into the PQ.
One way is to check if both the event and the new event are instances of serve events

**Comment by Jcheez** [comment]
you can use the following as a reference:

if x instanceof ServeEvent and nextEvent of x is also a ServeEvent, then do not print.

Hope this helps

**Comment by Josephaedan** [comment]
Yeah I recommend following @Jcheez and also not include this in the statistics calculations as well as your current one now records 11 customers being served.

**Comment by sharleneq** [comment]
Thanks y'all! It worked when I followed ClementNgZiQian and Jcheez suggestions for my design. Thanks to the rest for contributing too
