### ISSUE TITLE
Project 2 Level 3 Bad Source File when Compiling Package

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#439]
I have zero experience with creating java packages (didn’t actually do so in the first project), so I’m completely lost at what to do to make one and access the RandomGenerator class. 

I followed the steps in this previous issue #377  to try and compile the cs2030.simulator, but I received tons of errors along the lines of ‘bad source file’ (pic below). Am I saving/compiling my files in the wrong directory? 

<img width="565" alt="Screenshot 2020-11-19 at 4 09 31 PM" src="https://user-images.githubusercontent.com/39799639/99639210-4ebc2400-2a82-11eb-91f4-8ca373804bb2.png">

**Comment by ClementNgZiQian** [comment]
You try doing this:
1) make sure u have 'package cs2030.simulator;' as ur first line for all .java files except Main.java
2) delete all the .class files, create a folder 'cs2030'  and then 'simulator' inside cs2030
3) move the RandomGenerator.class into the cs2030/simulator
4) in ur main folder with all the .java files, compile the files using 'javac -d . *.java'
5) then in ur Main.java, u import the classes u need by 'import cs2030.simulator.**classname**'

**Comment by EssWhyy** [comment]
@ClementNgZiQian Yeah these were roughly the same steps I followed earlier, just realised I was not supposed to put Main.java along with the other java files when compiling into the package, so now it works, thanks.
