### ISSUE TITLE
Project 2: Level 6 how to correctly add to total waiting time when rescheduling

### ISSUE THREAD

**Issue by jadenwjh** [nus-cs2030/2021-s1#440]
Currently stuck at the total wait time part. I dont quite understand the process of adding the additional wait time when a event with self-checkout is rescheduled.
<img width="1130" alt="Screenshot 2020-11-19 at 9 31 29 PM" src="https://user-images.githubusercontent.com/62279469/99672615-98226880-2aae-11eb-97f9-8702b406ad9b.png">

**Comment by Jcheez** [comment]
perhaps you forgot to add extra waiting time in Main.java? Maybe you might want to share how you implemented your self-check servers.

**Comment by Hzxin** [comment]
maybe try update the time in done event maybe, simply use eventime of done event - customer arrival time   - serve time

**Comment by jadenwjh** [comment]
@Jcheez  what i did was i have my check for rescheduling in Main.java. If the event going to be rescheduled, it will not be executed. So i placed the adding function after the execute and will only add if this condition is met:

Executed event (y) is ServeEvent and Pre-executed event (x) is WaitEvent. totalWaitTime += y.eventtime() - x.eventtime()

@Hzxin  I tried the suggested but i cant get the right outputs bc timing for other stuff will change when i tried to get servetime via the supplier

**Comment by jadenwjh** [comment]
guys i found the problem. I didnt account for the additional time when the events are rescheduled.
