### ISSUE TITLE
Project 2 Level 7 Fail Test 7_7

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#443]
Hi,
<img width="807" alt="Screenshot 2020-11-20 at 9 50 56 AM" src="https://user-images.githubusercontent.com/71199647/99747708-0b12fa00-2b16-11eb-8480-99bf7c482c7e.png">

May someone help me find out what the mistake can be?

How I design `greedy customer` is :
If it is `greedy`, I will iterate through all the servers and self-checkout counters, and find the minimum number of waiting customers i.e. shortest waiting queue. Then I find the first server/self-checkout whose queue length is equal to this shortest queue length. Finally, I will pair the server with this minimum queue length with this greedy customer.

For now, my code passes all the past levels' test cases. So I'm unsure of whether there is something wrong with my greedy.

**Comment by kaiyang96** [comment]
I can't pinpoint the exact problem, but I can speculate as what it may be.
The first and third error would indicate there's a loophole in your method of checking for shortest queue for a greedy customer (since it passes previous test cases, the queue implemented should be correct). Maybe while checking for shortest waiting queue, did you ensure that its not >= max queue length? Or somehow you're returning the wrong server when checking for shortest waiting queue.
I'm inclined to think that the second error is a byproduct of the other errors.

**Comment by ClementNgZiQian** [comment]
How about trying to find for an available server first, then iterate through the waiting queue if all servers are occupied?

**Comment by jiayi-lim** [comment]
I think I know what your mistake is!! You said that when you find the minimum number of waiting customers, you iterate through all servers and self checkout counters. But do note that the self checkout counters only have one queue!!!! So you should just loop through the k human servers and k+1th server (the first self checkout counter). Hope this solves your problem.

**Comment by jiayi-lim** [comment]
If that is not the problem, then I think when you check which server (first k+1 servers only) matches the shortest queue length, check the k human servers before you check the (k+1)th self checkout counter queue cos you want to take the one with the smaller ID.

**Comment by weiyifei-evelyn** [comment]
Thank you for your suggestion! I'lm still checking. I'll update what is the actual error after I find it :)

**Comment by weiyifei-evelyn** [comment]
I solved the issue. The problem like what you describe @jiayi-lim  :)) Thank you so much for your help. I'm closing this issue now.

**Comment by hengyiqun** [comment]
Hi @weiyifei-evelyn, do you mind sharing how you overcome the problem? I am facing the exact errors as you did :(

**Comment by weiyifei-evelyn** [comment]
@hengyiqun Hi, my design in level 6 is to save the queue of self-checkout counters at the position of the first self-checkout counter. So when I design my greedy customer, I need to check the queue length of self-checkout counter by only looking at the queue length stored at the first self-checkout (because the rest of self-checkout counters have a queue length of zero in my design). If you have a similar design as me, that will be the problem. If not, you may want to check whether you updated your servers correctly.

**Comment by hengyiqun** [comment]
@weiyifei-evelyn thanks for your prompt response :)
