### ISSUE TITLE
[Project 2] Test 4_4

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#444]
Hi, I'm stuck on this extremely long list of test cases and I'm guessing it's because of how i implement my AE or could it be related to the lazy evaluation of Service Time generation?

For some context:
1. My ArriveEvent takes in the customerLimit in Queue, and then if it's more than 1, it firstly stores a predicate to check if `server -> server.canCustomerQueue()`. 
If it's present or if the Server's queue is not filled, I queue the Customer.

```java
            Optional<Server> availableServer = shop.find(server -> server.getAvailability());
            
            if (availableServer.isPresent()) {
                return Serve Event, invoked Supplier.get()
            } else if (limit <= 1) {
                Optional<Server> waitServer = shop.find(server -> !server.getHasWaitingCustomer());

                if (waitServer.isPresent())
                    return Wait Event
            } else {
                Optional<Server> canQServer = shop.find(server -> server.canCustomerQueue());

                if (canQServer.isPresent())
                    Queue Customer & return Wait Event
            }
```

2. My ServeEvent takes in a `double serviceTime` param. When AE calls SE, it invokes the `Supplier.get()` and when WE calls SE, it invokes the `Supplier.get()`.

![image](https://user-images.githubusercontent.com/46486515/99751766-d7d46900-2b1d-11eb-93a4-591e9142f280.png)

Appreciate any help please... Thank you

**Comment by limeugene** [comment]
Hmm from the output it doesn't really seem to be an issue of your lazy evaluation of Service Time generation, but I suspect it has to do with you not updating the queue count properly. Perhaps you could try to print the number of people queueing in your servers after polling each event from the priority queue and see if the queue count makes sense? Remember that you add 1 to the queue count when arrive -> wait and decrease 1 to the queue when wait -> serve. 

Also, make sure that you are working with the most updated version of your server when you are executing events so the queue count is the most updated version. (via shop.find(..))

**Comment by domlimm** [comment]
@limeugene Hi, thank you for your input. Based on level 4's 2nd test case, this is what i've gotten

Also, my DoneEvent returns a WaitEvent. I.e. when a Server is done serving current customer, it'll check its customer queue.

To add on, i use this to retrieve a Server in ArriveEvent:
```java
protected boolean canCustomerQueue() {
        return this.customerQueueSize() + 1 <= this.customerLimit;
    }
```

![image](https://user-images.githubusercontent.com/46486515/99755742-7cf33f80-2b26-11eb-8178-74ab797b28c2.png)

**Comment by szelongq** [comment]
From the serveEvent @ 10.484, after 7 is done, your new serveEvent for 9 find the server to be available and serves 9, but in that serveEvent the queue of the server has been reset to 0 even though 10 should still be in the queue. 

In this case, maybe you might want to check if your doneEvent updates the server from the Shop before actually freeing up the server, otherwise the queue from between the serveEvent and the doneEvent would not be saved.
