### ISSUE TITLE
Project 2 Level 5 Generating Rest Duration

### ISSUE THREAD

**Issue by limyapkai** [nus-cs2030/2021-s1#447]
Hi ! How is the rest duration generated? 

![image](https://user-images.githubusercontent.com/27536739/99764783-c2206d00-2b38-11eb-9334-2e650487bfc7.png)

![image](https://user-images.githubusercontent.com/27536739/99764832-d82e2d80-2b38-11eb-8536-41bc5d8413c5.png)

I Havent use the parameter restingRate anywhere. Wondering if someone could enlighten my fuzzy brain haha :)

**Comment by FergusMok** [comment]
Hello, your restingRate should be the last parameter of your RandomGenerator's constructor (var6 in the photo)
Then, you'll only need to compare RandomGenerator.genRandomRest() with the given probability of resting (Pr)
![image](https://user-images.githubusercontent.com/10182564/99765639-71aa0f00-2b3a-11eb-8a22-684205aae5f2.png)

**Comment by joelwongjy** [comment]
restingRate is supposed to be passed into RandomGenerator as the fourth parameter just like how you passed in arrivalRate and serviceRate. You should probably be calling genRandomRest somewhere in DoneEvent and if this is less than the probability of resting then the server goes to rest.

**Comment by merylseow** [comment]
You can do `this.rng = new RandomGenerator(seed, arrivalRate, serviceRate, restingRate)`

**Comment by limyapkai** [comment]
Hi All! Thank you for your inputs! Indeed I've forgotten to add the resting Rate into the RandomGenerator(...) >.<
However now Im getting these values:

![image](https://user-images.githubusercontent.com/27536739/99767873-c51e5c00-2b3e-11eb-8cdb-42181359d4f1.png)

**Comment by limyapkai** [comment]
Oh Ive resolved it. Lesson Learn, never ever call rng.genRestPeriod( ) like to store as a holding variable etc. It will mess up  the intended sequences of the time . *sigh *
