### ISSUE TITLE
Project 2 Level 3 (Bad class file)- despite following #377

### ISSUE THREAD

**Issue by coolieKi** [nus-cs2030/2021-s1#448]
# Description 
How can I resolve this?
I have followed the instructions in #377 
- Created a folder for cs2030
- Created a folder for simulator
- I copy and paste the RandomGenerator file into the simulator
- I run javac -d . *.java

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/72305170/99765670-81c1ee80-2b3a-11eb-8029-ab90500d369e.png)

**Comment by joelwongjy** [comment]
Are your class files created inside cs2030/simulator after you run javac -d . *.java? You don't actually have to create the folders cs2030 or simulator they will be automatically created for you.

**Comment by Terrence-F** [comment]
You might also want to check the permissions of the RandomGenerator file using chmod.
If that doesn't work, you can also attempt moving the file out of the directory and moving back in again and check the permissions once again (Not sure why but it helps in my case).

**Comment by ClementNgZiQian** [comment]
It seems that your Simulator.java is in ur home directory. RandomGenerator.java is actually default and not public, so u would not be able to access its constructor in Main.java directly. You need to add ur Simulator.java to package cs2030.simulator, then make this Simulator.java public and call it from ur Main.java

**Comment by patriciafzy** [comment]
I think you have to put your both 
```
import cs2030.simulator.RandomGenerator;
import cs2030.simulator.Simulator;
```
into your main instead, and not in your simulator. Simulator technically behaves like the other files and only has `package cs2030.simulator;` at the top!

**Comment by ClementNgZiQian** [comment]
The problem is even if u import cs2030.simulator.RandomGenerator; in ur Main.java, because the constructor for RandomGenerator is not public, you would not be able to do RandomGenerator rand = new RandomGenerator(x, y, z, w); in Main.java

**Comment by coolieKi** [comment]
> You might also want to check the permissions of the RandomGenerator file using chmod.
> If that doesn't work, you can also attempt moving the file out of the directory and moving back in again and check the permissions once again (Not sure why but it helps in my case).

Thanks man! I think this works for me
