### ISSUE TITLE
queuing error

### ISSUE THREAD

**Issue by yixin567** [nus-cs2030/2021-s1#450]
# Description 
i am currently stuck in level 4 and  apparently my status of my qmax is not changing even when the queue is full and i dont understand why because i always changes it.... 
![image](https://user-images.githubusercontent.com/66197880/99771269-cbfb9d80-2b43-11eb-8c94-da2bae88e0e6.png)
![image](https://user-images.githubusercontent.com/66197880/99771297-d6b63280-2b43-11eb-9aa9-5e33566240dd.png)

did anyone faced the same problem? 
been stuck in this level for 3 days:(((( 
thank you!!

**Comment by joelwongjy** [comment]
Are you getting the latest server status from the Shop in each event? You need to pull the latest server using Shop.find in each event.

**Comment by yixin567** [comment]
yep! i did it but it always says that the queue is not full..... @joelwongjy

**Comment by ClementNgZiQian** [comment]
What is ur implementation for qmax?

**Comment by yixin567** [comment]
i simply created another server that has a parameter that takes in a list of customer that is in the queue and a qFull to check if the queue is full anot when i add the customer in the arriveEvent! @ClementNgZiQian

**Comment by ClementNgZiQian** [comment]
Do you only add the waiting customers to the queue or also the ones being served.
Then when u transit from wait to serve do u remove them from the queue? or only after he is done.
It is possible that when you add to the queue it wasnt done properly.

**Comment by yixin567** [comment]
what i did was when the customer come, in the arriveEvent, i add it into my list and if my size of the list is the same as qmax, i will change the status to true which means that it is full. Then in my waiting list, i just didnt change my status and simply pass it to ServeEvent. In my Serve Event, i will then remove the customer from the list if i am serving the customer in the queue and change the status to false to show that it is not full and pass it to my doneEvent which does not change my status of the queue @ClementNgZiQian

**Comment by ClementNgZiQian** [comment]
You updated the server in Arrive Event, did you remember to update the shop also?
But since you shouldnt update your shop in Arrive Event, you should update the server and the shop in waitevent instead.
I suggest you try send it to the Wait Event, then do whatever you mentioned above in the Wait Event instead of Arrive Event

**Comment by yixin567** [comment]
@ClementNgZiQian i first had my WaitEvent updating the status of my server but the same issue occurred! and when i added the customer in the queue, it is printed out in the correct manner but is just that it is not changing the status as true. The function that i use to find the size of my list is just cl.size() == qmax which when i printed out, it is the same.....

**Comment by ClementNgZiQian** [comment]
Is it possible that ur qmax was set incorrectly? or did u not correctly reassign the updated server to the shop in Wait Event?

**Comment by yixin567** [comment]
@ClementNgZiQian 
![image](https://user-images.githubusercontent.com/66197880/99786638-b72a0480-2b59-11eb-90c8-b99721bfe46c.png)
i set my qmax as this which should be correct.... 
![image](https://user-images.githubusercontent.com/66197880/99786736-d163e280-2b59-11eb-9a8e-a6a5514a912d.png)
and this is what i did in my waitEvent when the queue is full

**Comment by ClementNgZiQian** [comment]
You can try adding a print statement after the 'if' line, then run the code again, if the statement doesnt print, it means ur id condition was not met.
If it prints, it may be how ur Arrive Events check the servers' queue

**Comment by yixin567** [comment]
okiees thank you!! @ClementNgZiQian 
can i ask right.... did u face this error in testcase 4_4 
![image](https://user-images.githubusercontent.com/66197880/99790061-87c9c680-2b5e-11eb-9b8e-6f35517b7cb9.png)

**Comment by ClementNgZiQian** [comment]
You probably did not update ur server properly after the done event

**Comment by yixin567** [comment]
@ClementNgZiQian okays thank you!!
