### ISSUE TITLE
Lab 8 Level 3 

### ISSUE THREAD

**Issue by FergusMok** [nus-cs2030/2021-s1#451]
Hello, I'm quite confused why service is not able to call findStopsWith. Isn't the service here a BusService?
My findStopsWith returns a CompletetableFuture<Set<BusStop>>.

![image](https://user-images.githubusercontent.com/10182564/99773123-ec792700-2b46-11eb-97c3-8c15f08e4b88.png)

**Comment by merylseow** [comment]
How about you try `CompletableFuture<Map<BusService, CompletableFuture<Set<BusStop>>>> validServices` instead?

**Comment by FergusMok** [comment]
Yup, thanks. That helped.
