### ISSUE TITLE
Project 2 bizarre error on CodeCrunch

### ISSUE THREAD

**Issue by bingmeow1999** [nus-cs2030/2021-s1#461]
# Description 
When I upload only the java files necessary for Levels 1 and 2, I can pass the test cases. However, when I upload all my files, I keep getting this weird error (see screenshot) and cannot even pass the first test case. Any idea what's happening? 

Extra info: My code compiles and runs fine on Ubuntu. The files that I didn't upload for the trial runs that passed Levels 1 and 2 are my main, the helper for the random generator, and event comparator.  

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
![java](https://user-images.githubusercontent.com/71839756/99850614-9fce3400-2bb8-11eb-998f-539f5e5a2a84.PNG)

**Comment by bingmeow1999** [comment]
![java2](https://user-images.githubusercontent.com/71839756/99850829-09e6d900-2bb9-11eb-87ab-10fb27e41916.PNG)
The issue seems to be with the event class and shop class, but when uploaded without main there are no issues.

**Comment by dtse2401** [comment]
I had a similar experience on jshell with this when I forgot to open Pair.java so perhaps you can check if it has something to do with this? Was pair uploaded and is it correctly imported/packaged?

**Comment by bingmeow1999** [comment]
Yup I checked multiple times that I uploaded everything. The thing that confused me the most is that it works fine without Main.java on codecrunch, but once Main is uploaded together everything goes wonky.

**Comment by bingmeow1999** [comment]
Problem solved. 
Lesson learnt, avoid naming conflicts with java API classes such as Random.
