### ISSUE TITLE
Project 2 Testcase 5_10 

### ISSUE THREAD

**Issue by patriciafzy** [nus-cs2030/2021-s1#462]
Does anyone know whats the testcase for this or know what's the problem? Previously I always managed to print out the testcase but this testcase overlaps with the previous ones too much so I am unable to do so. 

<img width="483" alt="Screenshot 2020-11-21 at 1 20 27 PM" src="https://user-images.githubusercontent.com/65544605/99868318-77682900-2bfc-11eb-8736-8ef0498bff16.png">

**Comment by aaron-ljx** [comment]
I only know 5_11's test case which is "2", "3", "10", "1000", "7", "1", "1", "1". Hope that helps.

**Comment by patriciafzy** [comment]
Hi @aaron-ljx , is it possible for you to send me the output for 5_11 testcases by running on your program? 

I think showing around the 10+ range customers will be good to see if it differs from mine, thank you so much!!

**Comment by aaron-ljx** [comment]
![Screenshot_2020-11-21 CodeCrunch](https://user-images.githubusercontent.com/70706659/99868788-a2547c00-2c00-11eb-9e68-19874b30963e.png)

Here is my output on CodeCrunch.

**Comment by chongweil907** [comment]
@patriciafzy 
![Uploading image.png…]()

**Comment by chongweil907** [comment]
@patriciafzy 
![image](https://user-images.githubusercontent.com/51086295/99869314-da5dbe00-2c04-11eb-991d-8c471ee01632.png)

**Comment by CWei88** [comment]
The error seems to be due to the Server_Rest event. When Server 1 finishes serving 1, the queue should still be full as the Server is taking a break and the remaining customers are queueing. At that point, the queue for Server 1 should be full and thus 9 shouldn't be able to join.

**Comment by patriciafzy** [comment]
Thank you everyone for your help! I have managed to clear it (:

**Comment by varshanaa** [comment]
hey can i ask how u resolved this issue?

**Comment by patriciafzy** [comment]
Hi @varshanaa, what i did was in ServeEvent, i compare the timing of this ServeEvent a with the allocated server's nextAvailTime (have to pull out from the shop again). If it is earlier, then i create another ServeEvent b and pass it into the queue again and NOT print this serveEvent a!
