### ISSUE TITLE
Project 2 Level 6 

### ISSUE THREAD

**Issue by patriciafzy** [nus-cs2030/2021-s1#467]
Hi, my implementation for level 6 is as such: 

At each loop of the priority queue, I check the timing of my event vs the selfcheck server next Available Timing and if the event timing is later, I proceed to serve. However, the order of the serving for self check are mixed up. 

<img width="363" alt="Screenshot 2020-11-22 at 12 43 59 AM" src="https://user-images.githubusercontent.com/65544605/99882492-d446fc00-2c5b-11eb-9eed-47c4763b2ae4.png">

^ 14 goes to self-check 3 because it has an earlier time when it was queuing BUT in actual fact the end time of self-check 3 is later. Hence, my result is 

<img width="283" alt="Screenshot 2020-11-22 at 12 47 08 AM" src="https://user-images.githubusercontent.com/65544605/99882552-44558200-2c5c-11eb-9f6a-66a2d1b8cce5.png">

when it should be: 

<img width="302" alt="Screenshot 2020-11-22 at 12 47 22 AM" src="https://user-images.githubusercontent.com/65544605/99882557-4d465380-2c5c-11eb-9a1e-72ec75ed2664.png">

Does anyone with similar implementation manage to get pass this error? Otherwise, is there a better way of implementation? thank you!

**Comment by e0420658** [comment]
hi! i had faced this exact error previously and that was because i missed out on a line of code which takes care of the updating of the waiting customers in the queue. maybe you can look into your updates in the serve event and done event!

**Comment by patriciafzy** [comment]
Hi @e0420658! May I know what do you mean by "updating of the waiting customers in the queue"? Cuz rn the order is different and im not sure what do you mean haha

**Comment by e0420658** [comment]
im not sure whats your implementation but for me when i was missing a "-1" to the selfcheckout queue when my customer is being served by a selfcheckout. So maybe you could check in your code whenever you update the selfcheckout queue, make sure its done correctly where you only "-1" when the waiting customer is indeed being served and not rescheduled to another serve event. Hope this helps!

**Comment by Josephaedan** [comment]
If I’m not wrong your implementation assigns 14 to self-checkout 3 at the start. But ideally you should be checking for the self-checkout counter with the earliest available time and assigning 14 to that counter. So you should be checking later on in the schedule which counter ends the earliest and returning a serveEvent for 14 with that designated server.

**Comment by qiiwen** [comment]
hello! i think the problem lies in assigning server based on nextAvailableTime since it does not account for how many people are in the queue. u will notice that while self check 3 has the earliest nextAvailableTime, there is already customer 13 waiting in queue and nextAvailableTime is the time where customer 13 is served, not customer 14. it would be better to just make all the self checkout counters share the same queue without assigning at the start, then decide on which customer to serve only after a DoneEvent or ServerBackEvent. hope this helps!

**Comment by joelwongjy** [comment]
Adding on to @Josephaedan suggestions, it is fine to assign 14 to the self-checkout 3 first. However, what you need to make sure to do in ServeEvent is to reassign 14 to the earliest self-checkout server. (You are coming from a WaitEvent). 

It does not matter which server 14 is assigned to now, but you need to check in the shop again and retrieve the earliest self-checkout, and return a new serve event with 14 and this earliest checkout. I did this with a method in Shop that filters the servers for SelfCheckout and gets the earliest time using .min. So I simply call this method on the Shop in ServeEvent.

**Comment by patriciafzy** [comment]
Thank you guys so much for the help!! I cleared the level ((:

**Comment by domlimm** [comment]
> hello! i think the problem lies in assigning server based on nextAvailableTime since it does not account for how many people are in the queue. u will notice that while self check 3 has the earliest nextAvailableTime, there is already customer 13 waiting in queue and nextAvailableTime is the time where customer 13 is served, not customer 14. it would be better to just make all the self checkout counters share the same queue without assigning at the start, then decide on which customer to serve only after a DoneEvent or ServerBackEvent. hope this helps!

Hi @qiiwen just to check, in your last statement you said to decide on which customer to serve only after a DoneEvent or ServerBackEvent, as for the DoneEvent, wouldn't that cause a cyclic dependency? Like from SE -> DE -> SE. I actually did that for mine. May I ask how you approached that issue if you did face it?

Sorry Patricia, gonna leave it here... I'm actually stuck on #476 currently

**Comment by patriciafzy** [comment]
Hi @domsterthebot, I actually followed qiiwen's approach and put it under my Simulator (might be main for you?)! So for example, when i polled the queue and if instanceof event polled is a DoneEvent and has a selfcheck counter, I just immediately serve the next waiting customer in line!

**Comment by domlimm** [comment]
Hi @patriciafzy I've a Simulator class that does the work with a method of simulateNextEvent. That's besides the point, 

Anyway, yup I've a Customer Queue specifically for selfCheckout/its queue located in Shop, where the queue is always accessible in all sub Event classes.

From what you say "if instaceof event polled is a DoneEvent and has a selfcheck counter..." i suppose your Event class has a Server variable and a getter for it?

Could you please take a look at #476 if you've the time! 😢
