### ISSUE TITLE
Windows Subsystem for Linux 2 may cause laptop ethernet cable to stop working.

### ISSUE THREAD

**Issue by TypeDefinition** [nus-cs2030/2021-s1#47]
On the official Microsoft WSL installation guide (https://docs.microsoft.com/en-us/windows/wsl/install-win10), there is a step on updating to WSL 2 which requires enabling the 'Virtual Machine Platform'. There is a chance that doing will result in your laptop being unable to connect to the internet via an Ethernet cable. 

If you are facing this issue, revert back to WSL 1 and disable the 'Virtual Machine Platform'.

To disable 'Virtual Machine Platform',
Go to 'Control Panel/Programs/Turn Windows features on or off'
and uncheck 'Virtual Machine Platform'.

![image](https://user-images.githubusercontent.com/13763067/92550169-842be080-f28d-11ea-983b-98c93cfa5823.png)

**Comment by darrenhoon** [comment]
Thanks for the heads up. I was contemplating on updating but I guess that's out of the question for now

**Comment by TypeDefinition** [comment]
> 
> 
> Thanks for the heads up. I was contemplating on updating but I guess that's out of the question for now

np :)
