### ISSUE TITLE
Proj 2 test case 6_7

### ISSUE THREAD

**Issue by jiexilim** [nus-cs2030/2021-s1#470]
![image](https://user-images.githubusercontent.com/70773974/99887517-08341880-2c80-11eb-8ded-4c78b11770ca.png)
Hi, any idea for this issue? I am not sure how to fix this, i got cust 15 served by 4 but done serving by 3.
What I did was:
In wait event, if it's a self-check counter, then i get the one with the smallest next available time to serve the customer.
In serve event, for self-check counter, i get the one with smallest next available time and check its availability then serve the customer.
Would appreciate any help :<

**Comment by patriciafzy** [comment]
Hi, I am not very sure what's your implementation but perhaps you can type `System.out.println(customer.getServer())` to get the servers and check if it's the right one. Looking at what you said, perhaps during the waitevent and serveevent, the server with the smallest next available time is different and hence, it gives you different servers?
