### ISSUE TITLE
Project 2 Level 3...

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#472]
Been stuck on fixing this level for days and desp need help... Server 1 seems to automatically become available even before it is done serving, thereby preventing server 2 from ever being called. Obviously something is wrong with my execute()/server updating logic, but I can't figure it out...

![image](https://user-images.githubusercontent.com/39799639/99894481-0b022e00-2cbf-11eb-94bf-3afadb9e850e.png)

**Comment by CWei88** [comment]
Did you remember to update the Shop, like when 5 is being served, did you replace server 1 in shop to become unavailable, so that the shop passed into server 6 arrive Event is updated
