### ISSUE TITLE
Project 2 level 1/2

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#474]
Hi there regarding the project, prof mentioned that we had to proceed with the project in a certain manner mentioned on cc for Level 1 and 2. Anyone has any ideas how to store/update the status of the servers now? For part 1, I used a static variable to check the status of each server in each event but i think if i were to continue that now it will be too troublsome. Anyone has any idea how to keep track of the states of the servers/events taking into consideration the new restrictions set on cc? Thank you!!

**Comment by yusufaine** [comment]
You can either use enums or check if an Event is an instance of its subclass (Arrive, Wait, Serve, Done, Leave) and proceed accordingly. 

I think how you do it might still be possible though.

**Comment by dljw98** [comment]
Not sure if I interpreted your question properly, but if you take a look at level 3, one of the ways to do it is in the Function of each Event. You can do it through if-else statements

**Comment by qiiwen** [comment]
u can just return it in your Event's function, which will return a new shop with the updated server upon calling execute(). then u can pass the new shop along the following Events and find your updated server required through server id .

**Comment by weiyifei-evelyn** [comment]
You may want to include a function property when designing Event class. Then every sub-event class i.e. arrive, server etc will have this property. Inside the function, you may write how you return Pair and how you update server status etc.

**Comment by kohkenneth** [comment]
@weiyifei-evelyn @dljw98 @yusufaine @qiiwen Thanks for the input guys!!
