### ISSUE TITLE
Lecture 4 on Superclasses

### ISSUE THREAD

**Issue by kelpal** [nus-cs2030/2021-s1#48]
Hi! If I have a superclass A that implements interface B, and several subclasses (e.g. C) that inherit from superclass A, then must I write `class C extends A implements B`, or can I just write `class C extends A` and it will be taken that C will also be able to implement the methods from the interface B? Thanks!!

**Comment by charoi** [comment]
Hi! @kelpal interesting question! Did some digging and found this.
[Query on superclass and subclass implementation](https://stackoverflow.com/questions/31261906/what-happened-when-subclass-and-superclass-both-implement-a-same-interface)
![ans](https://user-images.githubusercontent.com/41200981/92554138-37e59e00-f297-11ea-95d4-c426d671dd49.png)

Above should be the answer! And if the superclass implements an interface, they must define the methods in the interface. I would imagine the subclass simply extends all those methods so if the subclass UnitCircle wants to getArea, and the class Circle implements Shape, which has the abstract method getArea, UnitCircle can use the getArea method defined in Circle.

If UnitCircle wants its own implementation of Shape, it would work like overriding a superclass method? Maybe someone can answer me on this!

Hope this helps

**Comment by lkldev** [comment]
great answer @charoi, and yes, if UnitCircle wants its own implementation of Shape, they can simply override the methods they would like to override. As to whether or not your child should write the `implements B`, you might want to still have your subclass implementing the interface, in cases where you might remove (accidentally or intentionally) the interface from the parent class. 
You may read more about it [here](https://stackoverflow.com/questions/5668429/why-would-both-a-parent-and-child-class-implement-the-same-interface#:~:text=4%20Answers&text=answer%20was%20accepted%E2%80%A6-,As%20I%20understand%20interfaces%20(and%20my%20experimentation%20has%20reinforced)%2C,Technically%2C%20it%20is%20completely%20redundant.).

Do refer to #46 as we have a similar discussion there as well :)

**Comment by kelpal** [comment]
@lkldev @charoi thank you so much for the help! :D
