### ISSUE TITLE
Overloading and Overriding Static Method

### ISSUE THREAD

**Issue by jedlwk** [nus-cs2030/2021-s1#481]
# Description 
From all the labs and projects that we did, I came to realize that I can overload a static method but I cannot override a static method. 

I understand that this is related to how the method being a compile-time type and a runtime type. However, I am still quite confused about this, and does anyone has a simpler way of explaining this and possibly throw some examples? 

Thank you so much!

**Comment by varshanaa** [comment]
A static method belongs to the class and not the instance of a class; it's accessed directly by the class name. I think because it’s specific to the class, you can’t override it in subclasses, but you can have a static method with the same signature in subclasses.

**Comment by jedlwk** [comment]
Right, I realized I can declare the same static method in a subclass but I cannot override it. Thanks
