### ISSUE TITLE
Error doing screen recording

### ISSUE THREAD

**Issue by charoi** [nus-cs2030/2021-s1#483]
# Summary
Command not working

Hi! I tried doing the screen recording using FFmpeg on my windows laptop but it seems one of the commands does not work for me? Anyone knows a workaround for the command?
Heres the link to the SoC exam protocol to refer to the command I was looking at: [Screen Recording Software](https://mysoc.nus.edu.sg/academic/e-exam-sop-for-students/#_screen_recording_software)
![error](https://user-images.githubusercontent.com/41200981/100071387-f5833480-2e75-11eb-9a6b-e9e2918dbe35.png)

**Comment by Terence-Sim** [comment]
In your command line, you are missing a "1" after "-threads".

**Comment by charoi** [comment]
@Terence-Sim ah ok thanks prof!! Oop my bad :,)
