### ISSUE TITLE
Lab 8 Level 4

### ISSUE THREAD

**Issue by oolongmilkteax** [nus-cs2030/2021-s1#485]
I'm abit confused at this level. Are we suppose to change the variables in main class to CompletableFuture objects??

**Comment by jedlwk** [comment]
Yes! More specifically, you need to change what's in the while loop over here.

![image](https://user-images.githubusercontent.com/65217862/100080605-fe2d3800-2e80-11eb-9b62-f336418d1d26.png)

You need to 'construct all the promises as CompletableFuture objects' for the variables called by the System.out.println command.

**Comment by oolongmilkteax** [comment]
Thanks for the comment!
