### ISSUE TITLE
Lab 8 Level 1

### ISSUE THREAD

**Issue by changziming** [nus-cs2030/2021-s1#486]
# Description 
I am not very sure on how to start this level, but i tried to code something out. However, after downloading and running the .jar file, i got this exception
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.lang.String BusAPI.getBusServicesAt(java.lang.String)'
        at BusSg.getBusServices(BusSg.java:23)
        at BusSg.findBusServicesBetween(BusSg.java:45)
        at Main.main(Main.java:23)
```
Im not very sure what im doing wrong

**Comment by charoi** [comment]
@changziming the compiler is saying that there isn't a method called `getBusServicesAt` in **BusAPI** that takes in a string and returns a string. I think u have yet to modify your return type of `getBusServicesAt` to return a `CompletableFuture<String>`

**Comment by changziming** [comment]
@charoi I already changed both the return types of  `getBusStopsServedBy` and `getBusServicesAt` to CompletableFuture<String>, but im still getting that error.

**Comment by jedlwk** [comment]
@changziming maybe you can check your httpGet? 

actually if you are at level 1 you shouldn't touch your Main and BusSg file yet thoo :/ 

can you try to just compile just your BusAPI file?  `javac -Xlint:rawtypes BusAPI.java`

last resort is see if you can submit to codecrunch and check if it gives any error when you just submit your BusAPI file?

**Comment by changziming** [comment]
@jedlwk This is my implementation of httpGet. Im not sure about my `response.thenApply()` 
![image](https://user-images.githubusercontent.com/57001713/100104821-9f2beb00-2ea1-11eb-8aa6-42d278f3a70c.png)

**Comment by jedlwk** [comment]
You do not need to declare the response anymore so the line after HttpRequest is redundant. 

Your response.thenApply is very close to the actual implementation. You can take a look at mine here: 

![image](https://user-images.githubusercontent.com/65217862/100108641-f5029200-2ea5-11eb-8e86-c0953ea7226f.png)

Do remember to catch the error after this!

**Comment by changziming** [comment]
Okie thanks!
