### ISSUE TITLE
Lab 8 level 3

### ISSUE THREAD

**Issue by changziming** [nus-cs2030/2021-s1#490]
# Description 
Hi for lab 8 level 3, For the description method in BusRoutes, how can i change the result from String to CompletableFuture<String>? I tried doing this `CompletableFuture.supplyAsync(() -> result)` then altering the result but i dont think thats correct.

**Comment by gabrielloye** [comment]
When you are altering the result (I assume this is the base String, i.e. "Search for: ... <-> ", you should work with combining it with the `CompletableFuture<String>` returned from the `describeService` method using something like `thenCombine`

**Comment by e0420658** [comment]
for the description method you can return CompletableFuture.completedFuture("result")

**Comment by changziming** [comment]
Thanks everyone!
