### ISSUE TITLE
Answers for Past Year Papers

### ISSUE THREAD

**Issue by Chen-Yiyang** [nus-cs2030/2021-s1#491]
## Description 
We are able to get the question paper for PYP from library website. However, no answers are given. 

Therefore, I would like to clarify with the CS2030 staff, whether there is a way for us to get the answers (so that we can self-mark PYPs and prepare for the exam). 

Thank you

**Comment by xingaporean** [comment]
there is no ans for pyp generally, need discuss

**Comment by TarciusW** [comment]
i believe the intention is for us to post our discussions here! peer learningso no answers will be provided

**Comment by Chen-Yiyang** [comment]
I see. Thanks everyone for the clarification!
