### ISSUE TITLE
Lab 6 return type of printlog()

### ISSUE THREAD

**Issue by weiyifei-evelyn** [nus-cs2030/2021-s1#496]
Hi, could anyone give me a hint on the return type of printlog()? I am thinking about returning a String but it doesn't seem to fit the desired output: (they are in separate lines and I'm not so sure whether they should be strings or not.
Value initialized. Value = 5
Value changed! New value = 6
Value changed! New value = 5

Thank everyone in advance!

**Comment by jedlwk** [comment]
Yes, the return type is a string. You will need to include a List of Strings in your constructor that will store the various strings that you have identified above. 
Your output will go through the strings inside your List and print them out when you call printlog().
 
Here's my code for your reference.
![image](https://user-images.githubusercontent.com/65217862/100314070-d0670100-2ff0-11eb-8220-8c189a250673.png)

**Comment by weiyifei-evelyn** [comment]
@jedlwk I see!!! Thank you for your quick reply 👍
