### ISSUE TITLE
Lambda Expressions

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#498]
# Description 
hello does anyone know the answer and explanation for the sequence in which the lambda expressions are evaluated? 
i would think its efgcefgc but im not too sure

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/71011712/100323966-80dd0100-3001-11eb-9491-1aff85ef0cb2.png)
![image](https://user-images.githubusercontent.com/71011712/100324007-8fc3b380-3001-11eb-969e-87436538cfc5.png)

**Comment by xingaporean** [comment]
edit: oops read wrongly, thought i saw a stream

**Comment by jedlwk** [comment]
I think the answer is fgce fgce ? correct me if I'm wrong but i think one lambda expression does not call another lambda expression

**Comment by kohkenneth** [comment]
i think its cegf cegf/ cefg cefg?

**Comment by xingaporean** [comment]
lmao we have 4 different answers

**Comment by bentanjunrong** [comment]
According to my senior, the answer was: fgce fgce, but I'm a bit confused as to why it isnt fgcefgce**fgc** because I thought the map/forEach() would evaluate regardless on the LazyList.empty()

**Comment by e0420658** [comment]
sryy im still not sure why its fgcefgce?

**Comment by waynetee** [comment]
@e0420658 before c can run, g must be run, before g can run f must be run to supply the value to the next function
@bentanjunrong the evaluation is done in a ()->... so the ... is not run until the result is needed

**Comment by e0420658** [comment]
ahh i see! thanks everyone!!!
