### ISSUE TITLE
Project 2 Level 7 TestCase 7_7

### ISSUE THREAD

**Issue by limyapkai** [nus-cs2030/2021-s1#502]
I did a comparison between all the Servers ( that has no Waiting Customers ) and the K+1 Self CheckOut Server by comparing thier respective queue sizes. Although I did multiple variations, this error keep flagging out. Am I missing something? hmm

![image](https://user-images.githubusercontent.com/27536739/100335710-4038b400-3010-11eb-941b-0492de31205f.png)

**Comment by limyapkai** [comment]
Oh here is an update. I forgot to check for MaxQueueLength... So after I did the check here is the result, Arghhh so close.

![image](https://user-images.githubusercontent.com/27536739/100337269-213b2180-3012-11eb-8619-e3106d6bbe7e.png)

**Comment by rezlite** [comment]
You might want to print out the maxQueueLength at every arrive event especially self-check 3, and check whether its full.

If you're certain its full/correct, the problem could lie on your arriveEvent logic when the customer arrives.

**Comment by Mildred-ui** [comment]
Hi, you may want to check how u updated the Server (e.g. maybe the replace() in Shop). I had the similar error, turns out I didn't ensure that all self-severs share the same MaxQLength.

**Comment by limyapkai** [comment]
@majopok @Mildred-ui  Thank you all! Managed to solve it. I forgot to add another condition to compare between Self-Checkout and Normal Server :)
