### ISSUE TITLE
How to Uninstall Fedora SoC

### ISSUE THREAD

**Issue by eviehwy** [nus-cs2030/2021-s1#506]
Hi all, does anyone know if there are any instructions given on how we can un-boot/uninstall Fedora SoC from our drive? I bought a brand new thumb drive for this and I will wish to restore it back to its original state so that I can make use of it :P Can't seem to find much help online as I am using a mac

**Comment by kohkenneth** [comment]
Maybe you can try this!
https://discussions.apple.com/thread/5647115#:~:text=Connect%20the%20drive%20to%20your,t%20be%20detected%20on%20Windows.

If not, I think if you load an image again use the Fedora Media Writer software, after the new image is loaded, I think they will prompt you if you want to clear the existing image on the drive. Have not personally tried this method but I remember seeing this option after booting the image previously so maybe you can try this out!

**Comment by KeithCZW** [comment]
Yup, just load up Fedora Media Writer and they will prompt you to factory reset your thumbdrive.

**Comment by jj-weng** [comment]
So for Windows should be the same steps as above also right?

**Comment by kohkenneth** [comment]
@jj-weng yup windows should be the same. if not, i think you can try using the methods on this site: https://answers.microsoft.com/en-us/windows/forum/all/how-to-convert-bootable-usb-back-to-normal-with/a1f991fb-7169-4f5c-931f-b07edd2dc31c

**Comment by limyingying2000** [comment]
Hi, if you are using Macbook, the following link might be helpful to format your thumbdrive. Hope it helps!!
https://www.youtube.com/watch?v=-dQBftQufS4&ab_channel=Tech%26Design

**Comment by Jiwei99** [comment]
Hi if you are using Mac, can just use Disk Utility to erase the drive. The Fedora Media Writer removal method doesn’t seem to work for me. I used Disk Utility and I was able to erase and get back a working thumb drive. https://support.apple.com/en-sg/guide/disk-utility/dskutl14079/mac

**Comment by SethCKL** [comment]
Using the fedora media writer would be the easiest.

Either that or u can use disk management or command prompt for win10
https://www.windowscentral.com/how-format-usb-flash-drive-windows-10
