### ISSUE TITLE
PYP AY17/18 Midterms Q8

### ISSUE THREAD

**Issue by jj-weng** [nus-cs2030/2021-s1#510]
`#` Description 
Describe the question  
Hi , does anyone know why the answer to the question below is D? Doesn't hotel throws an exception, causiing exception(van) to be printed out? Thanks in advance!

8. (3 points) Consider the code below. InterruptedException is a subclass of Exception.
```
class Inception {
public static void main(String args[]) {
 van();
}
static void van() {
 try {
  System.out.println("van");
  hotel();
 } catch (Exception e) {
  System.out.println("exception (van)");
 }
}
static void hotel() throws InterruptedException {
 try {
   System.out.println("hotel");
   snowFortress();
 } catch (Exception e) {
   System.out.println("exception (hotel)");
 }
}
static void snowFortress() throws InterruptedException {
  System.out.println("snow fortress");
  limbo();
}
static void limbo() throws InterruptedException {
  throw new InterruptedException();
 }
}
```
Which of the following string will NOT be printed when we invoke the main class Inception?
A. van
B. hotel
C. snow fortress
D. exception (van)
E. exception (hotel)
Write X in the answer box if every string above is printed.

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by leeleonard98** [comment]
I think in this case when hotel calls throws InterruptedException, it just means this method could have this exception and it doesnt necessarily mean there is an exception. Unlike in limbo, where there is a new instance of exception created with the keyword being `new InterruptedException()`. So hotel itself has already use the try catch to catch the exception in Limbo so d wont be printed

**Comment by leeleonard98** [comment]
And also ur program should stop at the catch error of hotel

**Comment by limyingying2000** [comment]
<img width="577" alt="Screenshot 2020-11-27 at 6 15 03 PM" src="https://user-images.githubusercontent.com/65782648/100437939-7a6f8780-30dc-11eb-8f73-8ac326ea107d.png">

Hotel method doesn't throw the exception since the catch handles and not throws the exception in the catch block, thus van method will not catch any exceptions.

**Comment by jj-weng** [comment]
Okay thanks all!
