### ISSUE TITLE
Project 2 lvl 6

### ISSUE THREAD

**Issue by yaphuiyi** [nus-cs2030/2021-s1#512]
Did anyone have the same problem of customer 14 being served after customer 15 for level 6 of project 2? My implementation is that in my Wait Event, if the customer is waiting to get served by self checkout counters,  it will find the earliest nextAvailableTime of all the self checkout servers and execute a serve event. 

This is my output 
![image](https://user-images.githubusercontent.com/62334893/100448612-857ee380-30ed-11eb-8d0a-c784f0ad5c05.png)

And this is the correct output
![image](https://user-images.githubusercontent.com/62334893/100448892-fa521d80-30ed-11eb-8613-153401df6b29.png)

**Comment by CWei88** [comment]
Since self-checkout counters have a common queue, you will need to order the event such that 14 comes before 15, since they would have the same earliest next available self-checkout counter.

**Comment by yaphuiyi** [comment]
@CWei88 Thank you for your input! Do you have any idea on how to go about doing this? Got stuck for quite a while already ><

**Comment by e0420658** [comment]
#467 can take a look at this issue where the same problem was mentioned!

**Comment by yaphuiyi** [comment]
@e0420658 Thank you! Managed to solve the level :)
