### ISSUE TITLE
Project 2 Level 3

### ISSUE THREAD

**Issue by edwin716** [nus-cs2030/2021-s1#516]
Hi I'm currently facing an issue whereby the timings for my DoneEvent is wrong. From what I see, it seems that the service time generated is wrong but I'm not sure why this is the case. Would appreciate any inputs thanks!

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/65332564/100461095-3e035200-3103-11eb-8d45-83d87a7ec7b1.png)

![image](https://user-images.githubusercontent.com/65332564/100461148-52dfe580-3103-11eb-9992-4d6eb8f322c2.png)

**Comment by hengyiqun** [comment]
Did you call genServiceTime() multiple times inside this class, or at multiple events?

**Comment by hengyiqun** [comment]
On a side note, I think you need to change the output such that it is "done serving by server 1" instead of "done serving by 1".

**Comment by edwin716** [comment]
> Did you call genServiceTime() multiple times inside this class, or at multiple events?

I used it another time in my DoneEvent to update the next available time for the server. Could that be the issue?

**Comment by edwin716** [comment]
> On a side note, I think you need to change the output such that it is "done serving by server 1" instead of "done serving by 1".

Oh ok thanks!

**Comment by sdas04** [comment]
Hi, I think the next available time for the server would be the same as the start time of the DoneEvent?

**Comment by hengyiqun** [comment]
Yup, I think you should only call genServiceTime() only in one class, and only once.

![image](https://user-images.githubusercontent.com/20364508/100469160-b7ee0800-3110-11eb-9bcd-eb20ecdbba4a.png)

Currently, the service time for your 3rd server is 1.359 - 1.205 = 0.154. This is exactly the difference between the actual service time for the 5th sever (4.031 - 3.877 = 0.154) (see image above). This is probably because you called genServiceTime() about twice the number of times needed.

If I am not mistaken, you will need to update your code slightly to prevent the case of having to call genServiceTime() more than once for each server.

**Comment by edwin716** [comment]
> Hi, I think the next available time for the server would be the same as the start time of the DoneEvent?

Yeah I just realized it thanks!

**Comment by edwin716** [comment]
> Yup, I think you should only call genServiceTime() only in one class, and only once.
> 
> ![image](https://user-images.githubusercontent.com/20364508/100469160-b7ee0800-3110-11eb-9bcd-eb20ecdbba4a.png)
> 
> Currently, the service time for your 3rd server is 1.359 - 1.205 = 0.154. This is exactly the difference between the actual service time for the 5th sever (4.031 - 3.877 = 0.154) (see image above). This is probably because you called genServiceTime() about twice the number of times needed.
> 
> If I am not mistaken, you will need to update your code slightly to prevent the case of having to call genServiceTime() more than once for each server.

I have changed my code such that genServiceTime() is only called in the ServeEvent constructor now as shown in my initial post but I'm still facing the same issue. Could you elaborate abit more about the last line?

**Comment by leeleonard98** [comment]
Can i see ur updated code? And also u need to make sure u only call servicetime when it is being served and no where else even for done event. For your done event u need to remove that service time cos other wise u will be calling it twice and thats the reason why they hinted to use lazy

**Comment by edwin716** [comment]
> Can i see ur updated code? And also u need to make sure u only call servicetime when it is being served and no where else even for done event. For your done event u need to remove that service time cos other wise u will be calling it twice and thats the reason why they hinted to use lazy

![image](https://user-images.githubusercontent.com/65332564/100494168-14394200-317a-11eb-948d-5e16fc6332ac.png)
![image](https://user-images.githubusercontent.com/65332564/100494185-3f239600-317a-11eb-8cb5-3afdb920706f.png)

**Comment by edwin716** [comment]
Ok I managed to solve the issue already. It's because I called the execute method twice for my simulate method in the EventSimulator, which is possibly why the genServiceMethod() was called twice. Thanks for the inputs everyone appreciate it!
