### ISSUE TITLE
Project 2 Level 6 self-checkout implementation

### ISSUE THREAD

**Issue by fionacheong** [nus-cs2030/2021-s1#520]
Hi, I was wondering for the self-checkout counters in level 6, do i have to put all the servers (both normal and self check-out) in the same server list inside the shop? And if so how should i go about initialising such a list with two different types of servers using streams?

Thanks!

**Comment by kohwenjie** [comment]
hi @fionacheong , you can just make use of the same server class and add a Boolean flag to indicate if it is a self check out or a normal server. That way you can continue with you current implementation. You can add the normal servers first then add the self check out servers in that order using 2 different streams. Hope this helps!

**Comment by thmtiffany** [comment]
Alternatively you can have a child class that inherits the Server class to implement the self checkout, which would also allow you to put the self checkouts into the same list as the servers.

**Comment by zechajw** [comment]
The idea is to abstract the common functionality between the Server and SelfCheckout into a superclass (E.g. Counter), so that the shop can hold a list of the superclass without differentiating between server or selfcheckout.

**Comment by SkyBlaise99** [comment]
Of cuz, if you really want, you can use 2 lists

**Comment by fionacheong** [comment]
Thanks for your help guys!
