### ISSUE TITLE
Lab 8 Level 4 Slow Output

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#523]
I did pass the test case on Codecrunch, but my main() method took 18.9s to finish getting the results, meaning I must have processed my CompletableFutures inefficiently. However, I do not really understand why my code is inefficient. What did I do wrong here?
<img width="949" alt="Screenshot 2020-11-27 at 9 33 24 PM" src="https://user-images.githubusercontent.com/39799639/100456181-e95bd900-30fa-11eb-8acc-9dcd8ff6097d.png">

**Comment by SkyBlaise99** [comment]
Call `join` outside the while loop, mine took like 8s only

**Comment by EssWhyy** [comment]
@SkyBlaise99 Ok, I'll try that out, thanks!
