### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by kohkenneth** [nus-cs2030/2021-s1#529]
Hi, anyone know what might be the cause for this error? 

![image](https://user-images.githubusercontent.com/62513460/100514810-9d6c6b00-31b2-11eb-81eb-2086eb5e0a03.png)

I've checked my Program, Event and Main class and nothing seems to be off but I keep getting this NullPointerException error. Thanks in advance!

**Comment by kohwenjie** [comment]
@kohkenneth hi is it ur doneevent return a null then you never handle in your priorityqueue? aka you add a null into you queue

**Comment by itsyme** [comment]
It is probably a null that has not been removed from your queue

**Comment by kohkenneth** [comment]
@itsyme @kohwenjie oh yes i forgot to check that. Thanks for pointing it out! Have been trying to find the problem for a few hours :-(
