### ISSUE TITLE
are Assertions tested?

### ISSUE THREAD

**Issue by kohwenjie** [nus-cs2030/2021-s1#534]
Hi, i noticed that there are questions regarding using assert statements in the pyp like the one i attached. Just want to check, is this something which we were taught and are they tested for our exams? I kinda dont remember learning about them :(

![image](https://user-images.githubusercontent.com/70895902/100517448-871bda80-31c5-11eb-8472-11057bd9c406.png)

**Comment by Terence-Sim** [comment]
Assertions are not tested.

**Comment by kohwenjie** [comment]
@Terence-Sim okay thank you for the clarification!
