### ISSUE TITLE
Project 2 Level 4

### ISSUE THREAD

**Issue by edwin716** [nus-cs2030/2021-s1#535]
Hi, I'm currently facing this issue whereby there are 2 customers being served by the same server at the same time. I have looked through previous comments by others and kind of understand what's wrong with my code. I have tried to work on it but still not sure whether I would need to edit my code in ServeEvent or WaitEvent. Would appreciate any inputs thanks!

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/65332564/100519106-cd2a6b80-31d0-11eb-9bee-66293a4e3940.png)

**Comment by domlimm** [comment]
Hi edwin, the whole point here is to reschedule Customer 10 to be served right after Server 1 is done serving Customer 9.

Both Customer 9 & 10 were previously in a WaitEvent i assume, so Customer 9 moves from a WaitEvent to a ServeEvent tagged to Server 1. Maybe you can think of it this way i.e. Customer 10 WaitEvent, returns another new WaitEvent @ 10.781.

So Customer 10 will transit from WaitEvent to ServeEvent @ 10.781.

**Comment by varshanaa** [comment]
hey, i had the same issue as well. kind of did the same thing as what's suggested ^. how i solved it was before executing a ServeEvent, i checked whether the next available time of the server in the shop is more than the start time of your current ServeEvent. if it is, then create a new ServeEvent with the updated next available time of the server, and add it to the queue. also, remember not to print out the first ServeEvent which has the wrong timing.

**Comment by edwin716** [comment]
> hey, i had the same issue as well. kind of did the same thing as what's suggested ^. how i solved it was before executing a ServeEvent, i checked whether the next available time of the server in the shop is more than the start time of your current ServeEvent. if it is, then create a new ServeEvent with the updated next available time of the server, and add it to the queue. also, remember not to print out the first ServeEvent which has the wrong timing.

I tried something like you mentioned but the issue still persists. Maybe could you see what's wrong here?
![image](https://user-images.githubusercontent.com/65332564/100520879-4929b100-31db-11eb-9c5f-c55847faae25.png)

**Comment by edwin716** [comment]
> Hi edwin, the whole point here is to reschedule Customer 10 to be served right after Server 1 is done serving Customer 9.
> 
> Both Customer 9 & 10 were previously in a WaitEvent i assume, so Customer 9 moves from a WaitEvent to a ServeEvent tagged to Server 1. Maybe you can think of it this way i.e. Customer 10 WaitEvent, returns another new WaitEvent @ 10.781.
> 
> So Customer 10 will transit from WaitEvent to ServeEvent @ 10.781.

Hmm I tried doing this but doesn't seem to work so now I'm working on the method below instead. Thanks anyways!

**Comment by varshanaa** [comment]
the server you pass in is from the previous event right, so the start time for the event is going to be the same as the time you get from server.getNextAvailableTime(). instead, i think you need to check the most updated timing of this server, so something like shop.find(x -> x.getID() == server.getID()).getNextAT() should return the updated timing.

**Comment by ong6** [comment]
You could try creating another event here to help extend the waiting time. Really helps with the later levels as well since this means that the wait event has fewer things to handle.

**Comment by itsyme** [comment]
I think you should not add the service time when you are just updating it in the first part if not you may add the service time twice

**Comment by GJ0407790** [comment]
Hi, I think you can slightly modify ur program flow, i.e. such that the Serve Event is not triggered by the Wait Event, instead could be triggered by a Done Event.

**Comment by edwin716** [comment]
Thanks for the suggestions everyone, I managed to solve it already using @varshanaa 's method.
