### ISSUE TITLE
MCQ Answers for AY17/18 Finals?

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#536]
Has anyone attempted the MCQs from the AY17/18 Sem1 & Sem2 Finals? Would like to cross check my answers with anyone else who has done them

I didn't answer questions on RecursiveTask since it's not taught this sem (indicated with '-')

My answers:

AY17/18 Sem1
C,D,B,A,A,E,B,D,E,A,-,-
AY17/18 Sem2
D,E,D,B,A,E,E,B,C,-,A,C

**Comment by tomjoju** [comment]
Hi! These were the answers for the Sem 1 Paper a few of my friends and I came up with after discussing!
AY17/18 Sem1:
C,A,B,X,C,E,B,D,E,D,A,D

**Comment by xingaporean** [comment]
i posted the official answer key in the telegram group

**Comment by EssWhyy** [comment]
> i posted the official answer key in the telegram group

Nice thanks!

**Comment by nowknowing** [comment]
Hi may I join the telegram group too?
