### ISSUE TITLE
AY19/20 Sem 2 Question 4 - Monads

### ISSUE THREAD

**Issue by wongzw** [nus-cs2030/2021-s1#539]
# Description 
Hi! I have attempted this question and as it has not been really explicitly tested, I am not sure if my answers are correct :) So here I am ~

Below are my answers: 
(a) - None
(b) - L,R,A
(c) - R, A

## Topic: 
Monads

## Screenshot of Question: 
![image](https://user-images.githubusercontent.com/53685088/100521950-2c44ac00-31e2-11eb-9617-57fc3052542f.png)

**Comment by chongweil907** [comment]
The answer shld be :
L
LR
LA

**Comment by Maurice2n97** [comment]
@chongweil907 
I agree with 1) L
But for 2) L shouldn't associativity be violated too?
Correct me if I am mistaken but associativity law for monad is 
monad.flatmap(f).flatmap(g)  = monad.flatmap(x->f(x).flatmap(g))
so supposing monad wraps around v
shouldn't the LHS be a IntMonad of v+4 whereas RHS is intMonad of v +2?
3) Agree with LA

**Comment by wongzw** [comment]
oh wow @chongweil907 do you mind explaining how you get/derive the answers :D

**Comment by chongweil907** [comment]
![image](https://user-images.githubusercontent.com/51086295/100536384-4078bf80-325b-11eb-8dd3-7f08b4ec3814.png)

@wongzw this is the mark scheme from last sem
