### ISSUE TITLE
1920 Sem 2 Qn 2 Stack and Heap

### ISSUE THREAD

**Issue by itsyme** [nus-cs2030/2021-s1#543]
# Description 
In the questions in Qn 2 relating to Stack and Heap how do we create an instance of Bank and Depot given that there are no constructors in the classes?

## Topic: 
Stack and Heap

## Screenshots 

Screenshots (if any)

**Comment by itsyme** [comment]
Can we just use b = new Bank(); and d = new Depot();

**Comment by zechajw** [comment]
Yup if the constructor is not mentioned most likely its just an empty constructor with no inputs like b = new Bank();

**Comment by cl-xy** [comment]
yep, i think you can use the default constructor with no input parameters, ie b = new Bank();

**Comment by Henry-Yuan-He** [comment]
If you do not create any constructor, then there is a default empty constructor.

**Comment by yixin567** [comment]
yepp i think if there is no constructors, java will provide like a default constructor so i think its sth like Bank b = new Bank();
