### ISSUE TITLE
Writing 2 Interfaces

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#55]
If I have 2 interfaces, is it compulsory to put them into 2 java classes or I can write them together in one file? Thank you!

**Comment by charoi** [comment]
Hi @yibinglala ! Interfaces are like classes in the  sense that the naming of each file should be representative of whatever class it contains... ie 1 class per file!

`public interface trial {
    int getArea();
}

public interface Color {
    String getColor();
}
`
For eg, this code with 2 interfaces, what would you have named it as to reduce confusion? Personally, I tried saving this as trial.java, and this happened:

![error](https://user-images.githubusercontent.com/41200981/93009803-db94be00-f5b7-11ea-86aa-21d46c64134d.png)

As you can see, javac will have a compiler error if we do not save the file name to be the same as the object/class/interface! 

When I renamed the Shape interface to be trial, there was 1 less error, but the Color interface will still not compile!

Hence, this shows that 1 file = 1 interface. Hope this helps!

**Comment by domlimm** [comment]
Hey @yibinglala ! Your 2 interfaces should be standalone by themselves. It depends on their functions and what your other classes implementing the interfaces need..

For e.g. in Lab 3, you can consider that `JustRide.java TakeACab.java ShareARide.java` all require a `computeFare(...)` method. You can have an interface created and then have the 3 services implement the interface. In other words, you force the 3 services to have to work out a `computeFare(...)` method.

Also, naming of interfaces usually end with -able.

```java
public interface Serviceable {
    public int computeFare([INPUT_PARAMS]);
}

public class JustRide implements Serviceable {
    public int computeFare([INPUT_PARAMS]) { ... }
}

public class TakeACab implements Serviceable {
    public int computeFare([INPUT_PARAMS]) { ... }
}

public class ShareARide implements Serviceable {
    public int computeFare([INPUT_PARAMS]) { ... }
}
```

Hope it helps!

**Comment by yibinglala** [comment]
> Hi @yibinglala ! Interfaces are like classes in the sense that the naming of each file should be representative of whatever class it contains... ie 1 class per file!
> 
> `public interface trial {
> int getArea();
> }
> 
> public interface Color {
> String getColor();
> }
> `
> For eg, this code with 2 interfaces, what would you have named it as to reduce confusion? Personally, I tried saving this as trial.java, and this happened:
> 
> ![error](https://user-images.githubusercontent.com/41200981/93009803-db94be00-f5b7-11ea-86aa-21d46c64134d.png)
> 
> As you can see, javac will have a compiler error if we do not save the file name to be the same as the object/class/interface!
> 
> When I renamed the Shape interface to be trial, there was 1 less error, but the Color interface will still not compile!
> 
> Hence, this shows that 1 file = 1 interface. Hope this helps!
