### ISSUE TITLE
17/18 ST pp

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#551]
# Description 
hello does anyone have a clear cut method to solve this?

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/71011712/100537632-fdbbe500-3264-11eb-9c3f-b2baaf7f439f.png)

**Comment by merylseow** [comment]
I'd do an `IntStream` that ranges from 0 to `str.length() - 1` then filter based on the condition `str.charAt(i) == str.charAt(i + 1)` and also `str.charAt(i) != str.charAt(i - 1)` to prevent double counting in case there are three adjacent repeated letters. Then after that just perform a `count()` to find the number of occurrences.

**Comment by ghost** [comment]
What if there are 4 adjacent letters? @merylseow

**Comment by fans2619** [comment]
My solution is a little complicated (Ya the same idea with @merylseow ):
```
       int length = str.length();
       return IntStream.range(0, length - 1)
           .map(i -> {
               if (i == 0 && length != 0 && str.charAt(i) == str.charAt(1)) {
                   return 1;
               } else if (str.charAt(i) == str.charAt(i + 1) &&
                       str.charAt(i) != str.charAt(i - 1)) {
                   return 1;
               } else {
                   return 0;
               }})
           .filter(x -> x == 1)
           .count();
```

**Comment by merylseow** [comment]
@scottsusanto let me try to rephrase, so `str.charAt(i) == str.charAt(i + 1)` checks for a consecutive streak, and you need the next part `str.charAt(i) != str.charAt(i - 1)` to check that it's a "new streak" and not actually belonging to a previous streak, so it works even for 4 or more letters. I hope this makes sense to you, if not you can manually test it out to see if it works

**Comment by ghost** [comment]
That clarifies it, thank you! @merylseow

**Comment by e0420658** [comment]
got it!! thanks everyone!!
