### ISSUE TITLE
String Reverse using Streams

### ISSUE THREAD

**Issue by ghost** [nus-cs2030/2021-s1#553]
# Description 
This is easy enough using for loops but anyone knows how to do it using streams? Thank you!

## Topic: 
Specific Topics this question is related to (If Any) 

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/61898858/100537962-b3883300-3267-11eb-9795-86a5d3779982.png)

**Comment by fans2619** [comment]
```
return str.chars()
            .parallel()
            .mapToObj(x -> "" + (char) x)
            .reduce("", (x, y) -> y + x);
```

**Comment by rcdl2222** [comment]
I have a similar solution to @fans2619 , I changed `.mapToObj(x -> "" + (char) x)` to `.mapToObj(x -> Character.toString(x))` to make it more readable.

**Comment by joelwongjy** [comment]
Hi can I check which paper this is from?

**Comment by remuskwan** [comment]
This can also work.
`return str.chars()
                .parallel()
                .mapToObj(c -> (char) c)
                .reduce("", (s,c) -> s + c, (s1, s2) -> s2 + s1);`

**Comment by merylseow** [comment]
@joelwongjy 17/18 Special Term paper if I'm not wrong

**Comment by ghost** [comment]
Yes 17/18 Special Term, apologies for not specifying. I understand the solutions now, thank you everybody!
