### ISSUE TITLE
19/20 Sem1 Pure functions

### ISSUE THREAD

**Issue by tlylt** [nus-cs2030/2021-s1#556]
# Description 
Hi guys, wondering if 3rd and 4th functions are also considered pure?
the 3rd one uses Optional, and 4th one refers to an instance property .
My answer will be yes (NPPP)...
## Topic: 
Functions
## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/41845017/100541466-1c2eda00-327f-11eb-8bb6-158466eaf6bd.png)

**Comment by wongzw** [comment]
I believe both 3 and 4 will be considered as pure function. 

Based on my understanding a a function is called as pure if it satisfies these **two principles**:

- The return value of the function depends only on the input parameters passed to the function.
- The execution of the function has no side effects.

This means that 

- We cannot have any outside variable state mutated inside a pure function.
- For a particular input, we should get the same result, no matter how many times that function has been called. The output should always be the same for that input.


Based on my above understanding, I would agree that your answer is correct (NP, P, P, P). Do correct me if I'm wrong :)

**Comment by darrenhoon** [comment]
got the same answer as you :)
should be pure since they don't modify the input's contents, no side effects, returns a value, and are deterministic

**Comment by chongweil907** [comment]
Yes, i got the same ans too

**Comment by tlylt** [comment]
Thanks guys:)
For the 3rd function, I wonder if we use `Optional.of(c)` instead, which will throw exception if null is passed into it,
will it still be considered pure?

Or in general, if a function might throw an exception(either checked or unchecked), is it still pure?

**Comment by yixin567** [comment]
i think if the function throws an exception, it will no longer be pure... but correct me if im wrong! ><

**Comment by chuashiqi** [comment]
yep, i believe throwing exception is also a side effect so the function will no longer be pure

**Comment by kohkenneth** [comment]
@tlylt yup i dont think it will be a pure function anymore since it throws an exception

**Comment by tlylt** [comment]
hmm okay, because I am thinking of this case where
```
int sum(int a, int b) {
  return a +b;
}
``` 
is surely pure and 
```
int divide(int a, int b) {
  return a/b;
}
```
now becomes unpure?! just because of ArithmeticException(zero division error)...

**Comment by CWei88** [comment]
For number 4, if contents itself is private, wouldn't it throw an error and make number 4 not a pure function?

**Comment by chongweil907** [comment]
> hmm okay, because I am thinking of this case where
> 
> ```
> int sum(int a, int b) {
>   return a +b;
> }
> ```
> 
> is surely pure and
> 
> ```
> int divide(int a, int b) {
>   return a/b;
> }
> ```
> 
> now becomes unpure?! just because of ArithmeticException(zero division error)...

yep that is right

**Comment by wongzw** [comment]
> hmm okay, because I am thinking of this case where
> 
> ```
> int sum(int a, int b) {
>   return a +b;
> }
> ```
> 
> is surely pure and
> 
> ```
> int divide(int a, int b) {
>   return a/b;
> }
> ```
> 
> now becomes unpure?! just because of ArithmeticException(zero division error)...

I believe it only becomes not a pure method if the throw is explicit. But do correct me if im wrong!


For example the following is not pure

  ```
int divide(int a, int b) {
    if (b == 0) {
        throw new cannotDivideByZero();
    } else {
        return a/b;
     }
  }
```

but the following is pure

```
int divide(int a, int b) {
 return a/b;
}
```

Therefore, for the following question:
> For the 3rd function, I wonder if we use Optional.of(c) instead, which will throw exception if null is passed into it,
> will it still be considered pure?

I believe even with Optional, the method will still be pure.

**Comment by limeugene** [comment]
Hi, from this stackoverflow post, it seems that simply throwing an Exception inside a function does not make it impure, however CATCHING an Exception inside a function would make the function impure.

The important part of the post:
"Because throwing an exception inside a function doesn't make that function's result dependent on anything but the argument values and the definition of the function; the function remains pure. OTOH catching an exception inside a function does (or at least can) make that function no longer a pure function."
https://stackoverflow.com/questions/12335245/why-is-catching-an-exception-non-pure-but-throwing-an-exception-is-pure

**Comment by waynetee** [comment]
I think 4 could throw nullpointerexception

**Comment by tlylt** [comment]
> Hi, from this stackoverflow post, it seems that simply throwing an Exception inside a function does not make it impure, however CATCHING an Exception inside a function would make the function impure.
> 
> The important part of the post:
> "Because throwing an exception inside a function doesn't make that function's result dependent on anything but the argument values and the definition of the function; the function remains pure. OTOH catching an exception inside a function does (or at least can) make that function no longer a pure function."
> https://stackoverflow.com/questions/12335245/why-is-catching-an-exception-non-pure-but-throwing-an-exception-is-pure

If this is right, then whether 4 throws NullPointerException or access error, it is still pure. I think I will agree with @limeugene , the explanation makes sense: the function is still pure if "side-effects" are solely induced by the input to the function.

**Comment by wongzw** [comment]
Based on 17/18 Sem 1 PYP, it will suggest that throwing exception will make the method unpure.

>A pure function cannot have side effects – **cannot throw exceptions** (not fff, cannot perform I/O (not ggg), and must always return the **same output given the same input** (not hhh).

![image](https://user-images.githubusercontent.com/53685088/100544443-94ea6200-3290-11eb-8a8f-73de05caf26f.png)

**Comment by chuashiqi** [comment]
lecture 7 slides also seem to suggests that throwing exceptions also make a function impure
![image](https://user-images.githubusercontent.com/70755428/100544901-eba56b00-3293-11eb-8894-ada69bfcca21.png)

**Comment by just-trying-plz** [comment]
hmm, we can also consider AY17/18 SEM1 Qn 7's question on pure functions' answer key into consideration! It stated that side effects includes throwing exceptions and that would probably suggest that throwing exceptions makes a function impure..?  (oh ops, sorry, i just realised it is the same qn as above!)

**Comment by darrenhoon** [comment]
I think what that qn meant was that the function itself cannot have have a line that explicitly throws an exception. ie ... throw new Exception();

This is different from the user receiving an exception (usually runtime since compile time exceptions are caught during compilation) due to their input
eg if the function is

double average(int numerator, int divisor) {
  return numerator/divisor;
}

If we put divisor as 0, it will run into an arithmetic exception. But if it had a line:
if (divisor == 0) {
  throw new ArithmeticException();
}

Then it would be considered impure

**Comment by gabrielloye** [comment]
> I think what that qn meant was that the function itself cannot have have a line that explicitly throws an exception. ie ... throw new Exception();
> 
> This is different from the user receiving an exception (usually runtime since compile time exceptions are caught during compilation) due to their input
> eg if the function is
> 
> double average(int numerator, int divisor) {
> return numerator/divisor;
> }
> 
> If we put divisor as 0, it will run into an arithmetic exception. But if it had a line:
> if (divisor == 0) {
> throw new ArithmeticException();
> }
> 
> Then it would be considered impure

Yes, I think this is right. The side effect of throwing Exceptions probably refers to explicit throwing rather than uncatched runtime exceptions

**Comment by tlylt** [comment]
> I think what that qn meant was that the function itself cannot have have a line that explicitly throws an exception. ie ... throw new Exception();
> 
> This is different from the user receiving an exception (usually runtime since compile time exceptions are caught during compilation) due to their input
> eg if the function is
> 
> double average(int numerator, int divisor) {
> return numerator/divisor;
> }
> 
> If we put divisor as 0, it will run into an arithmetic exception. But if it had a line:
> if (divisor == 0) {
> throw new ArithmeticException();
> }
> 
> Then it would be considered impure

If you are referring to checked vs unchecked exceptions, then there is technically no difference between the example given:
```
double average(int numerator, int divisor) {
return numerator/divisor;
}

double average(int numerator, int divisor) {
if (divisor == 0) {
throw new ArithmeticException();
}
```
They both might throw an unchecked(runtime) exception, and they will both compile just fine. Not sure what you mean by "compile time exceptions"? If you are referring to checked exceptions, then it is probably the case of 
```
//example
double average(int numerator, int divisor) throws IOException {
throw new IOException();
return numerator/divisor;
}
```
If we are talking about explicitly thrown exceptions then yea...probably in the exam I will choose the function that does not contain the keyword "Throw" :joy: ...
