### ISSUE TITLE
Operator Associativity

### ISSUE THREAD

**Issue by wongzw** [nus-cs2030/2021-s1#557]
# Description 
Hi! I'm quite confused over the concept of Operator Associativity. Based on my understanding, in this case, it will return the same output as it is calling Math.max because the order which the items are put into the function does not matter. 

So, am I correct to say that if the function is replaced with `.reduce(100, (x,y) -> x/y)`, then the answer in this case will be A?

## Topic: 
Streams and Parallel?

## Screenshots (if any): 
Insert Images here if necessary
![image](https://user-images.githubusercontent.com/53685088/100541957-4930bc00-3282-11eb-8f26-4246ed917db5.png)

**Comment by kaiyang96** [comment]
Hi! I'm not sure if the screenshot matches your question as I don't see any `Math.max` anywhere.
However to clarify on the concept of 'associativity', let's shorten the operation to 'op' (which can be anything like +, -, *, /).
We say something is associative if x op (y op z) = (x op y) op z. (e.g. x + (y + z) = (x + y) + z)
An example which is not associative if the '/' operation as x / (y / z) = (xz) / y while (x / y) / z = x / (yz)

**Comment by wongzw** [comment]
Oops! I uploaded the wrong screenshot :(

![image](https://user-images.githubusercontent.com/53685088/100543697-99148080-328c-11eb-91db-73d23aac88c4.png)

**Comment by wongzw** [comment]
> Hi! I'm not sure if the screenshot matches your question as I don't see any `Math.max` anywhere.
> However to clarify on the concept of 'associativity', let's shorten the operation to 'op' (which can be anything like +, -, *, /).
> We say something is associative if x op (y op z) = (x op y) op z. (e.g. x + (y + z) = (x + y) + z)
> An example which is not associative if the '/' operation as x / (y / z) = (xz) / y while (x / y) / z = x / (yz)

 I see! Thank you!
