### ISSUE TITLE
AY19/20 Qn3

### ISSUE THREAD

**Issue by kennethkks** [nus-cs2030/2021-s1#568]
# Description 
Not sure how about the answers that i got after running in jshell. Is this related to Covariance and Contravariance? 

## Screenshots (if any): 
![image](https://user-images.githubusercontent.com/72310594/100572484-8ba0da00-3310-11eb-9209-8f2f667b03be.png)

**Comment by coolieKi** [comment]
Yes it is related. A loose rule of thumb would be a producer-like object that produces objects of type T can be of type parameter <? extends T>, while a consumer-like object that consumes objects of type T can be of type parameter <? super T>.

In this case, we can invoke the covariant rule, which says if A2 <: T then Optional<A2> <: Optional<? Extends T>, so we can do like Optional<? extends A2>, Optional<? extends A1> etc.

We can also have contravariant rule, which implied that if S <: A2, then Stream<A2> <: Stream<? Super S>; thus the possible answers of Optional<? super A2>, etc. 

Hope it answers!

**Comment by kennethkks** [comment]
Ok thanks for the explanation!
