### ISSUE TITLE
Lab 3 Codecrunch output in different order

### ISSUE THREAD

**Issue by KeithCZW** [nus-cs2030/2021-s1#57]
![lab3testcase](https://user-images.githubusercontent.com/70742248/93015750-832ce300-f5ee-11ea-80d2-3607c8ba2157.PNG)

As seen in the image, my output is correct but in a different order compared to the expected result. Initially I thought it might have been an issue with my findBestBooking function in level5.jsh but further testing showed that it wasn't the case. Any idea what might be causing this issue?

**Comment by SkullPirateTK** [comment]
Is the output on codecrunch the same as when you run it locally against the same test case?

**Comment by domlimm** [comment]
Hey keith! Check this issue out #52. Could be your `compareTo(...)` method.

**Comment by KeithCZW** [comment]
Ohh, I'll check it out. Thanks!

**Comment by KeithCZW** [comment]
Turns out the issue was the compareto function! Thanks for the help.
