### ISSUE TITLE
Text Editor for Exam 

### ISSUE THREAD

**Issue by rickyaandrew** [nus-cs2030/2021-s1#572]
Hi, just to confirm we are allowed to use any text editors such as VSC for our examination later right? Or are we restricted to vim and notepad

**Comment by zzkzzzz** [comment]
![image](https://user-images.githubusercontent.com/44489498/100580026-2a810280-3320-11eb-9d28-78b7bb1e5631.png)

I think VSC can be used since its a text editor

**Comment by rickyaandrew** [comment]
aightt thanks a lot just wanna confirm if VSC can be used
