### ISSUE TITLE
19/20 Special Term Q9 CompletableFuture

### ISSUE THREAD

**Issue by joelwongjy** [nus-cs2030/2021-s1#573]
# Description 
I wanted to check if my code for this question is correct as I'm still quite confused by this topic.

## Topic: 
CompletableFuture

## Screenshots (if any): 
<img width="848" alt="Screen Shot 2020-11-29 at 10 55 25 PM" src="https://user-images.githubusercontent.com/45819490/100580604-37eabc80-3321-11eb-8cf6-9aef6d9a9060.png">

**Comment by benluiwj** [comment]
tbh you can just return completableFuture( () -> { (copy and paste the entire chunk here) }. But idk if you would be marked down for that tbh

**Comment by KeithCZW** [comment]
This doesn't actually make the code run asynchronously as all you're doing is wrapping the end result in a CompletableFuture. What you should be doing is wrapping the entire function within a CompletableFuture using supplyAsync.
Something like CompletableFuture.supplyAsync( () -> function here );
