### ISSUE TITLE
What does this error mean in Lab3? 

### ISSUE THREAD

**Issue by colintkn** [nus-cs2030/2021-s1#63]
My compareTo() method in Booking returns a double. Is that not allowed? 

![image](https://user-images.githubusercontent.com/65516485/93421518-237f5200-f8e4-11ea-805f-0cb0b06a8843.png)

**Comment by marcuspeh** [comment]
The output that test your booking class uses int so nope. You will need int. Anyways, how did you get double for your compareTo()?

**Comment by domlimm** [comment]
Colin, check this out -> It's the `compareTo` method in the [Comparable Interface](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html#compareTo-T-). And like what Marcus said it has to return an `int`.

**Comment by colintkn** [comment]
Ah, so the class Booking has to implement Comparable<Booking>? 

And does the method compareTo(Booking b) override or overload the interface?

**Comment by marcuspeh** [comment]
I didnt use comparable but if you want to do it, it overrides the compareTo() method

**Comment by domlimm** [comment]
As Marcus suggested, if you'd like, you could just write a `compareTo(Booking b)` method with a return type of `int`. That will work too! Sorry if i caused a confusion!

**Comment by colintkn** [comment]
Alright. I think I'll create my own compareTo method for this lab as marcus suggested. Using the Comparable interface triggered alot of bugs. But thanks for your suggestion dom
