### ISSUE TITLE
Comparator vs Comparable 

### ISSUE THREAD

**Issue by rickyaandrew** [nus-cs2030/2021-s1#65]
# Description 
Hi, after the most recent recitation, i am confused about the difference between Comparable interface and the Comparator interface. when do we use Comparable and when to use Comparator interface? Thanks in advance! 

## Topic: 
Comparable vs Comparator interface

**Comment by wei2912** [comment]
From what I understand, you can view `Comparable` as defining the "natural order" of an object, and `Comparator` for defining alternative orderings. For example, you may have a playlist of songs which have a "natural order" based on the lexicographic order of their titles. However, you may want to define some sorting function that can take in a `Comparator`, and input different alternative orderings e.g. by song length, by number of plays, etc. You can take a look at https://stackoverflow.com/questions/4108604/java-comparable-vs-comparator for more details.

**Comment by cnlinh** [comment]
I think using `Comparable` or `Comparator` is up to personal preference. But for algorithm mods, `Comparator` is definitely more useful as you can call `Arrays.sort(arr, new customComparator())` to sort an array in any way you want for example.

**Comment by charoi** [comment]
Hi @darkinguy ! Can refer to the java documentation on the interface and its abstract methods here: [Comparable Interface](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Comparable.html)
And also: [Comparator Interface](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Comparator.html)
