### ISSUE TITLE
comparing between two parameterized types

### ISSUE THREAD

**Issue by jadenwjh** [nus-cs2030/2021-s1#66]
Type erasure will cause both parameterized types to become type Object during compile time. How can one overcome this?

**Comment by SkullPirateTK** [comment]
My approach is to use `a.isAssignable(b)` to check if `b` is a subclass of `a`, where `a = arr.getClass().getComponentType()` and `b = list.get(0).getClass()`. This will check the type of the array component against the type of the first element of in the list. (Just found out that this can't be used for lab4)
