### ISSUE TITLE
Lab #3 Codecrunch

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#67]
Hi guys I got this error on Codecrunch:
![image](https://user-images.githubusercontent.com/70444061/93633629-d903ef80-fa21-11ea-8cf4-09c0410076fe.png)

Not really sure what it means - my output on vim runs just fine 

Initially i was working with static methods but I got the "variable not declared private final" warning on CC so I changed them to private final and made get() methods.

I used my own compareTo() method instead of implementing the Comparable interface.

Appreciate any help! 

Thanks :)

**Comment by marcuspeh** [comment]
It looks like you made your own bookstub class. I dont think you need it as its one of the checks.

As for super, it refers to a reference of an object from the superclass. So it can only be called from  an object and not from static. Look at this for more details https://www.tutorialspoint.com/why-can-t-we-use-the-super-keyword-is-in-a-static-method-in-java#:~:text=Where%2C%20the%20%22super%22%20keyword,keyword%20from%20a%20static%20method.

**Comment by hhhhanz** [comment]
Oh nevermind it's bc I forgot to upload level5.jsh :') Thanks!
