### ISSUE TITLE
private final issues for project 1

### ISSUE THREAD

**Issue by chongweil907** [nus-cs2030/2021-s1#72]
For the project, i need to increment the number of customers served.
How am I supposed to do it when the class variable is being restricted since we need to set all fields to private final including static fields. 

Thank you !

**Comment by domlimm** [comment]
Hi, you could possibly write getters and setters method in the class storing the variables, where necessary! Not a good practice but for this case...

P.S I'm still on Lab 4 😭

**Comment by lkldev** [comment]
You may also like to create a stats class that increment the stats and return a new stats class, that is one way I can think of...

**Comment by SkyBlaise99** [comment]
Another way is to leave the counting to Main and not Customer.
Each time your priority queue invokes a new event, have some int count to do the counting.

**Comment by marcuspeh** [comment]
I think the statics for Customer need not be final since whether is it final or not will not affect whether the class is mutable or not

**Comment by SkyBlaise99** [comment]
Well but codecrunch will fail you if you dun put private final, which means you cannot have static attributes.

**Comment by marcuspeh** [comment]
I think mine never fail. It still can run

**Comment by chongweil907** [comment]
> I think mine never fail. It still can run

Mine failed 

![image](https://user-images.githubusercontent.com/51086295/93764542-e4cffb80-fc45-11ea-8080-9e6bf32e3339.png)

**Comment by marcuspeh** [comment]
> > I think mine never fail. It still can run
> 
> Mine failed
> 
> ![image](https://user-images.githubusercontent.com/51086295/93764542-e4cffb80-fc45-11ea-8080-9e6bf32e3339.png)

Thats weird. My event also didnt even use private at all. I used protected and it never fail. 

Edit: my bad i realise my private static methods were rejected too

**Comment by chongweil907** [comment]
> You may also like to create a stats class that increment the stats and return a new stats class, that is one way I can think of...

What do u mean by this? I dont get it why the prof decides to ban us from using public static variable

**Comment by SkyBlaise99** [comment]
> > You may also like to create a stats class that increment the stats and return a new stats class, that is one way I can think of...
> 
> What do u mean by this? I dont get it why the prof decides to ban us from using public static variable 

Erm I think he just mean make `Statistic` (stats) class which is created with Customer. Whenever Customer has an update it updates the stats class which returns a new stats class so as to achieve immutable class

**Comment by SkyBlaise99** [comment]
> > You may also like to create a stats class that increment the stats and return a new stats class, that is one way I can think of...
> 
> What do u mean by this? I dont get it why the prof decides to ban us from using public static variable 

Erm I think he just mean make `Statistic` (stats) class which is created with Customer. Whenever Customer has an update it updates the stats class which returns a new stats class so as to achieve immutable class

**Comment by chongweil907** [comment]
Thanks all I managed to finish the project!
