### ISSUE TITLE
Lab 4 Bonus Level

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#75]
# Description 
Hi, I'm facing this issue for the test case.

![image](https://user-images.githubusercontent.com/46486515/93766579-32019c80-fc49-11ea-8b86-781ab35fa424.png)

I have passed the rest of the remaining portion in this test case.

Not too sure how to fix it... And I may be doing things wrongly too. Surprisingly, I managed to complete the `Predicate` part.

```java
// Apologies for the format
    public <R> ImmutableList<R> map(Function<? super T, R> fn) {
        List<T> tempList = new ArrayList<T>(this.list);
        List<R> finalList = new ArrayList<R>();

        ListIterator<T> li = tempList.listIterator();
        while (li.hasNext()) {
            T element = li.next();
            finalList.add(fn.apply(element));
            // li.set(fn.apply((R) element));
        }

        return new ImmutableList<R>(finalList);
        //return toImmutableList((List<T>) finalList);
    }
```

Also, I may being doing it wrongly? I'm unsure of `Function<? super T, R>`

Appreciate any help!

**Comment by SkullPirateTK** [comment]
Second type argument in `Function` has to extend `R`. You can make the code more elegent by using enhanced for-loop. `tempList` is redundant.

**Comment by zzkzzzz** [comment]
```
jshell> Function<Object,Integer> f = x -> x.hashCode()
jshell> ImmutableList<Number> list = new ImmutableList<String>("one", "two", "three").map(f)
```
The Function interface takes a single parameter and returns a single value. In this test case, should take `Object` as input and `Integer` as return type. 

However, this test wants to map a `Sting` list to a `Number` list.  `Object` should be the super class of `String` and `Integer` should be sub class of `Number`.

`Function<? super T, ? extends R> fn`  should work.

**Comment by domlimm** [comment]
Ahhh thank you so much both of you! @SkullPirateTK @zzkzzzz 😃
