### ISSUE TITLE
Project1 test case

### ISSUE THREAD

**Issue by zzkzzzz** [nus-cs2030/2021-s1#76]
Does anyone face the same issue in the last test case? Since I can pass previous test cases, no point can't sort this.
![image](https://user-images.githubusercontent.com/44489498/93778710-c9222080-fc58-11ea-9575-d707e27ab738.png)

**Comment by marcuspeh** [comment]
Yup got the same issue. I solved it by tweaking the comparator for priority queue

**Comment by SkyBlaise99** [comment]
Basically u have 5 different Event, Arrive, Serve, Wait, Done, Leave and if they all clashed at the same timing, u need a tie breaker for them.

**Comment by rickyaandrew** [comment]
yes, you need to tweak your compare to function, first base on time, next base on the customer id

**Comment by SkyBlaise99** [comment]
> yes, you need to tweak your compare to function, first base on time, next base on the customer id

i didnt use customer id lol

**Comment by zzkzzzz** [comment]
I think my Comparator implementation is correct. When I test on my laptop, the sequence is correct. But in Codecrunch the sequence wrong. Is it related to the PriorityQueue size or something else? 
Thanks for helping!
![image](https://user-images.githubusercontent.com/44489498/93847959-fd3e2580-fcda-11ea-9ffc-fb8a35d7736e.png)
![image](https://user-images.githubusercontent.com/44489498/93847981-0b8c4180-fcdb-11ea-9487-d4336267df55.png)

**Comment by marcuspeh** [comment]
> I think my Comparator implementation is correct. When I test on my laptop, the sequence is correct. But in Codecrunch the sequence wrong. Is it related to the PriorityQueue size or something else?
> Thanks for helping!
> ![image](https://user-images.githubusercontent.com/44489498/93847959-fd3e2580-fcda-11ea-9ffc-fb8a35d7736e.png)
> ![image](https://user-images.githubusercontent.com/44489498/93847981-0b8c4180-fcdb-11ea-9487-d4336267df55.png)

What's the tie breaker you used for your comparator?

**Comment by zzkzzzz** [comment]
> > I think my Comparator implementation is correct. When I test on my laptop, the sequence is correct. But in Codecrunch the sequence wrong. Is it related to the PriorityQueue size or something else?
> > Thanks for helping!
> > ![image](https://user-images.githubusercontent.com/44489498/93847959-fd3e2580-fcda-11ea-9ffc-fb8a35d7736e.png)
> > ![image](https://user-images.githubusercontent.com/44489498/93847981-0b8c4180-fcdb-11ea-9487-d4336267df55.png)
> 
> What's the tie breaker you used for your comparator?

compare with start time then customer ID.

**Comment by SkyBlaise99** [comment]
I make sure done event has the highest precedence than any other lol

**Comment by marcuspeh** [comment]
> > > I think my Comparator implementation is correct. When I test on my laptop, the sequence is correct. But in Codecrunch the sequence wrong. Is it related to the PriorityQueue size or something else?
> > > Thanks for helping!
> > > ![image](https://user-images.githubusercontent.com/44489498/93847959-fd3e2580-fcda-11ea-9ffc-fb8a35d7736e.png)
> > > ![image](https://user-images.githubusercontent.com/44489498/93847981-0b8c4180-fcdb-11ea-9487-d4336267df55.png)
> > 
> > 
> > What's the tie breaker you used for your comparator?
> 
> compare with start time then customer ID.

Try using type of event as tiebreaker instead of customerID

**Comment by yhtMinceraft1010X** [comment]
The list of servers is meant to be mutable rite? 

As in, for each event that's created using a server list, the reference to the list in the event attribute is immutable but the internal contents of the list can still change.

**Comment by marcuspeh** [comment]
> The list of servers is meant to be mutable rite?
> 
> As in, for each event that's created using a server list, the reference to the list in the event attribute is immutable but the internal contents of the list can still change.

Yup i think it is. At least i did it like that

**Comment by SkyBlaise99** [comment]
Well my list is mutable, but the Server Objects inside the list shouldn't be. U gotta put a new Server Object in everytime u update the list I guess.

**Comment by yhtMinceraft1010X** [comment]
> Well my list is mutable, but the Server Objects inside the list shouldn't be. U gotta put a new Server Object in everytime u update the list I guess.

I see. I have a similar approach but I'm failing in terms of dequeuing events from PQ so I was wondering if it was list mutability thing.

**Comment by SkyBlaise99** [comment]
> > Well my list is mutable, but the Server Objects inside the list shouldn't be. U gotta put a new Server Object in everytime u update the list I guess.
> 
> I see. I have a similar approach but I'm failing in terms of dequeuing events from PQ so I was wondering if it was list mutability thing.

Well you can always `System.out.println(...);` before and after each event to debug. Hope that helps.

**Comment by zzkzzzz** [comment]
Thanks guys! I found out the problem is about double calculation. I have posted a new issue about it.
