### ISSUE TITLE
Submission of Project 1 to CodeCrunch

### ISSUE THREAD

**Issue by eman-kom** [nus-cs2030/2021-s1#78]
![Capture](https://user-images.githubusercontent.com/29501521/93840628-9d885000-fcc3-11ea-8eea-bd28b4a20075.PNG)
 
i keep getting this error.

Are we not supposed to package it?

**Comment by marcuspeh** [comment]
Your main should be in the package but it should import classes you need from it

**Comment by eman-kom** [comment]
import cs2030.simulator.*; ?

**Comment by SkyBlaise99** [comment]
prof dun like `*`, so import all one by one is the safest approach.
```
import cs2030.simulator.Customer;
import cs2030.simulator.Server;
import cs2030.simulator.Event;
import cs2030.simulator.ArriveEvent;
import cs2030.simulator.ServeEvent;
import cs2030.simulator.DoneEvent;
import cs2030.simulator.WaitEvent;
import cs2030.simulator.LeaveEvent;
```
btw, need to put main inside the package also? I had my main outside the package.

**Comment by eman-kom** [comment]
![Capture](https://user-images.githubusercontent.com/29501521/93845322-f7444680-fcd2-11ea-9343-cc76df57e474.PNG)

Now it cannot find Main.java.

I placed all the files in the same package

**Comment by SkyBlaise99** [comment]
Remove `package... ` from main and try?

**Comment by eman-kom** [comment]
omg it finally works 

thanks a lot !
