### ISSUE TITLE
Project Level 3

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#80]
Hi y'all, I'm kinda struggling on the thinking process on how to do this level.

I know there has to be an `Event` class which should be the parent of the 5 state classes. I've made my `Event` class to be `abstract` with the method of `execute()` to be implemented for all the states.

Do we actually really need 5 state classes? Or could we do all in our `Event` class? I mean it's all about oop right? So can i say we ought to have classes that connect to one another? But how will that actually work?

I just can't wrap my head around on how to do this

Appreciate if anyone can point me in the right direction on this 😢 

Thank you so much!

**Comment by marcuspeh** [comment]
Yes you will need 5 states. So your ArriveEvent execute should return either WaitEvent, ServeEvent or LeaveEvent. WaitEvent will return ServeEvent and ServeEvent will return DoneEvent.
