### ISSUE TITLE
Generics Question

### ISSUE THREAD

**Issue by eman-kom** [nus-cs2030/2021-s1#81]
What is the difference between

`public void someMethod(List<?> e)`

vs

`public <E> void someMethod(List<E> e)`

**Comment by domlimm** [comment]
I think <?> represents any so you don't have to specify like you do in the other method with <E>

**Comment by zzkzzzz** [comment]
I think both of the methods will behave identically. You can use `<T>` inside the method, but wildcard`<?>` can't.

**Comment by marcuspeh** [comment]
I think they are the same. Just that if your method returns something the same type as the list, you need to put <e> infront

**Comment by tanruiquan** [comment]
The second one is a generic method, the first one is not. When you define a generic method with type parameter E, you can use the reference type E in your method. Say you pass a List<(Integer)> in your generic method, E would become Integer.
