### ISSUE TITLE
PriorityQueue Project Level 4

### ISSUE THREAD

**Issue by e0420658** [nus-cs2030/2021-s1#83]
Hi i am quite confused on how the PriorityQueue works. Does it mean that for every ArriveEvent, we should use PriorityQueue to compare between all the events for the stimulation?

**Comment by marcuspeh** [comment]
PriorityQueue basically searches the queue and remove the one with the highest priority, which in this case is the one with the smaller time. So yup, in a way its using PriorityQueue to compare all the events. Look at this link for more info on how to do that

www.geeksforgeeks.org/implement-priorityqueue-comparator-java/amp/

**Comment by e0420658** [comment]
thanks alot!
