### ISSUE TITLE
Practical Exam 1 Queries

### ISSUE THREAD

**Issue by EssWhyy** [nus-cs2030/2021-s1#85]
Hello, I have some questions regarding the upcoming practical exam on week 7, apologies if someone has already asked during lecture/recitation!

•	Is everything until Lecture 5 tested? (i.e. until Exceptions/Assertions?)
•	Is the format similar to that of previous labs, with one question and multiple levels? With marks given for how many test cases are passed?
•	Are there any restrictions on the libraries we are allowed to use?
•	Must we document our code using Javadoc during the exam? 
 
Thanks in advance!

**Comment by chongweil907** [comment]
I am interested in this too

**Comment by ArizonaTay** [comment]
Can we refer to the lecture slides and our lab code during the practical?

**Comment by EssWhyy** [comment]
Bumping this. Can I also assume that we are not allowed to use other text editors besides Vim?

**Comment by hhhhanz** [comment]
Are we allowed to use checkstyle during the exam?

**Comment by rickyaandrew** [comment]
> Bumping this. Can I also assume that we are not allowed to use other text editors besides Vim?

we need to use vim terminal to code during practical. not allowed to use other text editors

**Comment by EssWhyy** [comment]
### Details given in Monday's lecture:

Time: During Respective Lab Session, 5 min to read qn and plan + 90 min to code
What's Tested: Everything up till week 6 (Lecture 5)

Format:

- Level based Question, like previous labs
- Open-Book, but cannot go online to search
- Moderated (given time after exam to fine tune code)
- All code must be done on plab server + vim
- No mention of javadocs (assume not needed)
