### ISSUE TITLE
Checkstyle error

### ISSUE THREAD

**Issue by marcuspeh** [nus-cs2030/2021-s1#86]
Hi! Does anyone know what does this error mean? 
![image](https://user-images.githubusercontent.com/54053213/94017580-2eede400-fde2-11ea-8256-29cc4b48888f.png)

**Comment by domlimm** [comment]
```java
private static final double SERVING_TIME = 1.0;

Class.SERVING_TIME
```

**Comment by marcuspeh** [comment]
> ```java
> private static final double SERVING_TIME = 1.0;
> 
> Class.SERVING_TIME
> ```

Got it thanks
