### ISSUE TITLE
Project Level 4 Private Test Case 8 (sim4_5)

### ISSUE THREAD

**Issue by azr124** [nus-cs2030/2021-s1#87]
<img width="857" alt="testcase" src="https://user-images.githubusercontent.com/71797696/94084651-946cbf80-fe38-11ea-9eec-e7604fd50ebb.png">
Hi, I've been stuck at test case 8 for quite some time and I am not really sure what's my mistake. I did try to backtrack the test case input according to the expected output given by code crunch and tried it in my terminal. The solution "works" in my terminal but not in code crunch. I have also tried switching from comparable to comparator and re-polled the events into a new priority queue each time something is added or remove but it still fails the test case.
Anyone happen to face the same problem?

Thank you!

**Comment by marcuspeh** [comment]
A similar question is asked in #76 . Bascially your tiebreaker has some issue. If both were the same time, you cant sort by customer id

**Comment by azr124** [comment]
Oh my bad, I did not realise there was a closed section of the forum. Thank you!
