### ISSUE TITLE
What does each empty slot of an array point to? 

### ISSUE THREAD

**Issue by ZhangAnli** [nus-cs2030/2021-s1#88]
As I was doing Project 1, I was thinking of creating an array to store all the events generated from the input. 

My final events (DONE and LEAVE) had an execute() function that returned null. 

Thus, I was wondering if empty slots in a new array pointed to "null", or is it some other value like undefined? If the empty slots of an array points to null, then I can use the condition (array[i] == null) to clean up the events.

**Comment by SkyBlaise99** [comment]
iirc, it is null and you should be able to do `array[i] == null`.
However, why do you need to store the `Event` in an array rather than use the priority queue?
