### ISSUE TITLE
Lab 4 Level 5 (passing in more than 1 type parameters)

### ISSUE THREAD

**Issue by hhhhanz** [nus-cs2030/2021-s1#90]
I saw in another GitHub post that we had to use a 2nd generic type parameter as T already exists in the class body so I am using U as follows:
public <U> U[] toArray(U[] arr) { ... }

to check for the ArrayStoreException, i am doing if (T != U) but it gives me a compilation error that says "error: cannot find symbol". Anyone knows why this is happening? Is it because of type erasure? Is (T != U) even a possible thing to do?
![image](https://user-images.githubusercontent.com/70444061/94132781-5c926600-fe92-11ea-8061-fda0c58e2aeb.png)

**Comment by tlylt** [comment]
I think **you** know why that is happening.. You said it yourself :smile:

Yes it is.

I can see where you are coming from. It it natural/logical to me as well to do the checking of different type parameters and then throw exception. One way to go around it is to use something built-in, if you look into the [docs](https://docs.oracle.com/javase/8/docs/api/java/util/List.html) for List interface, maybe they have something you need to solve this level:)

If anyone has a way to do what hhhhanz intended to do, but without error, do enlighten me pls!

**Comment by Terence-Sim** [comment]
@hhhhanz : The compiler does not know that the symbol U means a type. You have to tell it so by inserting `<U>` somewhere in the method signature....

Having said that, you cannot check if T and U are the same type with `T != U`.  And there is no need to do so for this level. Please  read the question carefully: 
"The behavior of toArray of your list is similar to that of toArray of List, with the only difference being the error message associated with the exception thrown."

The question doesn't say that you need to check if T and U are the same type, but rather that the _behavior_ is similar.

**Comment by SkyBlaise99** [comment]
You can read up on [List](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/List.html)

**Comment by hhhhanz** [comment]
Hi @tlylt, Prof @Terence-Sim and @SkyBlaise99, I see what you all are hinting at! Thanks so much!
