### ISSUE TITLE
Lab #4: Immutable List Question

### ISSUE THREAD

**Issue by juayhee** [nus-cs2030/2021-s1#93]
**## Description** 
I was working on the map method in the bonus level. The test case in CodeCrunch creates the mapping function:

`Function<Object,Integer> f = x -> x.hashCode()`

so the function takes in an object and outputs an integer.

My solution was as follows:
![image](https://user-images.githubusercontent.com/5661793/94281965-dead8800-ff81-11ea-943a-61d2324f9e7e.png)

My code will take in the mapping function just fine, but will output an ImmutableList<Integer> as the function specifies.
However, the test case in CodeCrunch assigns the output to an ImmutableList<Number>.

`ImmutableList<Number> list = new ImmutableList<String>("one", "two", "three").map(f)`

I'm not quite sure how to "cast" the output to an ImmutableList<Number>. Surely an `ImmutableList<Integer>` is an `ImmutableList<Number>`, but Java seems to not support this polymorphism and gives me an error. Is there any way to change the return value of the method to match the variable it is assigned to?

**## Topic:** 
Generics

**Comment by rohit0718** [comment]
issue #89 shd help

**Comment by juayhee** [comment]
Perfect. Thanks!
