### ISSUE TITLE
Lab3 Level 3: Failing Private Test cases

### ISSUE THREAD

**Issue by Mavvvvv** [nus-cs2030/2021-s1#94]
**Lab3Level3**
I can't seem to be able to pass the private test cases on CodeCrunch. The order of Bookings are not reflected out in the right order. (expected: XYZXYZXYZ, mine:XXXYYYZZZ). I suspect that this is because of my compareTo method.

(lowestService(request) returns the lowest fare by the driver)

![image](https://user-images.githubusercontent.com/71891733/94284815-7e204a00-ff85-11ea-8465-814e6c61b3ea.png)
![image](https://user-images.githubusercontent.com/71891733/94285110-de16f080-ff85-11ea-99ef-4022a2eb917e.png)

**Comment by JedrekLoo** [comment]
Hi, the compareTo function is supposed to compare booking A(request A) with booking B(request B)
However, if you noticed, your compareTo function is comparing booking A(request A) with booking B(request A), which is why your outputs are coming out in different orders

**Comment by Mavvvvv** [comment]
got it!! Thank youuu!!
