### ISSUE TITLE
[Project 1] Issues with CodeCrunch test cases

### ISSUE THREAD

**Issue by itsyme** [nus-cs2030/2021-s1#98]
<img width="527" alt="Screenshot 2020-09-26 at 2 46 52 PM" src="https://user-images.githubusercontent.com/71922282/94336377-642e4800-0015-11eb-89be-e5c382c2bc4a.png">
<img width="366" alt="Screenshot 2020-09-26 at 2 47 02 PM" src="https://user-images.githubusercontent.com/71922282/94336379-67293880-0015-11eb-86a0-8ed96f23c989.png">
I don't understand why there is an extra 1 which really doesn't make any sense I have been trying to debug this for hours and it still has that extra 1 on codecrunch but not on terminal. This is test case8/9 sim4_5.

**Comment by rootkie** [comment]
It seems like your "customer 1 done serving by server 1" happened after customer 3 served by server 1. How is 3 getting served by 1 when server 1 is not done serving customer 1? Something is definitely wrong with your scheduling.

**Comment by fans2619** [comment]
What about considering the precision problem? I also encountered this problem and I found it was due to the way I write my comparator. Think about two floating-point numbers may not be the same to the computer although they seem the same to you. One may be 3.0340000000000 and the other may be 3.0340000000001. It's due to storage of floating-point numbers I think.

**Comment by fans2619** [comment]
Just find [one previous discussion](#82 )!

**Comment by fans2619** [comment]
Just find [one previous discussion](https://github.com/nus-cs2030/2021-s1/issues/82#issue-706707393)!

**Comment by itsyme** [comment]
> What about considering the precision problem? I also encountered this problem and I found it was due to the way I write my comparator. Think about two floating-point numbers may not be the same to the computer although they seem the same to you. One may be 3.0340000000000 and the other may be 3.0340000000001. It's due to storage of floating-point numbers I think.

Thank you I will check this out

**Comment by itsyme** [comment]
> What about considering the precision problem? I also encountered this problem and I found it was due to the way I write my comparator. Think about two floating-point numbers may not be the same to the computer although they seem the same to you. One may be 3.0340000000000 and the other may be 3.0340000000001. It's due to storage of floating-point numbers I think.

Thank you so much it works now
