### ISSUE TITLE
Project: How does each customer know which server is available?

### ISSUE THREAD

**Issue by domlimm** [nus-cs2030/2021-s1#99]
Hi, odd question to ask at this juncture but... as the title 

So, we've to get user's input on how many servers there will be and the timings for the arrival of customer/s. So each arrival time given = 1 customer

I'm sure we've our own way and thinking on doing this project. What I did was:

1. Retrieve user input
2. Initialise a Customer and Servers list
3. Create a `PriorityQueue<Event>`
4. Add a new ArriveEvent with inputs of Customer and the list of servers.
```java
// Suppose all 5 states/events have a constructor of
Event(Customer c, List<Servers> s);

PriorityQueue<Event> pq = new PriorityQueue<Event>(event_comparator());

for (Customer c: customers) {
    pq.add(new ArriveEvent(c, this.servers));
}
```
5. Iterate through the PriorityQueue and execute this line of code `e.execute();`
6. Then each execute will look at some conditions and proceed from those conditions

The question is, **how will the next Customer know which server is available and so forth**?

Because when a customer has been served/a server has finished serving the customer, rightfully we're supposed to update that particular server's availability to **TRUE**. How is the list of servers passed onto other customers?

Are all the events in the PriorityQueue sharing just 1 PARENT/SUPER Servers List, I can't really see it...

I think I'm at that stage where I can't exactly visualise what's happening (the question) even though SOP statements have been used to slowly look at how everything works. Everything's kinda foggy 😞 

Thanks guys!!!

**Comment by lkldev** [comment]
You might want to consider whether should all the customer be added into the pq right away. As the first customer may be served before the second customer arrives, the server would have been updated. Thus you should consider integrating the creation of new ArriveEvent while processing the events in the queue. Hope this helps :)

**Comment by domlimm** [comment]
Hi kl, thanks for your input. Yeah I guess maybe because I added all the Arrival for the customer/s that's why I fail some of the test cases as the ArriveEvent's execute() couldn't see the updated serversList to decided whether the next customer that execute() should return Serve or Wait event. Thanks a bunch!!
